CONTRIBUTING.adoc
README.md

Fixes GH-1 (https://github.com/spring-projects/spring-kafka/issues/1)
* add `CONTRIBUTING.adoc` describing the Contribution procedure
* mention Contribution Guidelines in the `README.md`
* mention CODE_OF_CONDUCT in the `README.md`

GH-1: Add Contribution Guidelines

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/resources/log4j.properties

Fixes GH-3 (https://github.com/spring-projects/spring-kafka/issues/3)

GH-3:  Fix race condition in the partitions test 

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java

Fixes #33 
__Will fix docs in #31 __

GH-33: Use Consumer/Producer Constants in Tests

---

spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java

GH-53: Fix @KafkaListener autoStartup

---

build.gradle
spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java

GH-71: Remove GS Collections from -test

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java

Fixes #62
Resolves #72
See the discussion on GH-62 `commitAsync()` is not currenly reliable.
Use `commitSync()` by default; add `syncCommits` property to the containers
(default true).
Also allow a user-injected commit callback (GH-72)

GH-62; commitSync() By Default

---

build.gradle
spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafka.java
spring-kafka/src/main/java/org/springframework/kafka/config/ConcurrentKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/SimpleKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/quick-tour.adoc

Resolves #75
Add `syncCommit` and `commitCallback` to container factory.

GH-75: ContainerFactory Improvements

---

spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Having the async consumption nature we have to `spy` the `Consumer` before the real consumption.
Otherwise we can end up with the fact that we pass all desired phases in one thread, but another hasn't been spied yet to be verified in the end properly.
https://build.spring.io/browse/SK-SON-97/

Fix race condition in the `KafkaMessageLCTests`

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/config/ContainerProperties.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

API change prevented an app compiled against 1.0 running with 1.1.

Restore ErrorHandler Setter

---

spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

The `ConcurrentMessageListenerContainerTests#testDefinedPartitions()` relies on the fact that previous batches have been committed to Broker
and starts a new test-case for defined offset.
Since commits are happened on the separate Thread from the `stop()` and more over the `consumer.wakeup()` may discard the currently queued commit request,
to properly perform assertions we have to wait until commits are finished and only after that stop the container.
* Since `testDefinedPartitions()` doesn't use concurrency, move the test to the `KafkaMessageListenerContainerTests`
* Add `stopLatch` barriers before each `stop()` and pass barriers on their `commitSync()`

Fix race condition in test on offset commits

---

spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/si-kafka.adoc

See spring-projects/spring-integration-kafka#148

SI PayloadType Docs

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java

Resolves https://github.com/spring-projects/spring-kafka/issues/192

GH-192: KafkaEmbedded Lifecycle Methods to Public

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Fixes #268
Previously, the container's internal rebalance listener committed any manual acks before
calling a user `RebalanceListener`. If that listener added more acks, they were not committed
until after the rebalance, which is an error.
Defer committing manual acks until after the user listener (if any) is called so all such
acks are committed.
Add a test case:
- two partitions; send two messages to each
- ack the first message in each partition in the listener
- start a second container to force a rebalance
- ack the second message in each partition in the rebalance listener
- assert that the offsets were committed correctly
__cherry-pick to 1.1.x__

GH-268: Defer Manual Commits Until After Listener

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

Further work for #262
Use `Map.compute...` methods instead of discrete logic.

GH-262: Use compute... for Acks Reduction

---

src/reference/asciidoc/kafka.adoc

Adds text describing adding the MessagListener to a ContainerProperties object and creating the MessageListenerContainer using those properties.

Explanation for MessageListener/MessageListenerContainer

---

spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionInitialOffset.java

This PR polishes Javadoc to be aligned with its parameter.

Polish Javadoc

---

spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/FilteringBatchMessageListenerAdapter.java
spring-kafka/src/test/java/org/springframework/kafka/adapter/FilteringAdapterTests.java

Restore `ackDiscarded` to batch filtering listener adapter.

GH-280: Polishing - Restore ackDiscarded

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

No need to be inside while loop, so this PR moves it outside.

Move setting listenerType outside while loop

---

spring-kafka/src/main/java/org/springframework/kafka/core/KStreamBuilderFactoryBean.java
spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsTests.java
src/reference/asciidoc/streams.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/308
**Cherry-pick to 1.2.x & 1.1.x**

GH-308: KafkaStreams options on KStreamBuilderFB

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafka.java

Typo : javadoc fix, receied changed to received

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java

Fixes #338 
__cherry-pick to all 1.x__

GH-338: Add Timeout To Producer Close

---

spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/355

GH-355: Detect Misconfigured Manual @KafkaListener

---

spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

The container was stopped by the test before the transaction was comitted.
- Change the container to isolation `read_committed`
- Send a transactional message from the listener
- Change the container to listen to both topics
- Don't stop the container until the transactional message is received
- Remove the loop waiting for the consumer position to go to 1

GH-362: Fix Race Condition in TxContainerTests

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
spring-kafka-test/src/test/java/org/springframework/kafka/test/hamcrest/AddressableEmbeddedBrokerTests.java

Allow An Explicit Port for EmbeddedKafka

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java

Resolves https://github.com/spring-projects/spring-kafka/issues/411
The 0.11 client has a new `AdminClient`; use it instead of interacting with
Zookeeper in the `EmbeddedKafka` when provisioning test topics.

GH-411: Use AdminClient to Provision Test Topics

---

src/reference/asciidoc/kafka.adoc

Fixes spring-projects/spring-kafka#400

GH-400: Improve Producer Config sample in the Doc

---

build.gradle

Resolves https://github.com/spring-projects/spring-kafka/issues/428

Add Manifest Properties including Jigsaw Module

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java

Updated the javadoc in defaultTopic setter and getter methods.

Update java doc

---

build.gradle
src/reference/asciidoc/si-kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/397

GH-397: Error Handling Docs

---

.gitignore

Resolves: https://github.com/spring-projects/spring-kafka/issues/448

GH-448: Ignore .DS_Store on MacOS platform

---

src/reference/asciidoc/si-kafka.adoc

Resolves: spring-projects/spring-kafka#452
**Cherry-pick to 2.0.x**

GH-452: Add SI Java DSL samples to Docs

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/480

GH-480: KafkaAdmin - increase partitions

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafkaStreams.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaStreamsDefaultConfiguration.java
spring-kafka/src/main/java/org/springframework/kafka/core/StreamsBuilderFactoryBean.java
spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsTests.java
src/reference/asciidoc/streams.adoc

Fixes: spring-projects/spring-kafka#479

GH-479: Update Kafka Streams API and Docs

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

This PR removes unnecessary logging guards.

Remove unnecessary logging guards

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/config/ContainerProperties.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerBatchModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerRecordModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/518

GH-518: Add clientIdPrefix to @KafkaListener

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/config/ContainerProperties.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
src/reference/asciidoc/kafka.adoc

https://stackoverflow.com/questions/47914528/how-to-print-spring-kafka-configurations-in-logs-using-log4j/47914975#comment82800055_47914975

Add an option to log container properties

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
src/reference/asciidoc/kafka.adoc

[Issue #527](https://github.com/spring-projects/spring-kafka/issues/527)

527: Replace DefaultFormattingConversionService with Bean

---

spring-kafka/src/main/java/org/springframework/kafka/core/StreamsBuilderFactoryBean.java
spring-kafka/src/test/java/org/springframework/kafka/core/StreamsBuilderFactoryLateConfigTests.java

Make StreamsConfig customizable in StreamsBuilderFactoryBean
Set the phase on StreamsBuilderFactoryBean to Integer.MAX_VALUE - 1000
Adding tests

GH-548: StreamsBuilderFactoryBean enhancements

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java

- supports the SIK outbound gateway to determine if there's a default reply topic.
- supports the SIK validating a reply topic header if present in the outbound message.

Replying template - add getter for reply topic(s)

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

Fixes https://github.com/spring-projects/spring-kafka/issues/566
In case the user listener hands over the `Acknowledgment` to another thread.
__backports will need `compute...` s removed; will submit after review__

GH-566: Use ConcurrentMaps for offset management

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java

Resolves https://github.com/spring-projects/spring-kafka/issues/582
Let the OS select the port instead of attempting to find an available port.

GH-582: Use a truly random port in KafkaEmbedded

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/ChainedKafkaTransactionManager.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaAwareTransactionManager.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Enable transaction synchronization without the need for user code to
send the offset(s) to the transaction.

Add ChainedKafkaTransactionManager

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

See: https://github.com/spring-projects/spring-integration-kafka/issues/198

SIKGH-198: Add pause/resume to Listener Containers

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/599
Previously, initial seeks using `TopicPartitionInitialOffset`s only worked with
a provided `offset`. The `SeekPosition` field was ignored, and only used for
subsequent seek operations.
`initPartitionsIfNeeded()` now processes both styles of initial offset.

GH-599: Fix initial seek

---

spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/601

GH-601: @KafkaListener: Support List<Message<Foo>>

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/566
If `Acknowledgment.acknowledge()` is called on a foreign thread, there is a concurrency
problem with the `offsets` field; the consumer thread might `clear()` unprocessed acks.
Furthermore, `AckMode.MANUAL_IMMEDIATE` cannot use the `Consumer` object if the ack
is called on a foreign thread - the `Consumer` is not thread-safe.
- Revert `offsets` to simple `HashMap`s
- Only reference `offsets` on the consumer thread
- enqueue foreign acks into the `acks` queue (even "immediate" acks)
**Cherry pick to 2.0.x (and 1.3.x, fixing the lambda in the test and the diamond operators).**

GH-566: Ack Concurrency Issue

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/support/SendResult.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/623
Grab ack count before moving acks to offsets.

GH-623: Fix AckMode.COUNT

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/MissingGroupIdTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/631

GH-631: Fail fast with missing required group.id

---

src/reference/asciidoc/kafka.adoc

Changed log-compaction url. The old is not available, page deleted.

Change log-compaction url

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/637
Wrong timestamp used for event publication causing invalid events.
__cherry-pick to 2.0.x, 1.3.x__

GH-637: Fix spurious nonresponsive consumer events

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java

https://stackoverflow.com/questions/50179109/error-with-spring-kafka-unit-testing-failed-to-determine-testutils-createbroker/50179519#50179519

Improve exception message with jar mismatch

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/676. we have also migrated `topics` from `array` to `set`.

GH-676: KafkaEmbeddedHolder - creating and adding topics.

---

spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
src/reference/asciidoc/kafka.adoc

Emit WARN log for @SendTo with void return

---

spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java

- Modify the warning message if there is an error handler
- move the void check to the assert instead of the if statment

Polishing for previous commit

---

spring-kafka/src/main/java/org/springframework/kafka/support/CompositeProducerListener.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/691

GH-691: Add CompositeProducerListener

---

spring-kafka/src/main/java/org/springframework/kafka/support/converter/BytesJsonMessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/StringJsonMessageConverter.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/693

GH-693: Add BytesJsonMessageConverter

---

build.gradle
src/dist/notice.txt

**cherry-pick to 2.1.x, 2.0.x, 1.3.x**

Add licence and notice to all artifacts

---

spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java

Fixes https://github.com/spring-projects/spring-kafka/issues/686
**Cherry-pick to 2.1.x, 2.0.x, 1.3.x**

GH-686: Handle tombstones in Json Ser/Deser

---

spring-kafka/src/main/java/org/springframework/kafka/support/CompositeProducerListener.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java

Fix varargs warn for CompositeProducerListener

---

spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/731
- Auto detect reply topic/partition
- Improve docs to explain how to use a shared reply topic
- Add boolean to reduce log level for unexpected responses

GH-731: Replying template improvements

---

src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/650

GH-650: Pause/Resume doc example

---

spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java

This PR merges assertion conditions into one `if` condition in `MessagingMessageListenerAdapter`.

Merge assertion conditions into one in MessagingMessageListenerAdapter

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/739

GH-739: Custom (De)Serializer Doc Improvement

---

spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
spring-kafka/src/main/java/org/springframework/kafka/core/package-info.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

Also use a single `Duration` object for polling.

@NonNullApi for core package

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
spring-kafka/src/main/java/org/springframework/kafka/support/SeekUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/763
Add recovery capability to the default ARP.

GH-763: DefaultAfterRollbackProcessor, SeekToCurrrentErrorHandler: recovery

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/support/KafkaHeaders.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/767
Publish failed records to a dead-letter topic.

GH-767: Add DeadLetterPublishingRecoverer

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java

Fixes https://github.com/spring-projects/spring-kafka/issues/774
**cherry-pick to 2.1.x, 2.0.x, 1.3.x**

GH-774: Rethrow e in KT.executeInTransaction()

---

src/reference/asciidoc/kafka.adoc

See: https://stackoverflow.com/questions/52077027/kafkalistener-concurrency-multiple-topics/52078148#52078148
**cherry-pick to 2.1.x, 1.3.x**

Doc: Partition Assignment

---

spring-kafka/src/main/java/org/springframework/kafka/support/converter/DefaultJackson2JavaTypeMapper.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/Jackson2JavaTypeMapper.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/794

GH-794: Json Deserializer - remove type headers

---

src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/784

GH-784: Doc polishing

---

spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsConfiguration.java
spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java

Add `ConversionService` to convert map values to String.
Also use `Class.getName()`.

KafkaStreamsConfiguration Conversion

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java

Currently a `byte[]` gets converted to a String using an
`ArrayToStringConverter`, which is not very useful.
Add a `BytesToStringConverter`.

@KafkaListener Add BytesToStringConverter

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
src/reference/asciidoc/kafka.adoc

Looks like connectionFactory from docs doesn't exist anymore

Doc polishing, remove connectionFactory

---

spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java

Fix DEBUG error message about reply topics

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java

Resolves https://github.com/spring-projects/spring-kafka/issues/835
Illegal state instead of `ClassCastException`.

GH-835: LCF: check error handler is the right type

---

src/reference/asciidoc/kafka.adoc

https://stackoverflow.com/questions/52978691/registering-kafkalistenercontainers-with-kafkalistenerendpointregistry/52980393#comment92932278_52980393

Clarify listener endpoint registry bean

---

spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/MultiMethodKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/847

GH-847: Support placeholders in @SendTo

---

spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ContainerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java

Resolves https://github.com/spring-projects/spring-kafka/issues/850

GH-850: Stop container on error

---

spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppingEvent.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/867

GH-867: Add ConsumerStoppingEvent

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/hamcrest/KafkaMatchers.java
spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/InvocationResult.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RecordMessagingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java

Stashed changes missed from yesterday's commits - I was surprised the count only went down by 15; this explains it.

Address several Sonar issues

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
spring-kafka-test/src/main/java/org/springframework/kafka/test/core/BrokerAddress.java
spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/ContainerTestUtils.java
spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPausedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerResumedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppingEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ContainerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerIdleEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/NonResponsiveConsumerEvent.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareListenerErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerStoppingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaListenerErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/FilteringBatchMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/FilteringMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/InvocationResult.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/support/LogIfLevelEnabled.java
spring-kafka/src/main/java/org/springframework/kafka/support/LoggingProducerListener.java
spring-kafka/src/test/java/org/springframework/kafka/support/LogIfLevelEnabledTests.java

Fix magic numbers
Consumer transient in exception

Sonar: Fix classes with B,C maintainability

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
src/reference/asciidoc/testing.adoc

See https://github.com/spring-io/start.spring.io/pull/9

Add Docs for @SpringBootTest

---

spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPausedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerResumedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppingEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ContainerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/KafkaEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerIdleEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/NonResponsiveConsumerEvent.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
src/reference/asciidoc/kafka.adoc

Fixes: https://github.com/spring-projects/spring-kafka/issues/878

GH-878: Add parent container to container events

---

src/reference/asciidoc/kafka.adoc

Rsolves https://github.com/spring-projects/spring-kafka/issues/854

GH-854: Docs about Filtering Batch adapter

---

src/reference/asciidoc/kafka.adoc

https://stackoverflow.com/questions/53573729/spring-kafka-autoconfiguration-issue-using-replyingkafkatemplate/53575126#53575126

Polish Replying Template config with Boot

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/906

GH-906: @KafkaListener Javadoc Improvements

---

README.md

Corrected code of conduct link to redirect to the CODE_OF_CONDUCT.adoc file

Updated README.md code of conduct link

---

src/reference/asciidoc/si-kafka.adoc

Polish doc

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/942
Suppress topic/partition already exist exceptions - possible race when multiple
instances of the same app start concurrently.

GH-942: KafkaAdmin Improvements

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java

https://stackoverflow.com/questions/54466662/kafka-consumer-picking-up-topics-dynamically/54467119#comment95745500_54467119

Improve Javadocs for Topic Patterns

---

spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

https://build.spring.io/browse/SK-SON-1074/
Container could be paused before receiving the message that fails to commit.
- remove the pause/resume and use latches
- add some retries, but don't fail if the rebalance doesn't occur
- reduced test runtime from ~30 seconds to ~5 seconds

Fix race condition in test case

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/946

GH-946: Detect Unnecessary Replying Template

---

src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/897

GH-897 Docs: wiring Producer/Consumer interceptors

---

build.gradle
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerBatchModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerRecordModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RemainingRecordsErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/781
Also fix updateCopyright gradle task.

GH-781: Add commitSyncTimeout container property

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaStreamsDefaultConfiguration.java
spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanCustomizer.java
spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsTests.java
src/reference/asciidoc/streams.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/981

GH-981: Add StreamsBuilderFactoryBeanCustomizer

---

spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/983
When skipping non-retryable exceptions, we still need to seek the
remaining topic/partitions.

GH-983: Seek remaining records

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

From 78.5% to 83.8% and fix bugs found:
- Deprecate unused ctor
- Fix check for proper error handler for listener type

Improve container test coverage

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc

Rename property to `commitRecovered`.

GH-990: Polishing

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1014

GH-1014: Fix setSyncCommits Javadocs

---

build.gradle
spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java

Bump kafka-clients to 2.2.0

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1027

GH-1027: Set ackOnError to false by default

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

With a transactional container if committing the offsets fails
during a rebalance, we would leave the producers open.
Move the close to a finally block.

Fix close producers after a rebalance

---

spring-kafka/src/main/java/org/springframework/kafka/support/converter/ByteArrayJsonMessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/BytesJsonMessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/JsonMessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/ProjectingMessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/StringJsonMessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/StringOrBytesSerializer.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/converter/ProjectingMessageConverterTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/StringOrBytesSerializerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

- extract common superclass for all value types
- add `ByteArrayJsonMessageConverter
- support `Bytes` in `ProjectingMessageConverter`
- docs for `ProjectingMessageConverter`

JsonMessageConverter Polishing

---

build.gradle

Resolves https://github.com/spring-projects/spring-kafka/issues/1084

Add streams and streams test utils as test deps

---

spring-kafka/src/test/java/org/springframework/kafka/streams/HeaderEnricherTests.java

Looks like I pushed this a few seconds too late 😦

HeaderEnricher: Add test using stream test utils

---

spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsConfiguration.java
spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerRecordRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandler.java
spring-kafka/src/main/java/org/springframework/kafka/streams/package-info.java
spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsBranchTests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsJsonSerializationTests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/streams.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1082
Needs docs.

GH-1082: Dead Letter Streams Deserialization

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1095

GH-1095: Add thread-bound producers

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1101

GH-1101: Overide transactionIdPrefix

---

spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingSerializer.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1126

GH-1126: Add delegating Serializer/Deserializer

---

spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerde.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsJsonSerializationTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerdeTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/streams.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1139

GH-1139: Json Serialization: Add Fluent API

---

spring-kafka/src/main/java/org/springframework/kafka/listener/CompositeRecordInterceptor.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1142

GH-1142: Add CompositeRecordInterceptor

---

src/reference/asciidoc/testing.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1144

GH-1144: Doc. @EmbeddedKafka property limitation

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1145
**cherry-pick to 2.0.x, 1.3.x**

GH-1145: Backport NPE Fix

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
src/reference/asciidoc/testing.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1144

GH-1144: Fix @EmbeddedKafka with @SpringBootTest

---

src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1151

GH-1151: Doc: Clarify Stateful Retry Recovery

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/ConcurrentKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionInitialOffset.java
spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionOffset.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/MissingGroupIdTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1158

GH-1158: Deprecate TopicPartitionInitialOffset

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractConsumerSeekAware.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AbstractDelegatingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

- also handle late arriving time stamp seek requests while processSeeks() is already running.

Add seek helper abstract class

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java

GH-1196: Polishing after backports

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/GenericErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/support/SeekUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

- `SeekToCurrentErrorHandler`
- `AfterRollbackPostProcessor`

Add BackOff to SeekToCurrent components

---

src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/si-kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1204

GH-1204: SIK docs for transactions

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1203
Common properties that can be used with any consumer, not just a consumer that's
in a container.

GH-1203: Extract ContainerProperties Super Class

---

src/reference/asciidoc/kafka.adoc

Update snippet to correct return type and misspelling

Fixes https://github.com/spring-projects/spring-kafka/issues/1226 

---

spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/1234
Previous implementation assumed the first redelivered record would be
the one that failed; this is not always the case.
Maintain state for each topic/partition/offset.

GH-1234: Fix FailedRecordTracker

---

build.gradle
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Time calls to the listener.
**Review only; needs docs**

Add Micrometer Timers to the KMLContainer

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1283
Avoid `InstanceAlreadyExistsException` s when the user supplies a custom
`client.id`.

GH-1283: Unique client.id for each producer

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java

Deprecate `ZkClient` in favor of Kafka's `ZooKeeperClient`
in preparation for the 2.4 clients, where this class is removed.
Also only create the client on-demand because it is not used internally
by the embedded broker.

Deprecate ZkClient in embedded broker

---

spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java

Fixes https://github.com/spring-projects/spring-kafka/issues/1294

GH-1294: Fix mapping empty String header values

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java

Resolves: https://github.com/spring-projects/spring-kafka/issues/1293
`getSingleRecord()` would fail prematurely if records were present in other topics
- Add a loop to prevent early exit
- Always reset the offsets for other topics before assertions

GH-1293: Fix KafkaTestUtils.getSingleRecord()

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/assertj/KafkaConditions.java
spring-kafka-test/src/test/java/org/springframework/kafka/test/assertj/KafkaConditionsTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
src/reference/asciidoc/testing.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1299
**cherry pick to 2.2,x**

GH-1299: Add AssertJ keyValue Condition

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/ContainerTestUtils.java
spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1323

GH-1323: s-k-test remove hard AssertJ dependency

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1358

GH-1358: KTU.getRecords() - add minRecords option

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackBatchTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1363

GH-1353: Fix sleep with BatchListener nack

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
src/reference/asciidoc/kafka.adoc

@garyrussell as you wrote on Gitter it's a little bit tricky to add custom argument resolvers, because the order is important. 
But in my opinion we can add custom resolvers before payload resolver - what do you think about it?

GH-1362: Add the possibility of adding custom HandlerMethodArgumentResolver

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchToRecordAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DefaultBatchToRecordAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/support/LoggingProducerListener.java
spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/BatchListenerWithRecordAdapterTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1356
Also fix deprecation warning in `LoggingProducerListener`.

GH-1356: Add BatchToRecordAdapter

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1388

GH-1388: Support non-Tx with a Tx Template

---

src/reference/asciidoc/si-kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1397

GH-1397: Docs for S-I-K Channels

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DeliveryAttemptAware.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
spring-kafka/src/main/java/org/springframework/kafka/support/KafkaHeaders.java
spring-kafka/src/main/java/org/springframework/kafka/support/SimpleKafkaHeaderMapper.java
spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/SimpleKafkaHeaderMapperTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1402

GH-1402: Container retries delivery attempt header

---

spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1399

GH-1399: Reply Message<?> Headers

---

spring-kafka/src/main/java/org/springframework/kafka/listener/BatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerAwareBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerInvokingBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RetryingBatchErrorHandler.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RetryingBatchErrorHandlerIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RetryingBatchErrorHandlerTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1382

GH-1382: RetryingBatchErrorHandler

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/MicrometerHolder.java
spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/package-info.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1366

GH-1366: Add Micrometer timers to KafkaTemplate

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

- send the offset to the transaction instead of committing via the consumer.
**I will do backports after review/merge**

Fix manual acks with transactions

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

- now that the transactional producer is held in a field, don't pass as an argument.

Container Refactoring

---

spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/transaction/ResourcelessTransactionManager.java

- add an `InOrder` to verify commit sequence for a Kafka transaction synchronized
with another.

Polish transaction synchronization test

---

samples/sample-01/README.adoc
samples/sample-01/pom.xml
samples/sample-01/src/main/java/com/example/Application.java
samples/sample-02/pom.xml
samples/sample-02/src/main/java/com/example/Application.java
samples/sample-03/pom.xml
samples/sample-03/src/main/java/com/example/Application.java
samples/sample-03/src/main/resources/application.yml

- auto config of error handler and message converter based on listener type.

Update samples to use current Boot autoconfigure

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1430

GH-1430: Support Producer Property Overrides

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/RoutingKafkaTemplate.java
spring-kafka/src/test/java/org/springframework/kafka/core/RoutingKafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

- select the producer factory using the topic name

Add RoutingKafkaTemplate

---

spring-kafka/src/main/java/org/springframework/kafka/KafkaException.java
spring-kafka/src/main/java/org/springframework/kafka/listener/BatchListenerFailedException.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/support/SeekUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1435

GH-1435: Add RecoveringBatchErrorHandler

---

src/reference/asciidoc/streams.adoc

* Fix wrong prop keys
* Add `BOOTSTRAP_SERVERS_CONFIG`(boostrap.servers) configs
* Fix KStreams example to executable.

Fix streams docs

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxRollbackTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1443

GH-1443: Add support for new EOS BETA

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1445

GH-1445: Handle RebalanceInProgressException

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
src/reference/asciidoc/kafka.adoc

See https://github.com/spring-projects/spring-kafka/issues/1430
When cloning the producer factory, transfer the remaining factory properties.

GH-1430: Polishing; Copy Remaining Properties

---

spring-kafka/src/main/java/org/springframework/kafka/KafkaException.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerStoppingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaExceptionLogLevelAware.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RetryingBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/StatefulRetryTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1461

GH-1461: Configurable log level for EH Exceptions

---

build.gradle

Upgrade spring-doc-resources from version 0.2.0 to version 0.2.1
to get a bug fix (setting the display width for HTML output).

Upgrade spring-doc-resources

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java

See https://github.com/spring-projects/spring-kafka/issues/194
See https://github.com/spring-projects/spring-kafka/issues/345
See https://github.com/gradle/gradle/issues/11195
**cherry-pick to 2.4.x, 2.3.x, 2.2.x, 1.3.x**

Prevent EmbeddedKafkaBroker exiting the JVM

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java

Close thread bound producers after reset

---

build.gradle
src/reference/asciidoc/kafka.adoc

Upgrade Asciidoctor to the latest version, to eliminate technical debt.
I also fixed an invalid reference.

Upgrade Asciidoctor

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java

Unnecessary to perform the redundant commit on assignment if there
is already a committed offset for a partition.
It is only necessary when using `latest` auto offset reset and when
there is no current committed offset.

Don't commit on assignment with existing commit

---

spring-kafka/src/main/java/org/springframework/kafka/support/converter/DefaultJackson2JavaTypeMapper.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1483

GH-1483: Trust target class sub-packages

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
src/reference/asciidoc/kafka.adoc

See https://github.com/spring-projects/spring-kafka/pull/1485

GH-1485: Option to suppress single client.id

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1494
**I will back-port as needed after review/merge**

GH-1494: Fix NPE in DeadLetterPublishingRecoverer

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1496
Certain commit exceptions are retriable.
**I will back-port as necessary**

GH-1496: Handle RetriableCommitFailedException

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1499
**I will do the backports because I expect many conflicts.**

GH-1499: Option to suppress ConsumerRecord logging

---

spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonTypeResolver.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1506
Add the topic to method-based type resolution.

JsonDeserializer Type Resolution Improvements

---

spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerTests.java

GH-1509 Support nested BatchListenerFailedException in RecoveringBatchErrorHandler

---

spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerPostProcessor.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1520
To assist with Sleuth instrumentation.

GH-1520: Add Producer/Consumer Post Processors

---

src/reference/asciidoc/kafka.adoc

1. fix deprecated method
2. fix wrong type

Fix documentation

---

spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/MicrometerHolder.java
spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/MicrometerHolderTests.java

fixed NPE issue in MicrometerHolder during app shutdown (https://github.com/spring-projects/spring-kafka/issues/1531)

GH-1531: fixed NPE in MicrometerHolder during app shutdown

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ABSwitchClusterTests.java
src/reference/asciidoc/testing.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1538

GH-1538: Embedded broker get results for addTopics

---

src/reference/asciidoc/testing.adoc

Add a missing comma between two arguments

Make the example compile

---

.travis.yml
build.gradle
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractConsumerSeekAware.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConsumerSeekAwareTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

- add convenience methods to `AbstractConsumerSeekAware`
- compile tests with Java 11

Seek Improvements

---

src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/tips.adoc

Clarify synchronization of producer-initiated transactions.

Transactions Doc Polishing

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1587
We should not advance the consumer partition if Seek operations have been
performed; skip fixing the offsets if that condition is detected.
Capture the positions after the poll and check during the fix operation.
This is difficult to write a unit test for; tested with a Boot application,
observing the correct behavior via DEBUG logs.

GH-1587: Don't Correct TX Offsets After Seek(s)

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1597

GH-1597: Fix NPE

---

spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java

Add a setter to be able to change `CleanupConfig` after instanciation via `StreamsBuilderFactoryBeanCustomizer`

Add setter for CleanupConfig

---

src/reference/asciidoc/kafka.adoc

Add recoverer that can conditionally send a record back to the original topic.

DeadLetterPublishingRecoverer Docs

---

spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1610

GH-1610: Reset Retry State when Exception Changes

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1615

GH-1615: Add maxAge to Producers

---

spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1612

GH-1612: Option: Producer Fenced: Stop Container

---

spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java

#1507 
@pivotal-issuemaster This is an Obvious Fix

JsonDeserializer Type Resolution Improvements - javadoc, minor changes

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/PartitionOffset.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ManualAssignmentInitialSeekTests.java
src/reference/asciidoc/kafka.adoc

- support partition lists and lists of ranges with `@TopicPartition.partitionOffset()`.

Partition list, range with initial offsets

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1641
**I will back-port; the test will need some tweaks**

GH-1641: Reconfigurable Producer Factory

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaProducerException.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPausedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerResumedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppingEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/ContainerStoppedEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/KafkaEvent.java
spring-kafka/src/main/java/org/springframework/kafka/event/NonResponsiveConsumerEvent.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/support/CompositeProducerListener.java
spring-kafka/src/main/java/org/springframework/kafka/support/ProducerListener.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingSerializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DeserializationException.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1584
Resolves https://github.com/spring-projects/spring-kafka/issues/1626

Remove deprecations; add assertion

---

src/reference/asciidoc/kafka.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1673

GH-1673: Improve Docs for Default @KafkaHandler

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

Deprecate existing ARP method ready for the new method in 2.7.
**Merge to 2.6.x only**

Prepare for GH-1480

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveryStrategy.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RetryingBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1480
`BackOff` s with long intervals caused shutdown delays.

GH-1480: "Interruptible" BackOff for shutting down

---

spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RetryListener.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1638

GH-1638: Add RetryListener

---

src/reference/asciidoc/quick-tour.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1690
**cherry-pick to 2.6.x (fix kafka-clients version to 2.6.1)**

GH-1690: Polish Quick Start Docs

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/BatchInterceptor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CompositeBatchInterceptor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
src/reference/asciidoc/kafka.adoc
src/reference/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1681
Also add `BatchInterceptor`.

GH-1681: Add "after" methods to RecordInterceptor

---

samples/sample-01/pom.xml
samples/sample-01/src/main/java/com/example/Application.java
samples/sample-01/src/test/java/com/example/ApplicationTests.java
samples/sample-02/pom.xml
samples/sample-02/src/main/java/com/example/Application.java
samples/sample-02/src/main/java/com/example/MultiMethods.java
samples/sample-02/src/test/java/com/example/ApplicationTests.java
samples/sample-03/pom.xml
samples/sample-03/src/test/java/com/example/ApplicationTests.java

- don't run `ApplicationRunner.System.in.read()` from tests.

Upgrade Boot Version in Samples; Fix Tests

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka-docs/src/main/asciidoc/tips.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/transaction/ChainedKafkaTransactionManager.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1699

GH-1699: Deprecate ChainedKafkaTransactionManager

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareRecordRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1700

GH-1700: Check Partition in DLPublishingRecoverer

---

spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaConsumerBackoffManagerTest.java
spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/KafkaBackoffAwareMessageListenerAdapterTest.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/BackOffValuesGeneratorTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DestinationTopicContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactoryTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryResolverTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicBootstrapperTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilderTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConstantsTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicHeadersTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicInternalBeanNamesTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicAnnotationProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/KafkaStreamBrancherTests.java

Migrated all test classes from JUnit5 asserts to use AssertJ library.
Fixes #1721

Migrate test classes to AssertJ

---

spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryTopicConfigurationProvider.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/FixedDelayStrategy.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicAnnotationProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicIntegrationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1714
Add support for property placeholders and SpEL expressions for annotation
properties, where appropriate.
cc/ @tomazfernandes

GH-1714: @RetryableTopic Support SpEL and PPH

---

spring-kafka-docs/src/main/asciidoc/streams.adoc
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaStreamsDefaultConfiguration.java
spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanConfigurer.java
spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanCustomizer.java
spring-kafka/src/test/java/org/springframework/kafka/streams/Configurer1Tests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/Configurer2Tests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1736
**cherry-pick to 2.6.x**

GH-1736: Depr. StreamsBuilderFactoryBeanCustomizer

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1749
We cannot timeout before the `KafkaProducer`; otherwise we could be reporting
a timeout on a send that actually succeeds.
Ensure that the send timeout is at least a few seconds longer than the producer
timeout.

GH-1749: Fix DLPR Send Timeout

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka-docs/src/main/asciidoc/quick-tour.adoc
spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka-docs/src/main/asciidoc/streams.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/1753

GH-1753: Fix Project Name in Docs

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/support/converter/MessagingMessageConverterTests.java

See https://github.com/spring-projects/spring-kafka/issues/1789

GH-1789: Content Type Conversion (Outbound)

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1811

GH-1811: MessageConverter Nullable - Kotlin Compat.

---

spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateTransactionIntegrationTests.java

Wait for send offsets to complete.
Testing GitHub Action.

Fix Flaky Reactor Template Test

---

spring-kafka-docs/src/main/asciidoc/index.adoc

Make a link from the HTML to the PDF and vice-versa.

Link document formats

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaNullAwarePayloadArgumentResolver.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1800
Move the code to a top-level class and document its use.

GH-1800: Add KafkaNullAwarePayloadArgumentResolver

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/RetryingBatchErrorHandler.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RetryingBatchErrorHandlerIntegrationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1855
**cherry-pick to all 2.x.x (down to and including 2.3.x)**

GH-1855: Fix Call to RetryingBatchErrorHandler

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/BatchLoggingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/LoggingErrorHandler.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

GH-615: Add CommonLoggingErrorHandler

---

spring-kafka/src/main/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CommonMixedErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler1Tests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler2Tests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler3Tests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/CommonMixedErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerBatchModeTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerRecordModeTests.java

- CommonContainerStoppingErrorHandler
- CommonMixedErrorHandler

GH-615: More CommonErrorHandlers

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1894
When there was only a key deserialization exception, the exception info was added
twice, under the key keys and value keys.

GH-1894: DLPR: Fix Headers with Only Key Exception

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1872

GH-1872: @KafkaListener Override Listener Type

---

spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java

Change comment in ProductFactory

change-comment

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java

GH-1929: interceptBeforeTx True By Default

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

When pending acks are released due to a gap being "filled", wake the consumer
if it is currently paused.

GH-1189: asyncAcks Improvement

---

spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicInternalBeanNames.java

Fixes #1917
Make bean names public
Add javadoc

GH-1917 - Make RetryTopic bean names public

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc

- allows referring to a specific property, for example in an SO answer.

Add Anchors to container properties

---

spring-kafka-docs/src/main/asciidoc/appendix.adoc
spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1957

GH-1957: Align EOSMode with KIP-732

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerialization.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerializer.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerializationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/1964
Select the `Serializer`/`Deserializer` based on the topic name.

GH-1964: Add DelegatingByTopic(De)Serializer

---

spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2003

GH-2003: Fix RetryableTopic Delivery Attempts Hdr

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc

Docs: fix some broken links

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java

Authentcation -> Authentication

Simple log typo fix

---

spring-kafka/src/main/java/org/springframework/kafka/transaction/ChainedKafkaTransactionManager.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2034

Fix for issue ##2034: ClassCastException in ChainedKafkaTransactionManager in combination with Spring Cloud Sleuth Instrumentation

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2041
`NoSuchMethodError` logged.

GH-2041: Fix Embedded Broker Error When Downgrading

---

spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerialization.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/SerializationIntegrationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2038
- Don't add duplicate delegates
- Configure pre-loaded delegates

GH-2038: Fix DelegatingByTopicSerialization Config

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/SerializationIntegrationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2046

GH-2046: Add Property to Always Check for Deser Ex

---

spring-kafka-docs/src/main/asciidoc/testing.adoc
spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2061

GH-2061: EKB Seek to End Option for Embedded Topics

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java

Signature of `TestUtils.boundPort` has changed.

2.8.x kafka-clients 3.1.0 Compatibility

---

build.gradle
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java

Upgrade Kafka Clients to 3.1.0

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2082
Now that the `earlyRecordInterceptor` is always used unless explicitly disabled,
move delivery attempt header processing earlier so that the header is available
in the interceptor.

GH-2082: Fix RecordInterceptor

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTypeSerializer.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2085

GH-2085: DelegatingByTypeSerializer Improvements

---

spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java

add @Nullable to FailedRecordTracker.setBackOffFunction

---

spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RemainingRecordsErrorHandlerTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/RetryingBatchErrorHandlerIntegrationTests.java
spring-kafka/src/test/kotlin/org/springframework/kafka/listener/EnableKafkaKotlinTests.kt

Deprecate Accessors for Legacy Error Handlers

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc

This adds a what's new section with the changes in the other PRs.
Also adds an Integration Test suite that tests all classification / exception routing behaviors.
This relies on all other PRs being merged, won't even compile before that.
Since all the other PRs are related, I chose this strategy in order to avoid conflicts and still keep the PRs small.
PLMK if there's anything else needed.
Thanks!

Add Integration Tests and whats new for RT improvements - [Merge last]

---

spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateTransactionIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerRecordTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2153

GH-2153: Switch to ConsumerRecord Formatter

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/support/TransactionSupport.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxRollbackTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxTests.java
spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java

Suggest review with `?w=1` (several try/finally blocks removed).

GH-2164: Remove More Dead Code

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java

added spacing in exception message.

fixed spacing in dead letter publishing failed message.

---

spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionOffset.java
spring-kafka/src/test/java/org/springframework/kafka/support/TopicPartitionOffsetTests.java

**cherry-pick to all supported**

Fix TopicPartitionOffset Hash Code (NPE)

---

spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2268
2.7.x Only
The DLPR was incorrectly logging the full `ProducerRecord`; later versions
log the original `ConsumerRecord` using `KafkaUtils.format()`.
Backport the logging changes, but use a `ThreadLocal` for the input record
to avoid API changes in a patch release.

GH-2268: Fix DLPR Record Logging

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2274
Provide an option to suppress configuring programmatically provided
`Serializer`s and `Deserializer`s.
Also fix the DKPF, which did not configure serializers provided by the
supplier setter.
**PR is against 2.9.x; cherry-pick to 2.8.x and main**

GH-2274: Option to Not Configure (De)serializers

---

spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/MicrometerHolder.java
spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/MicrometerHolderTests.java

GH-2148: Use ObjectProvider to Locate MeterRegistry

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc

**2.9.x only** I will update appendix on main after merge.

Update What's new For RC1

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerPartitionPausingBackOffManagerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupport.java

Related to https://github.com/spring-projects/spring-kafka/issues/2239
**Cherry-pick to `2.9.x`**

Fix JavaDocs errors

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2372

GH-2372: Commit Offsets for Skipped Records

---

build.gradle

and remove spring-doc-resources, to pick up the new look and feel
and features.

Use spring-asciidoctor-backends

---

spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingDeserializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingSerializer.java

Refactor - use method referencing in lambdas where possible

---

spring-kafka-docs/src/main/asciidoc/kafka.adoc

Update type to match example template/producer

Update config example type

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/PartitionResolverTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2438

GH-2438: RetryTopic Destination Partition Select

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2352

GH-2352: Expose KLERegistrar Getter on BPP

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc

Resolves https://github.com/spring-projects/spring-kafka/issues/2448

GH-2448: State Non-Blocking Retries API Status

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka-docs/src/main/asciidoc/whats-new.adoc
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolver.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicContainer.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicResolver.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicProcessorTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolverTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2282

GH-2282: Fix Multi RetryableTopic Same Topic

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc

GH-2511: Fix code examples in the documentation for for Non-Blocking Retries - BackOff Configuration

---

spring-kafka/src/main/java/org/springframework/kafka/KafkaException.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/FilteringMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/KafkaBackoffAwareMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/security/jaas/KafkaJaasLoginModuleInitializer.java
spring-kafka/src/main/java/org/springframework/kafka/support/LogIfLevelEnabled.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2535
Change to expressions.

GH-2535: Refactor Switch Statements

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java

Additional parameter on `TestUtils.createBrokerConfig()`.
Retain compatibility with 3.3.1 and earlier.

kafka-clients 3.3.2 Compatibility

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2549

GH-2549: Add Option to Trim Retry Headers

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2626

GH-2626: Support External Admin for Cluster Id

---

build.gradle

Upgrade Micrometer, Reactor, Spring Versions

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java

Typo in error message in KafkaAdmin

Typo in error message in KafkaAdmin

---

spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaConsumerTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java
spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateTransactionIntegrationTests.java

GH-2190: add ctors to reactive producer and consumer

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerFactory.java
spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithNestedClassContextTests.java
spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithSpringTestContextTests.java

GH-2692: to be compatible with @Nested annotation

---

spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
spring-kafka/src/test/java/org/springframework/kafka/support/converter/MessagingMessageConverterTests.java

Allow the user to specify a custom partition selection function.

MMConverter Support Custom Partition Selection

---

spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaRecordReceiverContext.java
spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaRecordSenderContext.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2736

GH-2736: Fix Possible Observation NPEs

---

spring-kafka/src/main/java/org/springframework/kafka/retrytopic/BackOffValuesGenerator.java

Fix typo in BackOffValuesGenerator

Fix typo in BackOffValuesGenerator

---

spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
spring-kafka/src/main/java/org/springframework/kafka/support/KafkaMessageHeaderAccessor.java
spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeliveryHeaderTests.java

Provide simpler access to delivery attempt headers.

Add KafkaMessageHeaderAccessor

---

spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java

See `Configuration.getConfiguration()` which can use reflection to create an instance of this class.

Add ConfigFile Runtime Hint (for JAAS)

---

build.gradle
spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
spring-kafka/src/test/java/org/springframework/kafka/support/serializer/ToStringSerializationTests.java

- remove reflection
- add server-common jars

Prepare for 3.6.0 Client

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2859

GH-2859: Option to Manually Set the Cluster ID

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/validation.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java

Resolves https://github.com/spring-projects/spring-kafka/issues/2861

GH-2861: Add Validator to ErrorHandlingDeserializer

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/events.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/annotation-send-to.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/filtering.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-annotation.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-group-id.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listeners.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/rebalance-listeners.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/sequencing.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/template-receive.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/seek.adoc
spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/dynamic/Application.java

again some cosmetic improvements.
feel free to correct my mistakes.

some cosmetic improvements of the reference - part 2

---

README.md

the reference gradle task is outdated. synced up with the latest status.

update reference documentation gradle task in README.md

---

spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java

ProducerInterceptor in KafkaTempalte unvaild

---

spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/ContainerTestUtils.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerPartitionNoLongerIdleEvent.java
spring-kafka/src/main/java/org/springframework/kafka/listener/BatchAcknowledgingConsumerAwareMessageListener.java
spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
spring-kafka/src/main/java/org/springframework/kafka/mock/MockConsumerFactory.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicHeaders.java
spring-kafka/src/main/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandler.java
spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessageConverter.java
spring-kafka/src/main/java/org/springframework/kafka/support/serializer/RetryingDeserializer.java

fix some obvious typos in various javadocs, code comments or log statements

fix some typos

---

spring-kafka/src/main/java/org/springframework/kafka/core/RoutingKafkaTemplate.java
spring-kafka/src/test/java/org/springframework/kafka/core/RoutingKafkaTemplateTests.java

The following code has bug:
```
public RoutingKafkaTemplate(Map<Pattern, ProducerFactory<Object, Object>> factories) {
... ...
Optional<Boolean> transactional = factories.values().stream()
.map(fact -> fact.transactionCapable())
.findFirst();
Assert.isTrue(!transactional.isPresent() || !transactional.get(), "Transactional factories are not supported");
}
```
Suppose the factories havetwo elements, the first is not `transactionCapable` whereas the second is. then the above stream usage only covers the first factory due to the `map()` usage (`filter()` was the intention).
Created a unit testing case to prove the bug and cover our asses.

fix a bug in RoutingKafkaTemplate

---

build.gradle

- assertJ
- Hibernate validation
- Log4j
- Micrometer
- Micrometer Tracing
- Reactor
- Spring Data
- Spring Framework

Upgrade Dependency Versions

---

samples/sample-01/pom.xml
samples/sample-02/pom.xml
samples/sample-03/pom.xml
samples/sample-04/pom.xml
samples/sample-05/pom.xml

Update Spring Boot Version of the samples

---

spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTypeSerializer.java

Use method args delegates uniformly instead of this.delegates

Polish DelegatingByTypeSerializer

---

spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
spring-kafka/src/test/java/org/springframework/kafka/listener/FailedBatchProcessorTests.java

GH-3019: seek even in case of commit failure

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc

fixed a small typo in docs in 'JsonDe**S**erializer.TYPE_MAPPINGS'
Thanks for the docs!

fix typo in JsonDeSerializer.TYPE_MAPPINGS

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java

Fixes: #3225
* Clarify the usage of `@DirtiesContext` with `@EmbeddedKafka` when using `@SpringJunitConfig`.

GH-3225: Testing docs improvements

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsInteractiveQueryServiceTests.java
spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java

Fixes: #3238
Switch `EmbeddedKafaka#kraft` default to `false`.

GH-3238: Switch `EmbeddedKafaka#kraft` default`

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-annotation.adoc
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java

GH-3400: Clarify manual ack semantics

---

spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
spring-kafka/src/test/java/org/springframework/kafka/listener/AbstractConsumerSeekAwareTests.java

Fixes: #3373
(I will update this PR description later.)

GH-3373: Enhancing handling of seeking failures due to consumer rebalancing

---

spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java

Fixes: https://github.com/spring-projects/spring-kafka/issues/3526

GH-3526: Configure deserializers against modified configs

---

spring-kafka-docs/src/main/kotlin/org/springframework/kafka/kdocs/dynamic/Application.kt

Fixes: #3513
https://github.com/spring-projects/spring-kafka/issues/3513

GH-3513: Cleaning up Kotlin example in ref docs

---

antora-playbook.yml
build.gradle

This PR related https://github.com/spring-projects/spring-amqp/pull/2977 for generating document

Update version antora for branch docs-build

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc

Reference
https://docs.spring.io/spring-kafka/reference/4.0-SNAPSHOT/kafka/sending-messages.html#examples

Fix block code in section Examples

---

spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java

Fix MessagingMessageListenerAdapter Error swallowing

---

spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java

- Fixes : #3712 
In [Retrying Complete Batches](https://docs.spring.io/spring-kafka/reference/kafka/annotation-error-handling.html#retrying-batch-eh) doc, document said that 
```
There is no guarantee that, when a batch is redelivered, the batch has the same number of records and/or the redelivered records are in the same order. 
It is impossible, therefore, to easily maintain retry state for a batch.
```
So, we cannot use `ContainerPausingBackOffHandler` in batch mode. 
The important things in #3712 is that `Consumer` don't call `poll(...)` during backoff sleep. 
It causes the consumer group rebalancing. 
If consumer calls the `poll(...)` during backoff sleep, 
The `FallbackBatchErrorHandler` can handle even `Exponential BackOff`. 
I think that adding `consumer.poll(Duration.ZERO)` …

GH-3712: Make ContainerPausingBackOffHandler working in batch mode.

---

build.gradle
spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/MicrometerHolder.java

Update dependencies and add null safety assertions

---

spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/filtering.adoc

Remove unnecessary semicolon
