spring-projects/spring-kafka

- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- src/reference/asciidoc/testing.adoc
> GH-48: More Test Utilities

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes: https://github.com/spring-projects/spring-kafka/issues/185
If a listener is an `AcknowledgingMessageListener`, do not provide an ack if
the container is not configured for manual acks.
> GH-185: Dont Populate Ack for Non-Manual Ack Modes - 1.0.x BackPort

- src/reference/asciidoc/quick-tour.adoc
Fixes GH-213 (https://github.com/spring-projects/spring-kafka/issues/213)
After introduction copying of `ContainerProperties` instance in the `AbstractMessageListenerContainer` the sample in the Reference Manual ins't valid any more.
* Move `containerProps.setMessageListener()` before `createContainer()` where copying is happened already and we can't affect container with original `ContainerProperties` modifications afterwards.
**Cherry pick to 1.0.x**
> GH-213: Fix sample inconsistency in "quick tour"

- src/reference/asciidoc/quick-tour.adoc
Fixes GH-215 (https://github.com/spring-projects/spring-kafka/issues/215)
**Cherry-pick to 1.0.x**
> GH-215: Fix `quick-tour.adoc` sample obsolete code

- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/si-kafka.adoc
Fixes: GH-217 (https://github.com/spring-projects/spring-kafka/issues/217)
Now we have to provide `ContainerProperties` object instead of direct `topics` for the `KafkaMessageListenerContainer`
Fix race condition in the `KafkaMessageListenerContainerTests` where a `commitSync()` can be performed before spying a consumer.
Since `consumer` is available only after `container.start()` and several barriers to ensure that `consumer` is created but isn't executed yet to let the `spy` be ready for the subsequent `commitSync()` during `run()`
> GH-217: Fix obsolete docs and race condition

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes GH-221 (https://github.com/spring-projects/spring-kafka/issues/221)
When the value is `String[]` we iterate it for the `if (resolvedValue instanceof String[]) {` and then just go to a new `if` block instead of `else if` or `return`
* Fix `KafkaListenerBPP.resolveAsString()` as an `else if` for the second condition
* Confirm the fix with the  `EnableKafkaIntegrationTests` test modification to resolve `topics` to the `String[]`
> GH-221: Fix KafkaListenerBPP.resolveAsString()

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
> GH-209: Avoid allocations from Method.getParameterTypes() in MessagingMessageListenerAdapter

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes GH-230  (https://github.com/spring-projects/spring-kafka/issues/230)
The offsets never got commited by when we don't use MANUAL mode and rely on the `(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false)`
* Move `this.acks.put(record)` outside of the `else` branch for the regular listener.
This way the acks will be placed for the commits even if we use `batchListener` and don't use `isAnyManualAck` mode-
**Cherry-pick to 1.1.x**
> GH-230: Commit batch acks properly

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/ContainerTestUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Prevent the consumer thread from interacting with the mock before the stubbing is complete.
__cherry-pick to master, 1.1.x__
> Fix Stubbing in Tests

- src/reference/asciidoc/kafka.adoc
The recent clarification of the default thread names incorrectly stated the
threads always end `-1` - the default executor is put into the container properties
while starting so subsequent starts will find an existing executor.
__cherry-pick to 1.2.x, 1.1.x__
> Fix Executor Documentation

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AbstractRetryingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RetryingAcknowledgingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RetryingMessageListenerAdapter.java
Actually <? extends Object> for backwards compatibility.
__cherry-pick to 1.2.x, 1.1.x__
> Change RecoveryCallback from <Void> to <Object>

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes: https://github.com/spring-projects/spring-kafka/issues/288
The `DefaultKafkaConsumerFactory` incorrectly returns `false` if no `enable.auto.commit`
property is present. This causes the container to issue commits, which causes strange
offset behavior. Unread partitions are set to the end so messages can be lost.
Work-around is to explicitly add the property.
See: http://stackoverflow.com/questions/43405009/kafka-stop-consuming-message-from-new-assigned-patitions-after-rebalancing/43413899#43413899
__cherry-pick to 1.2.x, 1.1.x, 1.0.x__
> GH-288: Fix autoCommit Default Return Value

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RetryingMessageListenerAdapter.java
It looks `? extends ` part missed in 6d2e7341265bd3ce0dd7d3b5aa1ff1fc875e78a8 .
> Change to RecoveryCallback<? extends Object>

- spring-kafka/src/main/java/org/springframework/kafka/security/jaas/KafkaJaasLoginModuleInitializer.java
- spring-kafka/src/test/java/org/springframework/kafka/security/jaas/KafkaJaasLoginModuleInitializerTests.java
See: https://github.com/spring-projects/spring-kafka/issues/201
Use an enum for the values for content assist in IDEs when we add boot autoconfiguration.
Remove getters (no longer needed now that we have a single class).
> GH-201: Polishing - enum for ControlFlag Values

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
See: https://github.com/spring-projects/spring-kafka/issues/313
In 2.0 we introduce the ability to set the Kafka group.id property on
the annotation; rename the `group` attribute to `containerGroup` to
avoid confusion - deprecate `group` and remove in 2.0.
> GH-313: Prepare: Rename @KafkaListener.group

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RetryingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/FilteringAdapterTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapterTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/RetryingMessageListenerAdapterTests.java
- src/reference/asciidoc/kafka.adoc
Fixes GH-319
Add the `Acknowledgment` and/or `Consumer` to the retry context if the listener
type warrants it.
> GH-319: Add Ack and Consumer to Retry Context

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AbstractRetryingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RetryingAcknowledgingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RetryingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapterTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/RetryingMessageListenerAdapterTests.java
- src/reference/asciidoc/kafka.adoc
Fixes #319
Add the `Acknowledgment` to the retry context if the listener type warrants it.
__cherry-pick to 1.1.x, 1.0.x__
> GH-319: Add Acknowledgment to Retry Context [1.x]

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes #323
The check for `ConsumerSeekAware` was only performed on the record listener.
__cherry-pick to all 1.x__
If it doesn't pick cleanly, I'll create a new PR for 1.2.x.
> GH-323: Fix ConsumerSeekAware and BatchListener

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
Adding the group broke the client.id logic when no client.id configured.
`EnableKafkaIntegrationTests`...
13:51:01.196 WARN  [main][org.apache.kafka.common.utils.AppInfoParser] Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=null-0
> Fix Broken null-check for client.id

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes #325
The check validating parameters with a Batch listener and `List<ConsumerRecord<?, ?>>`
or `List<Message<?>>` did not account for the new optional `Consumer<?, ?>` parameter.
This prevented batch `@KafkaListener`s from being consumer-aware.
__cherry-pick to all 1.x__
Note: the `Assert.state` lambdas need to be removed when cherry-picking.
> GH-325: Consumer with Batch and @KafkaListener

- src/reference/asciidoc/kafka.adoc
KafkaHeaders.RECEIVED_MESSAGE_KEY was written twice in the list of header names that can be used for retrieving the headers of a message.
> Typo : Remove duplicate KafkaHeaders

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- src/reference/asciidoc/kafka.adoc
Fixes #335
Failed to check `batchListener` field when casting listener to apply filter.
> GH-335: Fix Class Cast with Batch Filter

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes #335
Failed to check `batchListener` field when casting listener to apply filter.
Conflicts:
spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolved.
__cherry-pick to all 1.x__
> GH-335: Fix Class Cast with Batch Filter [1.x.x]

- spring-kafka/src/main/java/org/springframework/kafka/core/KStreamBuilderFactoryBean.java
- src/reference/asciidoc/streams.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/365
Fixes https://github.com/spring-projects/spring-kafka/issues/317
* Add `closeTimeout` option to the `KStreamBuilderFactoryBean` to avoid
infinite wait on the internal `KafkaStreams` during `stop()` phase
* Document with samples how to get access to the `KafkaStreams`
instance via `KStreamBuilderFactoryBean` injection
> GH-365: Document KafkaStreams access & close time

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
This parameter is useful when the test expects messages to be there but they
are not because the tested code is not correct. In this case the test will
run for a minute waiting for a message before it fails. With a custom timeout,
a test can specify a shorter timeout to fail faster.
Closes GH-380.
> GH-380: Add timeout parameter to record-getting test utils

- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/378
Don't use a generated container id as the group id if no `id` property provided.
Also fixes `sendToTransaction()` by always populating `consumerGroupId` regardless of source.
__cherry-pick to 1.3.x__
> GH-378: @KafkaListener: Fix Group Id When No id

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaListenerErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/342
Allow no reply template when an error handler returns a result; the result is ignored.
Also add a note (and test) about a `void` method that has a `@SendTo` - which allows information
about the exception in a `void` method to be sent to a topic.
> GH-342: Allow KLErrorHandler to Return a Result

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- src/reference/asciidoc/kafka.adoc
Needed to support headers.
Adding overloaded send methods is getting out of hand, consider deprecating the parameterized sends.
__cherry-pick to 1.3.x__
> GH-352: Add General send() with ProducerRecord

- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/395
SCSt needs a reference to the sent message in order to generate an error message on a send failure.
> GH-395: Document Async Template Usage

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
The `StandardBeanExpressionResolver` is based on the
`TemplateAwareExpressionParser` which can parse any string to the
`LiteralExpression` or to the `CompositeStringExpression` if
template tokens (`#{` & `}`) are present in the source expression.
This way we don't need to deal with literal concatenations within
templated expression.
The expression like `#{'foo.' + myBean.bar}` can be replaced
with the `foo.#{myBean.bar}`
See: https://github.com/spring-projects/spring-amqp/issues/672
> Allow templating SpEL in @KafkaListener

- spring-kafka/src/main/java/org/springframework/kafka/event/NonResponsiveConsumerEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/config/ContainerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/466
Users might consider `stop()`ing the container under this condition,
which will wake the consumer.
__cherry-pick to 1.3.x__
> GH-466: Add NonResponsiveConsumerEvent

- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- src/reference/asciidoc/quick-tour.adoc
- src/reference/asciidoc/testing.adoc
Resolves: https://github.com/spring-projects/spring-kafka/issues/471
Support overriding kafka versions to 1.0.0.
(Minor API changes in the `TestUtils`)`
> GH-471: KafkaEmbedded compatibility with 1.0.0

- spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerIdleEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/NonResponsiveConsumerEvent.java
java.lang.NullPointerException: null
at java.util.ArrayList.<init>(ArrayList.java:177) ~[na:1.8.0_131]
at org.springframework.kafka.event.NonResponsiveConsumerEvent.<init>(NonResponsiveConsumerEvent.java:51) ~[spring-kafka-1.3.1.BUILD-SNAPSHOT.jar:na]
__cherry-pick to 2.0.x, 1.3.x__
> Fix NPE in events when no assigned topics

- spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerIdleEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/NonResponsiveConsumerEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RemainingRecordsErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
- src/reference/asciidoc/kafka.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/470
2.0 introduced the `ConsumerAwareErrorHandler`, which allows the user to
`seek()` the consumer after an exception.
However, any pending records from the previous poll are still sent to
the listener.
Add the `RemainingRecordsErrorHandler` interface and `SeekToCurrentErrorHandler`
implementation which resets the offsets of all unprocessed topic/partitions so
that the next poll will return the failed record and all of the previously
unprocessed records.
__cherry-pick to 2.0.x__
> GH-470: Add SeekToCurrentErrorHandler

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/485
When looking for matching methods, we matched on no annotation or `@Payload`.
Match should have been no annotation(s) or not `@Header`.
__cherry-pick to 2.0.x, 1.3.x__
> GH-485: Fix multi listener method @KafkaListener

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- src/reference/asciidoc/kafka.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/475
Previously, containers were started in phase 0; thy should be
started in a late phase.
__cherry-pick to 2.0.x, 1.3.x__
> GH-475 Fix Listener Container SmartLifecycle phase

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/501
With `AckMode.RECORD`, the container was committing the offsets on the
consumer instead of sending them to the transaction.
> GH-501: Fix transactions with AckMode.RECORD

- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Create the mock consumer before it has any interactions.
__cherry-pick to master, 1.3.x__
> Fix Mocking in EnableKafkaIntegrationTests

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
When using the `KafkaTemplate.send(Message<?>)` variant, an NPE was thrown
if Jackson wasn't on the classpath.
__cherry-pick to 1.3.x, 2.0.x__
> Fix NPE when Jackson not present

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminBadContextTests.java
Locally, I find the admin is sometimes created even with a bad host causing the test to fail.
Also, topic creation logged an error but did not throw an exception.
Fixed the test to expect one of two exceptions.
__cherry-pick to 2.0.x__
> Fix KafkaAdminBadContextTests

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
This PR introduces an intermediate variable for `topicNameToTopic.get(n)` in `KafkaAdmin.addTopicsIfNeeded()` for readability and performance although it's trivial.
> Introduce an intermediate variable for topicNameToTopic.get(n)

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Fixes https://github.com/spring-projects/spring-kafka/issues/522
> GH-522: Fix NPE in listener container

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
When `isKey` is `true`, `addTargetPackageToTrusted()` is not applied. So this PR applies `addTargetPackageToTrusted()` consistently.
> Apply addTargetPackageToTrusted() consistently in JsonDeserializer

- src/reference/asciidoc/testing.adoc
In https://docs.spring.io/spring-kafka/docs/current/reference/htmlsingle/#__embeddedkafka_annotation
KafkaEmbedded bean's field-name is 'kafkaEmbedded'. But, a few lines below are called 'embeddedKafka'
```
this.embeddedKafka.consumeFromAnEmbeddedTopic(consumer, KafkaStreamsTests.STREAMING_TOPIC2);
```
> fix Doc's description

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
- src/reference/asciidoc/kafka.adoc
In the `@KafkaListener` bean post processor, allow property SpEL expressions to
access properties and methods on the bean being post-processed.
[See Stack Overflow](https://stackoverflow.com/questions/48162588/spring-expression-language-is-it-possible-to-use-this-in-sel/48171277#48171277).
> Support local bean reference in @KafkaListener

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Previously, `setReplyTopic` detected runtime SpEL by checking if
the expression starts with `!{`. Since we use a `TemplateParserContext`
the topic can be evaluated even if the `!{` is not at the beginning.
This is not a breaking change since `!` and `{` are not valid topic characters.
> Fix @SendTo Runtime SpEL Detection

- spring-kafka/src/main/java/org/springframework/kafka/support/AbstractKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SimpleKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
- don't map message channel headers, unless they are String
- tolerate `byte[]` in topic header.
> More Spring Integration Kafka Support

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/si-kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/568
Also fix some PDF overflows.
> GH-568: S-I-K Gateways Documentation

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- Add trace log for successfull send
- Add debug log for failed send (debug because the user code should react to the future)
- Add trace logging for records received (topic-partition@offset) (container)
- Add debug logging for records received (topic-partition@offset) (test utils)
> More tracing and debug logging

- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/rule/AddressableEmbeddedBrokerTests.java
If the initial `poll()` used to force the subscription returns
any records, seek those partitions to beginning instead of
discarding.
> Embedded Kafka SeekToBeginning if needed

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/MultiMethodKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/HandlerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/563
Invoke a default handler if no match on payload.
Basically a copy of similar code in Spring AMQP.
> GH-563: Add default @KafkaHandler

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/AbstractJavaTypeMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerde.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsJsonSerializationTests.java
GH-561 Add a test to json serialize both a key and value in a stream.
GH-561 - Configure Jackson2JavaKeyTypeMapper in JsonDeserializer and JsonSerializer when the isKey flag is present.
GH-561 - Add collection json serialization tests.
GH-561 - Use isKey to set json headers.
> #561 -  Cannot use JsonSerde for both key and value serialization in a stream

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
This PR adds a missing `InterruptedException` handling.
> Add a missing InterruptedException handling

- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
The default broker configuration requires 3 broker instances for transactions.
Instead of running 3 embedded brokers, change the configuration to allow
transactions with just one.
Use broker config constants.
Add a builder method for individual properties.
> Transaction Tests Polishing

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
because DEFAULT_KEY_TYPE is "spring.json.key.default.type",  but DEFAULT_VALUE_TYPE is "spring.json.default.value.type", seems like wrong word order, we should keep them the same.
from
```
public static final String DEFAULT_KEY_TYPE = "spring.json.key.default.type";
public static final String DEFAULT_VALUE_TYPE = "spring.json.default.value.type";
```
to 
```
public static final String DEFAULT_KEY_TYPE = "spring.json.key.default.type";
public static final String DEFAULT_VALUE_TYPE = "spring.json.value.default.type";
```
> rename constant DEFAULT_VALUE_TYPE to keep the same with DEFAULT_KEY_TYPE

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPausedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerResumedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerIdleEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/609
- Provide visibility to the container pause state
- Add pause/resume events
> GH-609: Pause/resume polishing; events

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareRebalanceListener.java
Resolves https://github.com/spring-projects/spring-kafka/issues/597
Add default no-op methods as a convenience so only those that are needed
have to be implemented.
> GH-597: Add default impls for listener methods

- spring-kafka/src/main/java/org/springframework/kafka/listener/BatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerAwareBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerAwareErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RemainingRecordsErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/614
PR #595 added support for calling error handlers for general errors not related
to listener invocation.
However, the wrong `handle()` method was called.
Add a default implementation of the lowest interface method in the hierarchies to
`ErrorHandler` and `BatchErrorHandler` respectively and invoke that so the
right method will always be invoked, regardless of the error handler type.
Also see #615
> GH-614: Fix general consumer error handling

- spring-kafka/src/main/java/org/springframework/kafka/core/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/core/StreamsBuilderFactoryLateConfigTests.java
@garyrussell mentioned returning an `UnmodifiableMap` for the `StreamsConfig` in #618 , but after looking through the `StreamsConfig` code it doesn't look like it's mutable anyways (unless I'm missing something), as it makes a copy of the original configs when querying a `StreamsConfig` instance. With that said, let me know if you would still prefer an `UnmodifiableMap`, I'm happy to change it. As it stands right now, `StreamsConfig` has the benefit of knowing which keys are valid, the expected types of each value which helps for validation when retrieving configs. 
I also marked the return value as `Nullable`, as the `StreamsBuilderFactoryBean` allows configuration after instantiation. I also considering wrapping this in an `Optional`, but I didn't see any usage of `Optionals` in this …
> GH-618: Add StreamsBuilderFactoryBean#getStreamsConfig

- gradle.properties
- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- src/reference/asciidoc/appendix.adoc
- src/reference/asciidoc/testing.adoc
- src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/634
Tested with
```xml
<dependencies>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter</artifactId>
</dependency>
<dependency>
<groupId>org.springframework.kafka</groupId>
<artifactId>spring-kafka</artifactId>
<version>2.1.5.BUILD-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>org.springframework.kafka</groupId>
<artifactId>spring-kafka-test</artifactId>
<version>2.1.5.BUILD-SNAPSHOT</version>
<scope>test</scope>
<exclusions>
<exclusion>
<groupId>org.apache.kafka</groupId>
<artifactId>kafka-clients</artifactId>
</exclusion>
</exclusions>
</dependency>
<dependency>
<groupId>org.apache.kafka</groupId>
<artifactId>kafka-clients</artifactId>
<version>1.1.0</version>
</dependency> …
```
> GH-634: 1.1.0 Client compatibility

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminBadContextTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/646
- add protection to the transactional producer cache to avoid multiple cache inserts
- add try/catch around `abortTransaction()`
- detect (and reject) an illegal call to `template.send()` when there is no existing transaction
- from the send callback remove the `ThreadLocal` check (will always be null) and only close the producer if it's not transactional
- remove autoFlush from template tests
**cherry-pick to 2.1.x_, 2.0.x, 1.3.x**
> GH-646: Transaction Improvements

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
Unfortunately, I had this local change that I failed to push to the PR #647 - it avoids synchronization when there transactions are not being used.
@artembilan I will do the merge/cherry-picking if you like, after your review.
> GH-646: Avoid sync when no transaction

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
See https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/356
Use token 'consumer' for thread prefix when no bean name.
**cherry-pick to 2.0.x, 1.3.x**
> KBGH-356: Fix thread naming with no bean name

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/streams.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/652
Kafka Streams `ChangedSerializer` calls the `Serde` with `null` in `headers`.
**cherry-pick to 2.1.x, 2.0.x, 1.3.x**
> GH-652: JsonSerializer add null check for Headers

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/667
When catching exceptions outside of the listener (e.g. commit errors), the
`BatchErrorHandler` was never called since the record error handler gets a
logging handler.
Check listener type before invoking the error handler for consumer errors.
> GH-667: Fix BatchErrorHandler for generic errors

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/667
When catching exceptions outside of the listener (e.g. commit errors), the
`BatchErrorHandler` was never called since the record error handler gets a
logging handler.
Check listener type before invoking the error handler for consumer errors.
> GH-667: Fix BatchErrorHandler for generic errors [2.1.x]

- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- src/reference/asciidoc/testing.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/666
Allow a single `KafkaEmbedded` to be used across multiple test classes.
> GH-666: Refactor KafkaEmbedded to expose admin and addTopics()

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/ConcurrentKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/ContainerFactoryTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
See https://github.com/spring-projects/spring-integration-kafka/issues/204
With this in place, we could pass a container factory into the KMDCA and/or a DSL spec,
along with topic configuration.
This would enable boot properties to be used to configure the container (and any container
that is not used for a `@KafkaListener`.
With the integration DSL, something like
IntegrationFlows.from(Kafka.messageDrivenChannelAdapter(containerFactory, String... topics)
.handle(...)
...
where the `ConsumerFactory` and `ContainerProperties` are provided by the factory.
> SIKGH-204: Support auto config for all containers

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/683
If the error handler handles the error, the offset should be sent to the tx.
> GH-683: Fix Transactions with ErrorHandler

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/config/ContainerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/683
If the error handler handles the error, the offset should be sent to the tx.
**cherry-pick to 2.0.x, 1.3.x**
> GH-683: Fix Transactions with ErrorHandler [2.1.x]

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/MissingTopicsTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/696
Container start() fails if topics are missing.
> GH-696: Add missingTopicsFatal container property

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
Fixes https://github.com/spring-projects/spring-kafka/issues/690
The concurrent container did not propagate its `AfterRollackProcessor` to
child `KafkaMessageListenerContainer`s.
**cherry-pick to 2.1.x, 2.0.x, 1.3.x**
> GH-690: Propagate AfterRollbackProcessor to child

- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- src/reference/asciidoc/kafka.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/716
Improve documentation - `null` is not necessarily just for tombstone records.
__cherry-pick to 2.1.x__
> GH-716: Null Payload Doc Improvements

- build.gradle
Exclusion of Spring 4.X transitive dependencies from Spring-Retry
#719
> Exclude Spring 4.X dependency

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DeserializationException.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
- src/reference/asciidoc/kafka.adoc
A delegating deserializer that populates the key or value with a
`DeserializationException` containing the raw data when deserialization
fails.
> Add ErrorHandlingDeserializer

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
Resolves https://github.com/spring-projects/spring-kafka/issues/723
The replying template might have different generic types for the Key/Value
than the incoming container.
> GH-723: Relax reply template generic types

- build.gradle
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/KafkaEmbedded.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaStreamsDefaultConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/core/StreamsBuilderFactoryBean.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaStreamsCustomizerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/StreamsBuilderFactoryBeanTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/StreamsBuilderFactoryLateConfigTests.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsBranchTests.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsJsonSerializationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/quick-tour.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/757
Kafka 2.0.0 Compatibility
Tested against local build of the kafka trunk branch.
- `poll(long)` is deprecated.
- `poll(Duration)` does not block until the partitions are assigned.
- Several KStream changes.
- Some tests are still failing sporadically
Increase default poll timeout; ensure unique group.id for all tests.
Test against a build from the 2.0.0-rc1 tag instead of trunk.
Rebase; Polishing; test against official 2.0.0 build
> Upgrade to Kafka 2.0.0

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/762
Add an event when a consumer thread exits.
> GH-762: ConsumerStoppedEvent

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaStreamsDefaultConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/core/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaStreamsCustomizerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/StreamsBuilderFactoryBeanTests.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsBranchTests.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsJsonSerializationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsTests.java
- src/reference/asciidoc/streams.adoc
See https://github.com/spring-projects/spring-boot/pull/14021#discussion_r208929624
Avoid using a bean of type `Properties`.
> Add KafkaStreamsConfiguration

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/786
`DefaultKafkaProducerFactory`
- use `ContextStoppedEvent` instead of `Lifecycle` to close producer(s).
- add `reset` method
- deprecate `Lifecycle` methods
> GH-786: DKPF: ContextStoppedEvent

- spring-kafka/src/main/java/org/springframework/kafka/transaction/ChainedKafkaTransactionManager.java
- spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaAwareTransactionManager.java
- spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Sub-interface of `PlatformTransactionManager` to facilitate Boot auto-configuration.
Deprecate `ResourceTransactionManager` inheritance.
> Refactor KafkaAwareTransactionManager

- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
Don't throw an exception if the record was skipped by invoking the recoverer.
- Adds noise to the log since the record was recovered in some way.
> SeekToCurrentErrorHandler and Recovery

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
It was added in 7beaa606e28ef54d92e0b1831df6c229c560ea96 and looking at the commit, it looks intended to be in 2.2, so this PR changes the `@since` tag to 2.2.
> Fix @since tag for setRemoveTypeHeaders()

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/TransactionSupport.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/800
Fix assignment of `transactional.id` to be consistent across consumers.
**cherry-pick to all versions >= 1.3.x**
> GH-800: Fix Zombie Fencing

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/AliasPropertiesTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/812
Allow user annotations meta-annotated with `@KafkaListener` to set alias properties.
Also fix exception text when no topic/partition info provided.
> GH-812: Support @AliasFor in @KafkaListener meta

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Fixes https://github.com/spring-projects/spring-kafka/issues/813
Kafka resumes the consumer(s) after a rebalance, but since the
`ListenerConsumer.consumerPaused` is still true, the container starts
consuming again and can't be paused without first issuing a resume.
On a rebalance, reset the boolean; the consumer will re-pause  before
the next poll, if the container's `isPaused()` is still true after
the rebalance listeners exit.
Tested with a stand-alone Boot app (see the referenced issue).
> GH-813: Re-pause a paused consumer after rebalance

- build.gradle
- spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafka.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/816
> GH-816: Simplify Validator configuration

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
Expand id documentation to clarify that it will override the group id specified in the configuration by default.
> Update documentation on KafkaListener annotation

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/834
To solve the zombie fencing problem there is a producer for each
group/topic/partition.
Close these producers when a partition is revoked or the container stopped.
**cherry-pick to 2.1.x, 2.0.x**
I will backport to 1.3.x (without lambdas etc) after review/merge.
> GH-834: Remove transactional producers

- .gitignore
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/834
To solve the zombie fencing problem there is a producer for each
group/topic/partition.
Close these producers when a partition is revoked or the container stopped.
> GH-834: Remove transactional producers [backport]

- src/reference/asciidoc/kafka.adoc
Fixes GH-840 (https://github.com/spring-projects/spring-kafka/issues/840)
* remove reference to FilteringAcknowledgingMessageListenerAdapter and delete duplicated paragraph
* remove reference to RetryingAcknowledgingMessageListenerAdapter
> GH-840: Fix typos in documentation of Filtering Messages and Retrying Deliveries

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/InvocationResult.java
This PR polishes `InvocationResult.toString()` by removing an unnecessary ternary operator.
> Polish InvocationResult.toString()

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- Log exceptions on commit/abort transaction
- Don't attempt to abort if commit fails, otherwise we see
`Abort failed`
`org.apache.kafka.common.KafkaException: Cannot execute transactional method because we are in an error state`
> Log TX Exceptions

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DeserializationException.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer2.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversion2Tests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/checkstyle/checkstyle-suppressions.xml
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/853
Since a `null` key is common, we only check for the exception header
if we detect that the error handling deserializer is configured.
> GH-853: Type Safe ErrorHandlingDeserializer

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/859
When using `executeInTransaction` on a transactional container thread,
we cannot use the existing transaction - clear the TL to allow a new
Producer to be allocated.
Invalid state transition (in-trans to in-trans).
**cherry-pick to 2.1.x, 2.0.x, backport needed for 1.3.x**
> GH-859: Fix nested transactions

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/859
When using `executeInTransaction` on a transactional container thread,
we cannot use the existing transaction - clear the TL to allow a new
Producer to be allocated.
Invalid state transition (in-trans to in-trans).
**cherry-pick to 2.1.x, 2.0.x, backport needed for 1.3.x**
> GH-859: Fix nested transactions [1.3.x backport]

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/855
`DeadLetterPublishingRecoverer` should participate in the current transaction,
if present, or start a transaction otherwise (if the template is transactional).
> GH-855: Dead letter publisher and transactions

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
Fixes spring-projects/spring-kafka#842
**Cherry-pick to 2.1.x, 2.0.x and 1.3.x**
> GH-842: Fix NPEs in KafkaListenerAnnotationBPP

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Fixes https://github.com/spring-projects/spring-kafka/issues/881
`getAssignedPartitions()` can return `null`.
__cherry-pick to 2.1.x, 2.0.x, 1.3.x__
> GH-881: Null check in closeProducers()

- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/885
`SeekToCurrentErrorHandler` and `DefaultAfterRollbackProcessor`,
with negative `maxFailures`, now never recovers and continues to retry
indefinitely.
> GH-885: Restore infinite retries STCEH

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPausedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerResumedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppingEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ContainerStoppedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/KafkaEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ListenerContainerIdleEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/NonResponsiveConsumerEvent.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
The fix for https://github.com/spring-projects/spring-kafka/issues/878
introduced a new tangle between `events` and `listener`.
The container publishes events so events can't directly reference the containers.
> GH-878: Polishing - Fix new tangle

- src/reference/asciidoc/kafka.adoc
This PR adds a missing closing pointy bracket for `List<ConsumerRecord<?, ?>>` in doc.
> Add a missing closing pointy bracket in doc

- spring-kafka/src/main/java/org/springframework/kafka/support/JacksonPresent.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
Fixes spring-projects/spring-kafka#894
According Spring Boot Dev Tools recommendations it is much safer to
use a `ClassLoader` for manually loading class with the
`Thread.currentThread().getContextClassLoader()`.
This way those classes are going to be loaded in the `RestartClassLoader`
instead of `Launcher$AppClassLoader` allowing the proper deserializaiton
logic in the application at runtime
* Use a `ClassUtils.getDefaultClassLoader()` in the `JsonSerializer`
instead of `getClass().getClassLoader()` to load classes for mapping
* Also use a `ClassUtils.getDefaultClassLoader()` in the `JacksonPresent`
*No cherry-picking since we know a workaround with the explicit
configuration on the `DefaultKafkaProducerFactory` and
`DefaultConsumerFactory`*
> GH-894: Use context CL in the JsonSerializer

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/900
Use the proper zombie-fencing `transational.id` when committing initial
offsets after assignment.
**cherry-pick to all, 1.3.x will probable need a backport**
> GH-900: Use correct txId for initial commit

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
The `errorHandler` attributed has been missed from the
`KafkaListenerAnnotationBeanPostProcessor.processMultiMethodListeners()`
logic.
* Move `errorHandler` and `BeanFactory` population into the
`processListener()` method in the `KafkaListenerAnnotationBeanPostProcessor`
**Cherry-pick to 2.1.x, 2.0.x & 1.3.x**
> Process errorHandler in class level KafkaListener

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/908
Zombie-fenced producers, running on container threads with topic/partition/group
transactional ids must not be added to he general producer cache for use by other
arbitrary producer operations.
These producers are maintained in their own cached, keyed by the transactional id.
Add tests to verify these producers are not cached and that a producer used within
a nested transaction is added to the cache.
**cherry-pick to 2.1.x, 2.0.x; backport PR will be published for 1.3.x after review/merge**
> GH-908: Don't cache dedicated consumer producers

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/908
Zombie-fenced producers, running on container threads with topic/partition/group
transactional ids must not be added to he general producer cache for use by other
arbitrary producer operations.
These producers are maintained in their own cache, keyed by the transactional id.
Add tests to verify these producers are not cached and that a producer used within
a nested transaction is added to the cache.
**cherry-pick to 2.1.x, 2.0.x; backport PR will be published for 1.3.x after review/merge**
> GH-908: Don't cache dedicated consumer producers [back port]

- src/reference/asciidoc/si-kafka.adoc
Since we added gateways, a dedicated success channel is now provided instead
of using the output channel for result metadata.
> SI Outbound result channel docs

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/915
The configuration options were added after the reader was created.
> GH-915: Fix JSON default object mapper config

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/RemainingRecordsErrorHandlerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/916
The container failed to invoke the proper method for an implementation
of `RemainingRecordsErrorHandler`.
Regression caused by the addition of the `ContainerStoppingErrorHandler`.
There will be conflicts in the container, but the changes are simply to replace
`ContainerAwareErrorHandler` with `RemainingRecordsErrorHandler`.
> GH-916: Fix RemainingRecordsErrorHandler

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/DefaultJackson2JavaTypeMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Only remove the headers for the object being deserialized.
Previously, it removed all type headers, with explicit reference to the key
headers. This happened to work ok because the key was deserialized first.
If this ever changes, the key headers would be removed when the value is
deserialized and would not be available for key deserialization.
> JsonDeserializer Header Removal Polishing

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer2.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/926
Previously, the container only detected the presence of the deserializer
when it was configured using Kafka properties.
The container now detects it (and subclasses) when configured directly
into the consumer factory and properly routes exceptions to the error
handler.
Also add `setKey` to designate the deserializer as a key deserializer.
> GH-926: Always Detect ErrorHandlingDeserializer2

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerde.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
Currently it is impossible to create `JsonSerde` / `JsonDeserializer` for parameterized containers (e. g. HashMap<K,V>) without unchecked typecasting.
E.g. the following problems occur: 
```java
//error: cannot infer arguments
JsonSerde<HashMap<String, String>> s = new JsonSerde<>(Map.class);
```
```java
//warning: unchecked assignment
JsonSerde<HashMap<String, String>> s = new JsonSerde(Map.class);
```
```java
//warning: unchecked type cast 
Consumed.with(Serdes.String(),
(JsonSerde<Map<String,Double>>) new JsonSerde(Map.class)
```
The proposed change (see e.g. Joshua Bloch, "Effective Java", Item 31: 'Use Bounded Wildcards to Increase API Flexibility") moves the typecast (`Class<? super T>` to `Class<T>`) into the library class and makes other code more clear. So now the following …
> Better type handling for JsonSerde / JsonDeserializer constructors

- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- src/reference/asciidoc/testing.adoc
- src/reference/asciidoc/whats-new.adoc
Added ports attribute to EmbeddedKafka annotation.
It has a default value of 0 to be consistent with the count attribute.
> Specify the port with annotation #917

- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes spring-projects/spring-kafka#787
* Allow to configure listener container with strategies based on the
super classes of key and value generics
> GH-787: Fix upper-bounds for generics

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaListenerErrorHandler.java
This PR fixes a very minor typo in the `KafkaListenerErrorHandler` class description to get better code rendering.
> Fix typo in KafkaListenerErrorHandler class description

- spring-kafka/src/main/java/org/springframework/kafka/KafkaException.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerExecutionFailedException.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/948
For example, this can be used by the `DeadLetterPublishingRecoverer`'s
destination resolver to choose a topic based on the group in addition
to the information in the consumer record.
> GH-948: Enhance LEFException with group.id

- spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafkaStreams.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaStreamsDefaultConfiguration.java
- src/reference/asciidoc/testing.adoc
Fix existing code that show declaration of bean DEFAULT_STREAMS_CONFIG_BEAN_NAME
as a `Properties` object or a `StreamsConfig` object instead of `KafkaStreamsConfiguration`.
- `EnableKafkaStreams.java` : update documentation that used a `StreamsConfig` object
- `KafkaStreamsDefaultConfiguration.java` : fix the exception message when missing bean named `KafkaStreamsDefaultConfiguration.DEFAULT_STREAMS_CONFIG_BEAN_NAME`. The exception stated that a `Properties` object is required.
- `testing.adoc` : update an example that used a `StreamsConfig` object to create a bean named `KafkaStreamsDefaultConfiguration.DEFAULT_STREAMS_CONFIG_BEAN_NAME`
Hope it will prevent someone else from having trouble with starting working with `spring-kafka` 😄
> fix outdated references to DEFAULT_STREAMS_CONFIG_BEAN_NAME

- .editorconfig
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/RemainingRecordsErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Add the `properties` attribute to the `@KafkaListener` annotation to
enhance or override the consumer factory properties.
> @KafkaListener Consumer Property Overrides

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
When a container-aware error handler is called from a
`ConcurrentMessageListenerContainer`, when the consumer throws an
exception (rather than the listener), the wrong container was
passed in the container argument. The child container was passed
in instead of the concurrent container.
__cherry-pick to 2.1.x__
> Fix ErrorHandler for Consumer Errors

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/LoggingCommitCallback.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/960
When the container is configured with `AckMode.MANUAL_IMMEDIATE`, the
`SeekToCurrentErrorHandler` can be configured to commit the offset of
a recovered record.
> GH-960: Seek-to-Current - commit recovered offset

- spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerFactory.java
Since the getters are `@Nullable` the default implementation should
return `null` instead of throwing an `UnsupportedOperationException`.
> Fix default deserializer getters

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer2.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/kstream/KafkaStreamsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/889
- also `TimeWindows.of(long)`
> Remove uses of deprec. Extended(Des|S)erializer

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
- src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/950
Provide access to the `group.id` for all listener types, including
simple listeners.
> GH-950: Always wrap listener exception in LEFE

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/970
- allow retrieval of the `group.id`, even if not set on the container properties
- also add `getAllListenerContainers` to the `RLERegistry` as a convenience
- also add `getListenerId` to return the id or bean name of the container
__cherry-pick to 2.2.x__
> GH-970: Add getGroupId() to containers

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
If the consumer properties object contains `default` properties,
they were ignored. `Properties.forEach()` does not return default
properties.
Use `stringPropertyNames()` instead.
> Fix Consumer Property Overrides

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapterTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/974
Replace `KafkaNull` elements with `null` when the payload is resolved to a list.
> GH-974 Batch listeners replace KafkaNull with null

- spring-kafka/src/main/java/org/springframework/kafka/config/TopicBuilder.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Convenient builder for `NewTopic` to avoid the cast to short when
creating `NewTopic`.
Also convenient fluent API for setting topic configuration properties.
> Add TopicBuilder

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/983
Add a `spring-retry` `BinaryExceptionClassifier` to the
`SeekToCurrentErrorHandler` configured with default fatal
exception types.
> GH-983: Add exception classifier to the Seeking EH

- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/987
`DeadLetterPublishingRecoverer` now detects `DeserializationException`s
and sets the value of the republished record to the original incoming
`byte[]`.
- STCEH - fix `defaultClassifier` to traverse exception causes
> GH-987: DeserializationException and dead-letters

- spring-kafka/src/main/java/org/springframework/kafka/listener/AfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/990
Provide a mechanism to start a new transaction within which to invoke
the processor, so if it recovers the failed record, its offset can
be sent to the transaction.
> GH-990: Run AfterRollbackProcessor in Tx

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailrdRecordTrackerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/992
The `SeekToCurrentErrorHandler` and `DefaultAfterRollbackProcessor`
always retried at least one time, even if `maxAttempts` was 1.
> GH-992: Fix SeekToCurrent zero retries

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer2.java
Fixes https://github.com/spring-projects/spring-kafka/issues/995
Doesn't really make a difference because `writeObject()` drains
all data to the underlying output stream and `flush()` and `close()`
are no-ops for `ByteArrayOutputStream`.
But, technically, correct.
> GH-995: Close ObjectOutputStream in EHD2

- publish-maven.gradle
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://spring.io with 1 occurrences migrated to:  
https://spring.io ([https](https://spring.io) result 200).
* http://www.apache.org/licenses/LICENSE-2.0.txt with 1 occurrences migrated to:  
https://www.apache.org/licenses/LICENSE-2.0.txt ([https](https://www.apache.org/licenses/LICENSE-2.0.txt) result 200).
> URL Cleanup

- spring-kafka/src/main/java/org/springframework/kafka/support/AbstractKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SimpleKafkaHeaderMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/SimpleKafkaHeaderMapperTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1012
Add configuration to map string-valued headers as raw `byte[]`
instead of adding to the map of json-mapped headers.
__cherry-pick to 2.2.x__
> GH-1012 Allow raw Strings in default header mapper

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Useful if multiple containers for the same topics in the same
application.
> Add group.id to container info logs

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/JacksonUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/ProjectingMessageConverter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/StringJsonMessageConverter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerde.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/680
* Introduce `JacksonUtils` factory class and use its
`enhancedObjectMapper()` whenever we rely on the default `ObjectMapper`.
* The `JacksonUtils` instantiate `ObjectMapper` with
`MapperFeature.DEFAULT_VIEW_INCLUSION` &
`DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`, and also registers
well-known data type modules found in classpath.
> GH-680: Use enhanced ObjectMapper by default

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/1055
For better generics handling the `TypeReference`-aware ctors are added
to the `JsonDeserializer`
Apply some internal refactoring to the `JsonDeserializer` for code reuse
> GH-1055: Add TypeReference support to JsonDeser

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
With a transactional container if committing the offsets fails
during a rebalance, we would leave the producers open.
Move the close to a finally block.
> Fix close producers after a rebalance

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1059
* Code style polishing in the `KafkaListenerAnnotationBeanPostProcessor`
and `EnableKafkaIntegrationTests`
**Cherry-pick to 2.2.x**
> GH-1059: Add SpEL support for KafkaListener.id()

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1008
* If provided `configs` for the `DefaultKafkaProducerFactory` contains a
`ProducerConfig.TRANSACTIONAL_ID_CONFIG` value, treat it as a `prefix`
and override for the target `Producer` configs.
Also log an `INFO` that this value is going to be prefix the target
`Producer`
* An explicit `setTransactionIdPrefix()` will override this value
any way
* Polishing for `KafkaTemplateTransactionTests` together with an
explicit `ProducerConfig.TRANSACTIONAL_ID_CONFIG` config in the
`testLocalTransaction()` test
> GH-1008: Use `transactional.id` config as a prefix

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessageConverter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
- spring-kafka/src/test/java/org/springframework/kafka/support/converter/BatchMessageConverterTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/converter/MessagingMessageConverterTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1066
Certain clients (e.g. mapR) that emulate the Kafka clients do not properly
populate the `ConsumerRecord.headers()` field.
Check for null before mapping; also check `timestampType`.
**cherry-pick to 2.2.x, 2.1.x**
> GH-1066: Protect against null Headers

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka/src/main/java/org/springframework/kafka/config/ConcurrentKafkaListenerContainerFactory.java
Seems like more performant version, at least in newer JDK versions.
See: https://github.com/spring-projects/spring-boot/pull/12153
> Use empty array in toArray call.

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1074
Use the admin client instead of a `Consumer`.
> GH-1074: Use AdminClient to check topic presence

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Add default method implementations to avoid users having to implement
methods they are not interested in.
> ConsumerSeekAware default implementations

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1102
Add `running` boolean for `isRunning()`.
Previously the registry returned `true` if at least one of its
containers had been previously started manually.
> GH-1102: Fix KLEndpointRegistry SmartLifecycle

- build.gradle
- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/package-info.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/EmbeddedKafkaConditionTests.java
- src/reference/asciidoc/testing.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1107
> GH-1107: Improved JUnit5 Support

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1111
`pause()` the consumer in the rebalance listener so that the Consumer
will discard any fetched records that would otherwise be returned by
the initial poll.
> Fix re-pausing consumer after a rebalance

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
The paused state from ConcurrentMessageListenerContainer was not
propagated to the newly instanciated KafkaMessageListenerContainers
when calling start().
> GH-1111 Propagate the CMLC paused state on start

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecordInterceptor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1118
> GH-1118: Add RecordInterceptor

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1121
`getSingleRecord()` didn't work if the consumer was subscribed to
multiple topics that had records.
Change the assert to ensure there is just one message for the
requested topic and seek any records that were retrieved for other
topics.
> GH-1121: Fix KTU.getSingleRecord()

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/JacksonMimeTypeModule.java
- spring-kafka/src/main/java/org/springframework/kafka/support/JacksonUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/1129
Introduce a `JacksonMimeTypeModule` with a simple `MimeTypeSerializer`
for the proper inter-platform `MimeType` objects serialization.
Essentially we call its `toString()` which is enough to carry mime-type
info over the network.
Register this module in the `JacksonUtils.enhancedObjectMapper()` which
is used from the `DefaultKafkaHeaderMapper`.
Such a module can be registered as a bean in the application context
and will be automatically discovered by Spring Boot auto-configuration
for Jackson
* Modify a `DefaultKafkaHeaderMapper` to not deal with `MimeType`
directly any more since it is covered by the `JacksonMimeTypeModule`
even if `MimeType` is a part of collection like it is in case of
mapped HTTP headers.
* Modify …
> GH-1129: Add JacksonMimeTypeModule

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1134
We always have to call `callback` in the `stop(Runnable)` implementation
independently of the component state
**Cherry-pick until 1.3.x to support Spring Boot 1.5.x**
> GH-1134: Fix `stop(Runnable)` usage

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/AbstractJavaTypeMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/DefaultJackson2JavaTypeMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1137
- use `lastHeader()` to ensure we retrieve the latest header
- clear the headers when serializing, if already present
- also expose the existing deser `useTypeHeaders` Kafka property as a property directly
> GH-1137: Fix Json Type Headers for KStream

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
When processing manual acks on a "foreign" thread, the commits are
not made until the consumer wakes from his `poll()`.
For `AckMode.MANUAL_IMMEDIATE`, we should wake the consumer so the
offset(s) are committed as soon as possible.
> AckMode.MANUAL_IMMEDIATE - wake Consumer

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanTests.java
Since Kafka Streams 2.1, StreamsBuilder has a `build(Properties)` method whose use is required to benefit from [topology optimization](https://docs.confluent.io/current/streams/developer-guide/optimizing-streams.html) (i.e., the `topology.optimization=all`). 
However, currently `StreamsBuilderFactoryBean` calls the older `build()` without arguments, which, since 2.3, doesn't do any topology optimization at all. (In 2.1.x and 2.2.x, it at least did the KTable
source changelog reuse optimization if `topology.optimization` is set on the `KafkaStreams` level.)
With this PR, we always use `build(Properties)` and thus allow Spring Kafka to make full use of topology optimization by just setting `topology.optimization`.
> Use StreamsBuilder#build(Properties) to allow topology optimization

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionInitialOffset.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
- enable users to perform seeks, relative to the partition start, end,
or current position.
> Add relative seek to ConsumerSeekCallback

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryLateConfigTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1159
- build `properties` field from `StreamsConfig.originals()`.
> GH-1159: SBFB: Fully deprecate StreamsConfig

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1168
`sendOffsetsToTransaction` assumed the transaction was started by a
`KafkaTransactionManager` and using `executeInTransaction` failed.
Look for a local transactional producer before checking for a thread-bound transaction.
> GH-1168: Fix sendOffsets in local transaction

- build.gradle
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
After introducing a `BeanDefinition.getResolvableType()` we have
several failed builds because of `NoSuchMethodError`.
Looks like interface and its implementation classes are loaded from
different versions.
* Exclude `org.springframework` from `spring-data-commons` to avoid
CLASSPATH conflicts
Related to
https://build.spring.io/browse/SK-SON-1242/
https://github.com/spring-projects/spring-framework/issues/23178
> Bump to the latest BUILD-SNAPSHOTs

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Improve the code by using supplier in the assert messages instead of static messages.
We had a problem in our project, because of the string generation in AbstractKafkaListenerEndpoint Line [474](https://github.com/spring-projects/spring-kafka/blob/2a05612410788ddaa1527da2ad9e4dd0ed63486e/spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java#L474). The method endpointDescription in MethodKafkaListenerEndpoint needs the EventListener Bean, which in our case was not yet correctly initialized.
By using the lazy message generation our problem was solved and in the same context I also updated the other assert calls.
> Update assert messages to supplier messages

- .travis.yml
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1171
Allow the use of custom header names for request/reply semantics.
> GH-1171: Custom headers for ReplyingKafkaTemplate

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
(if not specified by the user).
See https://stackoverflow.com/questions/57481979/embedded-kafka-starting-with-wrong-number-of-partitions/57482246#57482246
> Embeded broker - automatically set num.partitions

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaResourceHolder.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1196
Add `closeTimeout` to `KafkaTemplate` and `KafkaTransactionManager` (default 5s).
Use a zero timeout if a transaction operation failed with a timeout.
> Use close(Duration) instead of close()

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaResourceHolder.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1196
Add `closeTimeout` to `KafkaTemplate` and `KafkaTransactionManager` (default 5s).
Use a zero timeout if a transaction operation failed with a timeout.
> GH-1196: Use close(Duration) instead of close() [13x]

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaResourceHolder.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1196
Add `closeTimeout` to `KafkaTemplate` and `KafkaTransactionManager` (default 5s).
Use a zero timeout if a transaction operation failed with a timeout.
Deprecate 1.3.x public APIs
> GH-1196: Use close(Duration) instead of close() [21x]

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaResourceHolder.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/transaction/KafkaTransactionManager.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1196
Add `closeTimeout` to `KafkaTemplate` and `KafkaTransactionManager` (default 5s).
Use a zero timeout if a transaction operation failed with a timeout.
Deprecate 1.3.x public APIs
> GH-1196: Use close(Duration) instead of close() [22x]

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Fixes https://github.com/spring-projects/spring-kafka/issues/1186
A new `ContainerProperties.idleBetweenPolls` option allows to configure
a sleep interval between `poll` calls in the main container loop.
The actual sleep interval is selected as a minimum from provided
option and difference between `max.poll.interval.ms` and records
processing time
> GH-1186: Add `idleBetweenPolls` container option

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- if a recoverer `BiConsumer` threw an exception, the seeks would not be performed
- also add try/catch around after rollback processor calls
**cherry pick to 2.1.x, 1.7.x**
> Try/Catch around error recovery [Backport]

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1219
Avoid `ClassCastException`.
> GH-1219: Assert no retry with batch listener

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1234
Previous implementation assumed the first redelivered record would be
the one that failed; this is not always the case.
Maintain state for each topic/partition/offset.
> GH-1234: Fix FailedRecordTracker [2.2.x]

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- move `consumerProperties` from `ContainerProperties` to `ConsumerProperties`
- rename to `kafkaConsumerProperties`
- deprecate old accessors
- allows overriding factory consumer properties in SIK message source
> Pull Up Consumer Properties

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1247
Previously, stopping the container unconditionally called `consumer.wakeUp()`.
It should only be woken while actually polling, otherwise operations such
as `commitSync()` would fail (after committing the offset but before calling
any callbacks or interceptors).
Add logic to only wake the consumer while it is in the `poll()` method.
**cherry-pick to 2.2.x, 2.1.x**
> GH-1247: Only wake consumer while polling

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
String-valued headers are now mapped as raw strings by default instead
of being encoded as JSON strings.
This can be disabled until all applications have been upgraded to use
2.3 or later.
> DefaultKafkaHeaderMapper Improvement

- build.gradle
- spring-kafka/src/main/java/org/springframework/kafka/support/JacksonUtils.java
- one deprecated method replaced by `JsonBuilder.configure(...)`.
GA is expected before our GA.
> Upgrade to Jackson 2.10

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerFailedToStartEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStartedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStartingEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1252
- also log an error when a consumer fails to start
> GH-1252: Add more consumer lifecycle events

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/EmbeddedKafkaRule.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/EmbeddedKafkaBrokerTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/rule/AddressableEmbeddedBrokerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1254
- port `EmbeddedKafkaBroker` from scala and add ZK port configuration
- add `zookeeperPort` to `@EmbeddedKafka`
> GH-1254: Configurable Embedded Zookeeper Port

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RecordMessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1225
When no argument is sourced from a `Message<?>` (no `@Headers`, `@Payload`,
etc - only `ConsumerRecord`, `Acknowledgment` or `Consumer`) then don't
convert.
> GH-1225: @KL - skip conversion when not needed

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1259
Previously if the recoverer in a `SeekToCurrentErrorHandler` or
`DefaultAfterRollbackProcessor` failed to recover a record, the
record could be lost; the `FailedRecordTracker` simply logged
the exception.
Change the `SeekUtils` to detect a failure in the recoverer (actually
any failure when determining if the failed record should be recovered)
and include the failed record in the seeks.
In this way the recovery will be attempted once more on each delivery
attempt.
> GH-1259: Handle Failed Record Recovery

- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1259
When a record fails with an exception that is not classified for retry,
handle a failed recovery and re-seek the failed record.
`FailedRecordTracker.skip()` is not used for unclassified exceptions,
it's recoverer is called directly.
> GH-1259: Failed recovery with no retry

- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1260
Refactor common code with `SeekToCurrentErrorHandler` into
`FailedRecordProcessor` super class.
> GH-1260: Add exception classification to DARP

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- src/reference/asciidoc/kafka.adoc
- was `pollInterval` instead of `pollTimeout`
> Fix typo around NRCEvent properties

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1274
The deprecated CTORs taking `maxFailures` did not properly set up the
`BackOff` when `maxFailures` was negative (infinite retries).
> GH-1274: Fix STCEH Deprecated CTOR

- spring-kafka/src/main/java/org/springframework/kafka/listener/GenericErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1273
Previously, offsets were only committed if an error handler "handled" an
error (did not throw an exception), when transactions are being used.
Now, if an error handler successfully recovers, the offset will automatically
be committed.
Since this is a behavior change, a new boolean `ackAfterHandle()` is added to
the `GenericErrorHandler`, default `false` and the `SeekToCurrentErrorHandler`
returns `true`; it is the only framwork handler that can recover from failures.
In a future release, this boolean will be `true` by default.
> GH-1273: Fix offset commit after recovery

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1278
Support transaction per partition with Batch Listeners so the `transactional.id`
is tied to the group/topic/partition.
> GH-1278: Zombie Fencing with Batch Listener

- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/EmbeddedKafkaRule.java
`ExternalResource` already implements `TestRule` which makes the explicit implementation of `TestRule` obsolete.
> Remove unnecessary implements statement

- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1287
Throw an `IllegalStateException` in the `SeekToCurrentErrorHandler` if
the root exception is a `SerializationException`.
Handling of deserializatin problms requires the configuration of an
`ErrorHandlingDeserializer2`.
**cherry-pick to 2.2.x, 2.1.x**
> GH-1287: Detect mis-configured deserialization

- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1289
Fix IOOBE If a not-retryable exception was thrown outside of record handling
(when no records are passed to the error handler).
Throw an illegal state exception if this condition occurs.
> GH-1289: STCEH - Fix IndexOutOfBoundsException

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/1301
* Restore `DefaultKafkaHeaderMapper.DEFAULT_TO_STRING_CLASSES` set
of `MimeType` and `MediaType`
* Use this set as default one for the `toStringClasses` property
* Therefore `MimeType` headers are now stored in the `ProducerRecord`
as string.
* Also encode all the `toStringClasses` values as JSON - for backward
compatibility as well
This makes it backward compatible with previous versions and doesn't
break the current version since it is easy to recreate a `MimeType`
from its string representation - Postel's law
> GH-1301: Make DefKafkaHMapper backward compatible

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
When `idleBetweenPolls` was set, the sleep was done after invoking
the listener and before calling `pollAndInvoke()` again.
This delays committing the offsets for ack modes other than `RECORD`.
Move the sleep to after committing the offsets and before the next `poll()`.
> Don't delay batch offset commits

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
Add seek to beginning/end variants that take a collection to make
resetting all assigned partitions easier, and more efficient.
> ConsumerSeekAware Improvement

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1309
When no commit timeout is provided we update the properties in the local
container properties.
The parent container's properties must also be updated because the parent
is passed into the error handler (e.g. for stopping the entire container
when an error occurs).
Also, fix a problem where the child container instead of the parent was
passed into the batch error handler.
> GH-1309: Fix NPE when no syncCommitTimeout set

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1321
Provide an option to invoke `RecordInterceptor` before the transaction starts.
> GH-1321: Add intercept before Tx option

- src/reference/asciidoc/testing.adoc
This is code block for explaining methods to set up producer and consumer properties. So 'consumerProps()' and 'producerProps()' are must be here. But there is 'senderProps()' method instead of 'producerProps().
API ref. `org.springframework.kafka.test.utils.KafkaTestUtils#producerProps`
> Fix wrong method name in docs

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1331
Authorization errors create a log storm; stop the container for
such exceptions in the same way we do for `NoOffsetForPartitionException`.
> GH-1331: KMLC - treat auth. exceptions as fatal

- build.gradle
- gradle.properties
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaConsumerTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareRebalanceListener.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/GenericErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/HeaderEnricherTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/messaging/MessagingTransformerTests.java
- src/reference/asciidoc/appendix.adoc
- src/reference/asciidoc/changes-since-1.0.adoc
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
- Remove references to ZkClient
- deprecation of `Consumer.committed(TopicPartition tp)`
- Addition of `onPartitionsLost` to `ConsumerRebalanceListener`
- since `onPartitionsLost` calls `onPartitionsRevoked` by default with a
possible partial list, remove the revoked partitions from the assignments
- fix some reflection uses in tests (`groupId` field and `NewTopic`)
- fix `EKIT` `listen12` listener - we now always get the full batch
- `ConsumerRebalanceListener.onPartitionsRevoked` is no longer called with an
empty collection
- deprecation of some `TopologyDriver` helper classes
- update what's new and change log appendix
- add `unregisterSeekCallback` to `ConsumerSeekAware`
- `AbstractCSA` now removes TL there since we may have only a partial revoke
> Upgrade to 2.4 clients

- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1319
- change the release strategy to a `BiConsumer`
- call the strategy during normal message delivery as before
- now call the strategy when releasing a partial result after timeout
- allow the strategy to modify the list (change from `Collection` to `List`).
> GH-1319: Agg. Replying Template improvement

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1340
Previously, a reply type of `Collection` always split the collection
into discrete replies.
There is now an option to send the entire collection in the reply.
**cherry-pick to 2.3.x - there will be a conflict in the what's new**
> GH-1340: Support returning a collection

- src/reference/asciidoc/appendix.adoc
spring kafka 2.4 depends on apache kafka 2.4, this PR updates it.
In addition, I would like to know if changing is hard coded is the best practice, or use the `project-version` param
> kafka 2.4 dependencies

- src/reference/asciidoc/streams.adoc
There is 2 way that create the StreamsBuilderFactoryBean by `@Bean` method, returning as `StreamsBuilderFactoryBean` type or as `FactoryBean<StreamsBuilder>` type. but document’s code said return `FactoryBean<StreamsBuilderFactoryBean>` type.
> Fix return type in streams docs

- build.gradle
Fixes https://github.com/spring-projects/spring-kafka/issues/1344
Sometimes people build our project outside of Git repository
* Make the `updateCopyrights` Gralde task conditional on
the presence of `grgit` object initialized by the
`org.ajoberstar.grgit` when Git repository is present.
Otherwise it is `null`
* Check for `grgit` presence when we try to gather `modifiedFiles`
> GH-1344: Enable updateCopyrights onlyIf grgit

- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/EmbeddedKafkaConditionTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1347
When count > 1 with no port specification (default random port)
tests failed because not enough ports were provided,
> GH-1347: Fix @EmbeddedKafka with count > 1

- spring-kafka/src/main/java/org/springframework/kafka/config/CompositeKafkaStreamsInfrastructireCustomizer.java
- spring-kafka/src/main/java/org/springframework/kafka/config/CompositeKafkaStreamsInfrastructureCustomizer.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsInfrastructureCustomizer.java
- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanCustomizer.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
- src/reference/asciidoc/streams.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1236
Allow modification of the builder and/or topolgy before the stream is
created.
> GH-1236: Add Streams infrastructure customizer

- spring-kafka/src/main/java/org/springframework/kafka/support/ProducerListener.java
- src/reference/asciidoc/kafka.adoc
See https://github.com/spring-projects/spring-kafka/pull/681#issuecomment-577203808
Deprecate the legacy methods since all the information is available in the
variants that get the full `ProducerRecord`.
> GH-681: Fix docs/deprecations for ProducerListener

- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
When reading the reference manual, it is likely that one would encounter the "Introduction" and start with the "consumer properties map" approach to configuring deserialization. However, in the course of troubleshooting consumer failures  (eg. deserialization errors), one might read further into the manual and encounter the "Serialization, Deserialization, and Message Conversion" section, and pass instances of deserializers to the consumer factory in an attempt to fix the failures, and might miss out that in fact consumer properties map now has no effect.
Mention this in the documentation, and add a test case illustrating this is the expected behaviour.
> Document more explicitly that (de)serialization config properties have no effect when instances are provided

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommitOnAssignmentTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1370
Add an option to control current offset commit behavior on partition assignment.
Container changes might be easier to review with `?w=1` after initial review.
> GH-1370: Opt. commit current offsets on assignment

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordProcessorTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1354
When a negative `maxAttempts` was used, the default backOff interval was
5s instead of 0.
> GH-1354: Fix default BackOff with deprecated CTOR

- src/reference/asciidoc/kafka.adoc
This PR simply fixes a typo in reference.
#1374 
Thank you!
> Fix typo in reference adoc

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1376
The customizer was not called for containers created for `@KafkaListener`,
only for containers created manually via the factory.
> GH-1376: Fix ContainerCustomizer

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1369
1. `CloseSafeProducer.cache` was incorrectly null
(direct access to `this.cache` instead of `getCache()`
Prevented closure of a fenced `consumerProducer`
2. Don't call the `AfterRollbackProcessor` when a producer is fenced -
the partitions will have already been revoked so seeking is inappropriate
and starting a new transaction will fence the new (current) producer.
**cherry-pick to 2.3.x if clean**
> GH-1369: Fix Fenced Consumer-based Producers

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
For build servers with high load, it may happen that the build hangs for couple of seconds. This causes the internal ZK client session of embedded Kafka broker to timeout and fail the build.
It would be good if these were configurable.
> Make ZK client timeouts configurable

- src/reference/asciidoc/quick-tour.adoc
Probably topic1 should be declared as variable, or it just may be a string as it's in mr
> Doc typo fix

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchToRecordAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DefaultBatchToRecordAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/BatchListenerWithRecordAdapterTests.java
Incorrectly passed the whole message list to the callback, which
caused listeners with a `ConsumerRecord<?, ?>` argument to fail.
Changes a public API but there is no choice and it was only added a couple of
weeks ago.
> Fix BatchToRecordAdapter

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1386
The builder was incorrectly customized in `start()`. It needs to be
customized after creation so that when it is used to create `KStream`s
elsewhere, it is already customized.
> GH-1386: Fix StreamsBuilder customization

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1385
When configuring the trusted packages from consumer properties, trim
whitespace characters.
> GH-1385: JsonDeserializer - trim trusted packages

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1353
`AckMode` is not used with transactions - clarify the semantics in docs
and javadocs.
Also fix that offsets were not previously sent to the transaction with an
incorrectly configured MANUAL ack mode.
> GH-1353: Clarify AckMode with transactions

- CONTRIBUTING.adoc
- README.md
It seems the contribution guidelines are still referencing JIRA and this can lead to confusion for future contributors.
Fixed it by changing it to GitHub issues
> Replace JIRA ticket with GitHub issue in the contribution guidelines

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1388#issuecomment-588890911
Don't start a new transaction in the `DeadLetterPublishingRecoverer` if the
`KafkaTemplate` allows it.
> GH-1388: DeadLetterPR: Don't start a Tx if allowed

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1400
Currently, StreamsBuilderFacotryBean does not give direct access to the toplogy object.
It will be beneficial for downstream clients such as the Kafka Strems binder in
Spring Cloud Stream to get access to the topology object directly.
> GH-1400: Expose topology from StreamsBuilder

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DeserializationException.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer2.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversion2Tests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- src/reference/asciidoc/kafka.adoc
- strip exception header from record published to DLT
- remove deprecated `ErrorHandlingDeserializer`
- rename `ErrorHandlingDeserializer2` to `ErrorHandlingDeserializer`
- add deprecated `ErrorHandlingDeserializer2`
> DeadLetterPublishingRecoverer improvements

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1414
- synchronize all access to `this.containers`
- don't return an indirect reference to the field in `getContainers()`
**cherry-pick to all supported (1.3.x will require a back port)**
> GH-1414: ConcurrentMLC Fix ConcurrentModification

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessageConverter.java
- spring-kafka/src/test/java/org/springframework/kafka/support/converter/MessagingMessageConverterTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
The message converter builds a simple `Map` from the record properties;
it does not use a `MessageBuilder`; a `null` key was incorrectly mapped
with a `null` value instead of omitting the header altogether.
> Don't populate a null RECEIVED_MESSAGE_KEY

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1424
Do not deliver remaining records after a `ProducerFencedException` - the
partitions will have been reassigned to another instance.
> GH-1424: Abort delivery on ProducerFencedException

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerStoppingErrorHandlerRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackBatchTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackRecordTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/RemainingRecordsErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
See GH-1370
- deprecate `ContainerProperties.getTopicPartitionsToAssign()`
- defaults for `ackCount`, `ackTime`
- `subBatchPerPartition` default `true` for transactions
- `assignmentCommitOption` default to `LATEST_ONLY_NO_TX`
- deprecate `ackOnError`
> GH-1370: Container props: Polish, Defaults, Docs

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/rule/AddressableEmbeddedBrokerTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/AliasPropertiesTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversion2Tests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/StatefulRetryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/RetryingBatchErrorHandlerIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandlerTests.java
- src/reference/asciidoc/testing.adoc
- src/reference/asciidoc/whats-new.adoc
Since, in most cases, tests require
`props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");`
change the utility method to set it by default.
Remove unnecessary `props.put()` in tests, including one which incorrectly
set it to `latest`.
> Change default test consumer config a.o.r=earliest

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/RoutingKafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1437
The future returned by `Producer.send()` may have been immediately completed
with an exception; check if `future.isDone()` and call `get()` so that any
such exception is propagated to the caller.
**I will perform backports after review/merge.**
> GH-1437: Check for immediate failure on send

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1441
Close and remove a producer after a `OutOfOrderSequenceException` or subclass.
**I expect conflicts so I will do the backports**
> GH-1441: Close producer after fatal send error

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1446
See https://kafka.apache.org/documentation/#static_membership
Add a qualifier to `group.instance.id` for each child container.
Catch `FencedInstanceIdException` and stop the container.
Fix delay on self-stopping containers.
Treat `FencedInstanceIdException` the same as `ProducerFencedException` when
using transactions (do not call `AfterRollbackProcessor`.
> GH-1446: Support Static Group Membership

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
In 2.4 we added support for cooperative rebalancing by removing
specific revoked partitions in `onPartitionsRevoked`.
However, `onPartitionsAssigned` is also called (often with no
partitions), so we should not replace the exiting assignments,
but add the new assignments.
**cherry-pick to 2.4.x**
> Fix assigned partitions with cooperative rebalance

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Complete the remainder of `onPartitionsRevoked()` if the commits fail
fatally.
It is possible that commits might fail when using manual acks; we must
complete the remainder of the method if the commits fail.
**I will backport as needed**
> Fix commits on partition revocation

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Retrying deliveries is more reasonable default behavior than just
logging the failure.
> Change Default Error Handlers

- build.gradle
- spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/MicrometerConsumerListener.java
- spring-kafka/src/main/java/org/springframework/kafka/core/MicrometerProducerListener.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
- Refactor `DKPF` so that `CloseSafeProducer` is not aware of whether it is cached
- Add producer and consumer factory listeners
- Add listener implementations for Micrometer
> Producer/Consumer Factory Listeners and Micrometer

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
Resolves https://github.com/spring-projects/spring-kafka/issues/194
Create the temporary directory in EKB instead of the broker to avoid
`NoSuchFileException`s during shutdown.
**cherry-pick to 2.4.x, 2.3.x, 2.2.x**
> Manage log.dir in the EmbeddedKafkaBroker

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Commit on assignment should not occur when `auto.offset.reset` is `earliest`
when assigment option is not `ALWAYS`.
The code did not consult the factory configuration, just the container
properties.
Work around is to set it on the container properties.
> Fix commit on assignment for earliest setting

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaFailureCallback.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaProducerException.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaSendCallback.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1475
Add `onFailure` with a narrowed `Throwable` to make it easier to access
the failed producer record.
> GH-1475: Add KafkaSendCallback

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Exit from the method when we encounter a fatal error.
(Early exit was lost during refactoring).
> Fix fatal early return from onPartitionsAssigned

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AdapterUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/ConsumerRecordMetadata.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/config/RecordMessagingMessageListenerAdapterTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1479
Because we pass the payload in as a discrete argument, standard headers
such as `RECEIVED_TOPIC` will get the payload value if it's a String.
See https://github.com/spring-projects/spring-framework/issues/25033
Provide a mechanism to get the record metadata as a parameter instead.
Make this available in all listeners for consistency.
> GH-1479: ConsumerRecordMetadata

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/AliasPropertiesTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1487
A meta-annotated annotation did not work at the class level.
**cherry-pick to 2.4.x, 2.3.x, 2.2.x**
> GH-1487: @KafkaListener Meta-Annotation on Class

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Automatically handle "standard" types supported by the `Serdes`.
> Delegating(De)Serializer Improvements

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java
- src/reference/asciidoc/kafka.adoc
Previously, a single config and selector header was available
making it impossible to use these (De)Serializers for both
key and value.
**I will backport after merge as needed due to conflicts**
> Support keys in Delegating(De)Serializer

- src/reference/asciidoc/kafka.adoc
corrects two small typos in the documentation.
> Corrects two typos

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/main/java/org/springframework/kafka/streams/KafkaStreamsMicrometerListener.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/streams.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1501
> GH-1501: Add Micrometer Support for KafkaStreams

- spring-kafka/src/main/java/org/springframework/kafka/listener/AfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1508
- also validate configuration when `commitRecovered` is `true`; deprecate setters.
> GH-1508: Fix DefaultARProcessor for EOSMode.BETA

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1501
- add support for multiple listeners
- consistent with consumer/producer factories
> GH-1501: StreamsBuilderFB.Listener Improvement

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AdapterUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1519
An empty `@SendTo` on a `@KafkaListener` method means send the reply
to the `KafkaHeaders.REPLY_TOPIC` header.
This default was not applied for class-level `@KafkaListener`s.
**backport to 2.4.x, 2.3.x, 2.2.x**
(I will do the back ports, because I expect conflicts).
> GH-1519: Fix @SendTo on @KafkaHandler

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1522
If the `errorHandler.isAckAfterHandle()` is true and the handler exits
normally, add the offset to the pending `acks`, even when the `AckMode`
is `MANUAL`.
> GH-1522: Commit recovered record with MANUAL Acks

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1527
For example, to set a timeout for other transaction managers in a
chained transaction manager.
> GH-1527: Add Support for Transaction Properties

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommitOnAssignmentTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxRollbackTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTxTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/changes-since-1.0.adoc
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1451
- switch the container default `EOSMode` to `BETA`
- configure the producer to fall back to `ALPHA` if the broker is not compatible
> GH-1451: Exactly Once Semantics Mode BETA Default

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Sometimes I have this kind of exception while I try to rewind Kafka partitions by timestamp:
```
Caused by: java.lang.NullPointerException: null
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$processTimestampSeeks$31(KafkaMessageListenerContainer.java:2048)
at java.util.HashMap.forEach(HashMap.java:1289)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.processTimestampSeeks(KafkaMessageListenerContainer.java:2048)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.processSeeks(KafkaMessageListenerContainer.java:1988)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1040)
at …
```
> FIX: KafkaMessageListenerContainer#processTimestampSeeks offsetsForTimes method can return map with null values

- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
- src/reference/asciidoc/kafka.adoc
Handle `DeserializationException` via `ErrorHandlingDeserializer` in
`ReplyingKafkaTemplate`.
**I will do the backports after review/merge; I expect conflicts**
> ReplyingKTemplate Handle DeserializationException

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1547
It generally makes sense to repeat the back offs after a recovery failure
instead of attempting recovery immediately on the next delivery.
Add an option to revert to the previous behavior.
> GH-1547: Reset BackOff State on Recovery Failure

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1550
- trust arrays of trusted types (including arrays of primitive wrappers and String))
- trust arrays of primitives
> GH-1550: DefaultKafkaHeaderMapper - trust arrays

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/PartitionOffset.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/TopicPartition.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionOffset.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualAssignmentInitialSeek.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualAssignmentInitialSeekTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/tips.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1554
When using manual assignment it was difficult to specify the initial
offset for multiple partitions - especially when dynamically determined.
Add a wildcard to indicate the offset should be applied to all partitions.
> GH-1554: Partition wildcard for initial offsets

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1552
Previously, non-String-valued consumer property overrides were ignored (and logged).
This is due to the unfortunate design of `Properties` being a subclass of `HashTable`
in that only String-valued properties can be accessed in the nested `default`
properties `HashTable`.
- when creating the merged `Properties` to create the consumer, copy any non-String-valued
properties from the default hash table to the new properties object
- in the DKCF, iterate over the hash table to find any other properties not already found
- log an error if we find non-String-valued default properties
> GH-1552: Support more consumer properties override

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
- remove unnecessary assertions - it is no longer possible to set the classifier
- add varargs version of `addNotRetryableExceptions`
> FailedRecordProcessor Polishing

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1559
Provide a mechanism to select which `BackOff` to apply.
> FailedRecordProcessors - selectable BackOff

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves #1566 
This pull request makes `ConversionException` not retryable exception.
> Add ConversionException in FailedRecordProcessor.classifier to skip retrying

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- Wrong default used when `max.poll.interval.ms` is not specified - 30s Vs 300s
- Value set in `@KafkaListener.properties` ignored for this calculatio and default
used instead
- Also use actual default for `ConsumerConfig.DEFAULT_API_TIMEOUT_MS_CONFIG`
**I will back port - expecting conflicts**
> Fix idleBetweenPolls max value calculation

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1565
Previously extended `ErrorHandlingDeserializer` only worked if configured
as a class rather than a class name.
Spring Boot automatically converts the class names to classes but config
outside of such an environment would not work.
**cherry-pick to 2.5.x, 2.4.x, 2.3.x**
> GH-1565: ErrorHandlingDeserializer Extensions

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1569
Allow provision of around advices, for example to set/reset logging MDC.
**cherry-pick to 2.5.x (what's new will need fixing)**
> GH-1569: Add Message Listener Advice Chain

- src/reference/asciidoc/kafka.adoc
`producerPerConsumerPartition` is a property of `DefaultKafkaProducerFactory` and not of `DefaultKafkaConsumerFactory`
> fix references to producerPerConsumerPartition

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerde.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
This changes improve ability to configure `JsonSerde` as well as `JsonSerializer` and `JsonDeserializer`.
First, allow `TypeReference` and `JavaType` when constructing `JsonSerde`. This can be helpful when using Serde for deserialization, but there are container types involved.
Second, allow forcing type format when serializing. This is actually a problem that cannot be currently solved using `JsonSerializer`: Lets assume theres a serialized type A, which is polymorphic and there is a list of objects of type A, possibly subtypes. Currently, the mechanism finds typed jackson serializer only for raw list, and serializes contents without configuration, so as simple beans, skipping properties that should be added. This can be seen in test …
> Json (de)serialization configuration improvements

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Message conversion is bypassed when consuming the raw `ConsumerRecord`.
However, the request message is needed when returning a result (for
reply topic determination, correlation, etc).
**I will do the backports; I expect conflicts in the test.**
> Fix Request/Reply with ConsumerRecord<?, ?>

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Don't poll the consumer if the container has already stopped.
This causes excessive test run times.
Local build time reduced from 7 minutes to less than 5.
> Fix Shutdown Race Causing Test Delays

- spring-kafka/src/main/java/org/springframework/kafka/config/TopicBuilder.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
- src/reference/asciidoc/kafka.adoc
The `TopicBuilder` now supports deferring to the broker defaults
for number of partitions and replicas.
> Topic Provisioning - default partitions/replicas

- spring-kafka/src/main/java/org/springframework/kafka/listener/GenericErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RetryingBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1582
- allow users to use `getContainerProperties().getGenericErrorHandler().setAckAfterHandle(false)`
- add the propery to error handlers where it was missing (except logging handlers)
> GH-1582: Add GenericErrorHandler.setAckAfterHandle

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1587
See javadoc for `ConsumerProperties.setFixTxOffsets()` for more information.
> GH-1587: Option to Correct Transactional Offsets

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/support/CompositeProducerListener.java
- spring-kafka/src/main/java/org/springframework/kafka/support/LoggingProducerListener.java
- spring-kafka/src/main/java/org/springframework/kafka/support/ProducerListener.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- src/reference/asciidoc/kafka.adoc
When sending a record with no partition, and an error occurs, the
`RecordMetadata` might contain the assigned partition if the error occurs
after partition assignment; this may be useful information for the
application.
> Add RecordMetadata to ProducerListener.onError

- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/GenericErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1591
`BackOff` was ignored for batch listeners (not recoverable).
- move code from `SeekToCurrentBatchErrorHandler` to `ListenerUtils`
- call from both STCEH and DARP
- also clear the thread state (in both) if a batch fails and subsequently succeeds
**I will do the backports - conflicts are expected**
> GH-1591: Apply BackOff in DARP with Batch Listener

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1587
Code was using the presence of a transaction template instead of the KTM.
> GH-1587: Fix NPE with Foreign TM and fixTxOffsets

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
Resolves
Do not clear the cache in `destroy()` - just drain the producer queues instead.
Fixes a race condition where a producer could be returned to the cache between draining
the queues and clearing the map.
Just leave the queue(s) in place to accept new returns.
**cherry-pick to 2.5.x, 2.4.x, 2.3.x, 1.3.x**
> GH-1613: Fix Race in Producer Factory

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1618
Incorrectly added the child container as a parameter for the `ConsumerStoppedEvent`.
The child container is already passed in as the `source`.
> GH-1618: Remove Duplicate Parameter

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackRecordTxTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1621
When using transactions, the remaining records in the batch after a `nack()`
were incorrectly added to the commit list.
**I will back-port - conflicts expected**
> GH-1621: Fix nack() with Tx Batch Listener

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTests.java
Previously, the `subBatchPartition` was coerced when the `EOSMode`
property was set.
This mechanism relied on `BeanUtils.copyProperties` so it was not
obvious how the default was set to false in 2.6.
Remove the coercion and add explicit code in the determination to check
the `EOSMode`.
> Improve subBatchPerPartition determination

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1633
Only the child container instance should be stopped when a producer is
fenced.
Tested with a Boot Application:
```java
@SpringBootApplication
public class Kgh1633Application {
public static void main(String[] args) {
SpringApplication.run(Kgh1633Application.class, args);
}
@Autowired
KafkaTemplate<String, String> template;
@KafkaListener(id = "kgh1633a", topics = "kgh1633")
public void listen(String in) throws InterruptedException {
System.out.println(in);
this.template.send("kgh1633-1", "foo");
Thread.sleep(10_000);
}
@Bean
public NewTopic topic1() {
return TopicBuilder.name("kgh1633").partitions(1).replicas(1).build();
}
@Bean
public NewTopic topic2() {
return …
```
> GH-1633: Do not stop parent container when fenced

- spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionOffset.java
- spring-kafka/src/test/java/org/springframework/kafka/support/TopicPartitionOffsetTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1637
**cherry-pick to 2.5.x, 2.4.x, 2.3.x**
> GH-1637: Fix TopicPartitionOffset.hashCode()

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerStoppedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1643
> GH-1643: Add More ConsumerStoppedEvent.Reasons

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Producers were incorrectly returned to the cache after a `reset()`.
**I will back-port; conflicts expected**
> Don't cache tx producers after reset()

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1646
```
Failed to correct transactional offset(s)
java.lang.IllegalStateException: You can only check the position for partitions assigned to this consumer.
```
It is not clear how this happened since we remove revoked partitions from `lastCommits`.
However, `lastCommits` should be cleared, even if successful, to avoid unnecessary
processing if no records are received by the next poll.
- add the `lastCommits` to the error log
- clear `lastCommits` in a finally block
> GH-1646 Clear lastCommits after fixTxOffset

- build.gradle
- gradle.properties
- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateTransactionIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- src/reference/asciidoc/changes-since-1.0.adoc
- src/reference/asciidoc/whats-new.adoc
- remove `retries` from tests (deprecated)
- deprecate reactive template `flush()`
> 2.7.0 RC3 Kafka Clients

- build.gradle
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1653
Need to unwrap the cause of `ListenerExecutionFailedException` to determine
if the exception type changed.
> GH-1653: Fix resetStateOnExceptionChange

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1659
> GH-1659: Only Log Record Metadata true by default

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java
- src/reference/asciidoc/testing.adoc
> Add getEndOffsets() to KafkaTestUtils

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareRebalanceListener.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConsumerAwareRebalanceListenerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1668
Users might implement one of the not-consumer-aware methods so the default
methods should delegate to those.
Call in try/catch block, expecially `...RevokedBeforeCommit` to prevent the
commits to be skipped.
**cherry-pick to 2.6.x**
> GH-1688: ConsumerAwareRebalListener Improvements

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1661
Allow properties that resolve to bean names to also resolve to instances
of the required type instead.
> GH-1661: @KafkaListener Improvements

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- fixed variables and methods which include typo `timout` to `timeout`
> fixed typo in ContainerProperties

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1672
Previously (and still, by default), stopping the listener container does
not take effect until the records from the previous poll are all processed.
Add an option to stop after the current record, instead.
**cherry-pick to 2.6.x, 1.5.x**
> GH-1672: Option to Immediately Stop the Container

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
- spring-kafka/src/main/java/org/springframework/kafka/config/MultiMethodKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1675
Add support for payload validation with `@KafkaHandler` methods.
> GH-1675: Validation on @KafkaHandler Methods

- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaHeaders.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- src/reference/asciidoc/kafka.adoc
- src/reference/asciidoc/whats-new.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1605
When both the key and value fail deserialization, populate both
original values in the record published to the DLT.
> GH-1605: DeadLetterPublishingRecoverer Improvement

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapterTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1683
Error message was unclear when a non-MANUAL ack mode was used with an
`Acknowledgment` parameter.
**cherry-pick to 2.6.x**
> GH-1683: Improve Missing Ack Argument Exception

- spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaConsumerTemplate.java
Fixes issue [#GH1693](https://github.com/spring-projects/spring-kafka/issues/1693)
> use concatMap  instead of flatMap to guarantee message ordering

- spring-kafka/src/main/java/org/springframework/kafka/core/ConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1678
Although the consumer factory can override properties using an overloaded
`createConsumer` method, add update/remove methods for properties to be
consistent with the `ProducerFactory`.
Change maps to concurrent to avoid possible `ConcurrentModificationException`.
> GH-1678: Allow CF Property Overrides

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointHandlerMethod.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicAnnotationProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicIntegrationTests.java
- move `EndpointHandlerMethod` to its own file
- remove backward reference from `...Configuration` to its builder
- fix docs
- 
cc/ @tomazfernandes
> GH-920: Fix Class Tangle

- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
```
2021-02-25 15:44:31.640 ERROR 73473 --- [etry-8000-0-C-1] o.s.k.l.SeekToCurrentErrorHandler        : Failed to determine if this record (kgh920-retry-8000-0@5) should be recovererd, including in seeks
```
In `SeekUtils` when the nested exception is a `KafkaBackoffException`.
Also fix some asciidoctor rendering in the docs.
cc/ @tomazfernandes
> GH-920: Suppress ERROR Log for Expected Exception

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1728
Add a hook allowing detection of server errors and complete the future
exceptionally.
**cherry-pick to 2.6.x (minus whatsnew.adoc)**
> GH-1728: ReplyingKT Hook for User Errors

- build.gradle
With these options, we now see
```
KafkaAdminTests > testTopicConfigs() FAILED
org.opentest4j.AssertionFailedError:
Expecting:
<2>
to be equal to:
<3>
but was not.
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at org.springframework.kafka.core.KafkaAdminTests.testTopicConfigs(KafkaAdminTests.java:84)
```
on the console.
It is still useful to capture test results, in case we need to look at STDOUT.
> Enable Verbose Test Logging from Gradle

- spring-kafka/src/main/java/org/springframework/kafka/core/CleanupConfig.java
I'm a dev on the Kafka Streams project, and we frequently have Spring Boot users asking us why their applications take so long to start up even after a clean shutdown. We discovered that the default options choose to manually wipe out all local state when closing the Kafka Streams app. This configuration is not recommended for production applications, and it's arguable whether it's even preferable for development/OOTB settings. 
Given how often this comes up, I recommend changing the defaults to avoid calling `KafkaStreams#cleanup` during a clean shutdown.
> Don't wipe out local state stores by default

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/topics/Config.java
- spring-kafka-docs/src/main/kotlin/org/springframework/kafka/kdocs/topics/Config.kt
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdminOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolver.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1725
- add `NewTopics` collection wrapper for auto topic creation
- add `createOrModifyTopics()`
- add `describeTopics()`
- introduce `KafkaAdminOperations`
> GH-1725: KafkaAdmin Improvements

- build.gradle
- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/requestreply/Application.java
- spring-kafka-docs/src/main/kotlin/org/springframework/kafka/kdocs/requestreply/Application.kt
- spring-kafka-docs/src/main/kotlin/org/springframework/kafka/kdocs/started/consumer/Application.kt
- spring-kafka-docs/src/main/kotlin/org/springframework/kafka/kdocs/started/noboot/Sender.kt
- spring-kafka-docs/src/main/kotlin/org/springframework/kafka/kdocs/started/producer/Application.kt
- spring-kafka-docs/src/main/resources/logback.xml
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RecordMessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/RequestReplyMessageFuture.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/RequestReplyTypedMessageFuture.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/JsonMessageConverter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1741
`ReplyingKafkaTemplate` enable send and receive with `Message<?>`.
- also fix ToC level for new chapter
- also polishing some tests for left over state
> GH-1741: Add Message<?> sendAndReceive(Message<?>)

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/BatchInterceptor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CompositeBatchInterceptor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CompositeRecordInterceptor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareRecordInterceptor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecordInterceptor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1747
Also add `Consumer` to the new 2.7 methods and batch interceptor.
> GH-1747: Add ConsumerAwareRecordInterceptor

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1751
Always trust packages for classes in the id class mappings, even
with an externally injected type mapper.
We don't normally reconfigure mappers when injected, but in this case
it makes sense and provides an easier user experience.
> GH-1751: JsonDeser. Trust Mapped Class Packages

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
- spring-kafka/src/test/java/org/springframework/kafka/support/converter/BatchMessageConverterTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/converter/MessagingMessageConverterTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1757
> GH-1757: Option for Raw ConsumerRecord Header

- spring-kafka/src/main/java/org/springframework/kafka/listener/PartitionPausingBackoffManager.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Fixes #1765
I've also increased the back off times in the Integration Tests - they were too low and where not triggering the back off mechanism, which is why we didn't get this error sooner. It didn't add that much time to the tests in general, just a few seconds.
I also renamed the RetryableTopicIntegrationTests to RetryTopicIntegrationTests since not all listeners have the @RetryableTopic annotation.
Let me know if there's anything to be changed.
Thanks!
> GH-1765 - Fix using same factory for retry & main

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/ContainerFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1770
The clientId property, if set on the container factory, is overwritten
by an empty String if not defined on the annotation.
Check for an empty String (groupId too).
**cherry-pick to 2.6.x**
> GH-1770: Fix ClientId for @KafkaListener

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1776
Set `transactional` flag using overrides.
> GH-1776: Fix transactional Template with Overrides

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1778
`Consumer`/`Producer` post processors are `Function`s and the result should
be used; it was previously discarded.
> GH-1778: Properly Apply Client Post Processors

- spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/test/kotlin/org/springframework/kafka/listener/EnableKafkaKotlinTests.kt
See https://github.com/spring-projects/spring-kafka/issues/748#issuecomment-827333267 (issue not resolved by this)
Kotlin and Lombok (`@SneakyThrows`) can throw checked exceptions even though
the method signatures do not allow it. Such exceptions were not passed to the
error handlers until the failed record is no longer in scope. They were called
as if the consumer itself threw an exception.
Always wrap listener exceptions in `ListenerExecutionFailedException`s.
Also remove Java9 constructs in `@Deprecation`s.
> GH-748: Handle Kotlin/Lombok Message Listeners

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultRetryTopicNamesProviderFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicBootstrapper.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicInternalBeanNames.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicNamesProviderFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/SuffixingRetryTopicNamesProviderFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicBootstrapperTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
Resolves #1772 
Add provider to handle the names used on retry/dl topics (topic name, groupId, etc.). This can be extended to customize the behaviour in addition to the simple suffix parameter.
Currently customizing the default requires to register a bean  implementing RetryTopicNamesProviderFactory interface, with name "internalRetryTopicNamesProviderFactory".
> GH-1772 Add RetryTopicNamesProvider

- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ListenerUtilsTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1785
- only slept for 100ms, regardless of next back off interval
> GH-1785: Fix ListenerUtils.stoppableSleep()

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1787
The validator was invoked twice with a class-level `@KafkaListener` when
no default `@KafkaHandler` is present.
**cherry-pick to all supported**
> GH-1787: Only Validate Once

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/MessagingMessageConverter.java
- spring-kafka/src/test/java/org/springframework/kafka/support/converter/MessagingMessageConverterTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1789
Move the `SmartMessageConverter` invocations to a more logical place,
based on their expected inputs for comversion.
> GH-1789: Refactoring

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/ContainerFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1808
Each container got a reference to the same `Properties` object in
`kafkaConsumerProperties`, unless it was created via a `@KafkaListener`
with property overrides.
Do not copy the property from the factory's properties.
**Cherry-pick to all supported branches**
> GH-1808: Fix Container Properties Crosstalk

- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithSpringTestContextTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1806
When there is a test application context present, do not resolve the
broker for parameter resolution.
> GH-1806: Fix Autowiring Broker in JUnit 5

- samples/sample-04/src/main/java/com/example/Application.java
- samples/sample-04/src/main/resources/application.properties
- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/AliasPropertiesTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateTransactionIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1817
> GH-1817: Allow Annotation Attribute Modification

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicInternalBeanNames.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
This is the other part of the RetryTopicConfigurer extensibility improvement and lets the user provide a custom RetryTopicConfigurer subclass bean. This isn't supposed to be available for non advanced users, so I don't think it should be documented. Please let me know if there's anything to fix or enhance.
With this PR all the changes I had in mind for the RetryTopic feature are complete. From my point of view we can close GH-1745 and also remove the Experimental API designation, if you don't have any other concerns - please let me know if you do.
Thanks a lot for your support so far, it's been amazing!
> GH-1745 - Let users provide a RetryTopicConfigurer bean

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
Just opening some doors for advanced users who want to have more control over the RetryTopicConfigurer. Since the PR from @apolci already covered many use cases through DI it didn't look like it was worth having another DI setup for this.
> GH-1745 - Improve RetryTopicConfigurer flexibility

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ExistingRetryTopicIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1828
**Update DeadLetterPublishingRecovererFactory#resolveDestination**
- Extract out a protected method to `resolveTopicPartition` for destination DLT
- Set the partition to the same partition as the original record
**Test Changes**
- Add tests for `RetryableTopic` with `autoCreate=false`
- Remove unnecessary mockito stubbing from tests
> GH-1828: Use consumer record's partition for @RetryableTopic

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerGroup.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerGroupSequencer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/AliasPropertiesTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerGroupSequencerTests.java
- spring-kafka/src/test/resources/log4j2-test.xml
Resolves https://github.com/spring-projects/spring-kafka/issues/1827
Add a mechanism to automatically control a sequence of containers,
starting a group of containers when the current group goes idle.
> GH-1827: Add ContainerGroupSequencer

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/ExponentialBackOffWithMaxRetries.java
- spring-kafka/src/test/java/org/springframework/kafka/support/ExponentialBackOffWithMaxRetriesTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1804
Simply a convenience to automatically calculate the max elapsed time.
> GH-1804: Add ExponentialBackOffWithMaxRetries

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
updated documentation to add bean name
```diff
- public RecoveringBatchErrorHandler(KafkaTemplate<String, String> template)
+ public RecoveringBatchErrorHandler batchErrorHandler(KafkaTemplate<String, String> template)
```
fixes #1790
> fix missing bean name in documentation

- spring-kafka/src/main/java/org/springframework/kafka/listener/BatchLoggingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/GenericErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/LoggingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RemainingRecordsErrorHandler.java
Motivation - Kotlin uses jsr305 annotations to deduct non-null / nullable types. This PR marks data as explicitly nullable (which happen in code).
Without this it's impossible to pass null value as `data` parameter in Kotlin.
> Data in handle method is @Nullable

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConditionalDelegatingBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConditionalDelegatingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerAwareErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConditionalDelegatingErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1842
> GH-1842: Add Conditional Delegating Error Handlers

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
https://github.com/spring-projects/spring-kafka/issues/1845
- don't idle until partitions are assigned - it caused delayed assignment
- use `ListenerUtils.stoppableSleep()` - don't hold up container stop while idle
- `ListenerUtils.stoppableSleep()` - reduce sleep time for small intervals to
improve resolution
> GH-1845: Idle Between Polls Improvements

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/tips.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1784
> GH-1784: Customizing JSON Serializer/Deserializer

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConditionalDelegatingBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConditionalDelegatingErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConditionalDelegatingErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1842
> GH-1843: Delegating EH - use isAssignable()

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/DefaultJackson2JavaTypeMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1858
Do not add mapping class packages if trusted packages is already all (`*`).
> GH-1858: Fix Regression in JsonDeserializer

- spring-kafka-docs/src/main/asciidoc/changes-since-1.0.adoc
- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/quick-tour.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Preparation for https://github.com/spring-projects/spring-kafka/issues/1189
Defer committing out of order offsets until the gaps are filled.
Pause the consumer until all acks are acknowledged.
> GH-1189: Support Out-of-Order Manual Commits

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1861
> GH-1861: Add KafkaTemplate.receive()

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Fixes #1863.
I remember having read somewhere that some endpoint properties should be set after registering the endpoint - this PR sets all properties before registration for the retry topic endpoints, but all tests pass nevertheless so it doesn't seem to be a problem. If there's any concerns about this please let me know, it'd be a reasonable bigger change if we need to take that into account.
I also noticed the type converter specified in the annotation wasn't being setup too, so I added it to this PR as well.
I added both features to the first integration test in RetryTopicIntegrationTests suite.
Hope it's ok, let me know if there's anything else to be done about this.
Thanks!
> GH-1863 - Setup listener error handler and type converter for @RetryableTopics

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1866
The new retryable topic feature pauses/resumes individual partitions.
This broke normal container pause/resume by incorrectly resuming partitions
that were paused by the container pause operation.
Similarly, if individual partitions were paused and then the container was
paused and resumed, the container resumed all partitions.
Decouple the functionality to prevent this cross-talk.
Do not resume any individually paused partitions when the container is in a paused state.
Do not resume any individually paused partitions when the container is resumed.
Also
Use a `ConcurrentHashMap.newKeySet()` instead of synchronization on partition pause requests.
Use `getAssignedPartitions()` to allow the retry topic feature to work with …
> GH-1866: Fix Pause/Resume

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Flatten `GenericErrorHandler` into a single interface.
Create an adapter for legacy error handlers.
> GH-615: Error Handler Evolution Part 1

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/1870
Also remove references to `KafkaProperties`, which the Boot team doesn't consider
a public API.
> GH-1870: Fix Doc for Programmatic JSON Config

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionOffset.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1876
Support initial seek to timestamp when manually assigning partitions.
> GH-1876: Seek To Timestamp with Manual Assignment

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConditionalDelegatingBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConditionalDelegatingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RetryingBatchErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonDelegatingErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerBatchIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerBatchTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerRecordTests.java
Replaces legacy `SeekToCurrentErrorHandler` and `RecoveringBatchErrorHandler`.
These were the previous defaults when no transaction manager is present.
They will be deprecated in a future PR.
- refactor common code into superclass/utilities
- copy existing test case classes, changing the error handler types
> GH-615: Add DefaultErrorHandler

- build.gradle
- spring-kafka/src/main/java/org/springframework/kafka/support/JacksonUtils.java
* Extract inner classes for Jackson modules
and use them only when respective `static boolean` is true
according presence of required class in CP
* Add `optional` dependencies for Jackson modules for compilation
**Cherry-pick to `2.7.x`**
> Make `JacksonUtils` compatible with Native

- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1883
NPE when `null` `replyTimeout` supplied (javadoc says it's allowed and means use default).
`replyTimeout` argument ignored on message-based methods.
> GH-1883: Fix replyTimeout Logic

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
Resolves: https://github.com/spring-projects/spring-kafka/issues/1888
Incorrectly deprecated when ChainedKafkaTransactionManager was deprecated.
There are still valid use cases for this property.
> GH-1888: Revert Deprec. setTransactionDefinition()

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1880
SpEL can resolve to `String`, `String[]` or `Collection<String>`.
> GH-1880: SpEL Improvements for Property Overrides

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecoveringBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RetryingBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekToCurrentErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/StatefulRetryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualAssignmentInitialSeekTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackRecordTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackRecordTxTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/RecoveringBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorBatchModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTXTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentOnErrorRecordModeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/615
- Deprecate remaining legacy error handlers
- Fix `DefaultErrorHandler` for remaining records and delivery header
- Docs
> GH-615: Complete CommonErrorHandler Work

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
When decorating a `ListenerExecutionFailedException` with the consumer's
group id, add the lost stack trace of the original LEFE in a suppressed
exception. This retains the top stack frames which were otherwise lost;
suppressed exceptions are printed nested within the stacktrace of the new 
exception so we can now see the complete stack trace with no loss.
```
Caused by: org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void com.example.demo.Gitter97Application.listen(java.lang.String)' threw exception; nested exception is java.lang.RuntimeException: x; nested exception is java.lang.RuntimeException: x
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2487) …
```
> Improve Decorated ListenerExecutionFailedException

- spring-kafka/src/main/java/org/springframework/kafka/support/LoggingProducerListener.java
- spring-kafka/src/test/java/org/springframework/kafka/support/LoggingProducerListenerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1898#issuecomment-890854978
Large `byte[]` payloads could cause an OOM.
**cherry-pick to 2.7.x, 2.6.x, 2.5.x**
> GH-1898: Fix OOM in LoggingProducerListener

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerGroupSequencer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerGroupSequencerTests.java
Set `autoStartup` to `false` so we see the `Starting first group` message.
> GH-1827: ContainerGroupSequencerTests Diagnostics

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/AbstractJavaTypeMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingSerializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/JsonSerializationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1879
It was not intuitive that configuration properties were not applied when
construcing (De)Serializers programmatically.
The producer and consumer factories now call the `configure()` method.
However, the JSON implementations cannot be configured with a mixture
of setters and configuration properties.
> GH-1879: Factories Now Configure (De)Serializers

- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerGroupSequencer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerGroupSequencerTests.java
- increase idle event interval to prevent sequencer stopping the container too soon.
- tighten up synchronization in the sequencer
> GH-1827: Fix Race

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ExceptionClassifier.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicBootstrapper.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1918
Do not publish records with fatal exceptions to the same topic, it
causes an irrecoverable endless loop.
Log at ERROR when such a situation is detected.
Extract a new abstract super class for exception classification.
> GH-1918: Don't Retry DLT Fatal Exceptions

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationManualAssignmentIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1916
Previously, the `topics` property was used during reply topic configuration
before it had been resolved for SpEL expressions and Property Placeholders.
> GH-1916: Fix RetryableTopic for SpEL and Prop PH

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerGroupSequencerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1909
Increase `idleEventInterval` before data is received, to avoid false positives
with small event intervals.
> GH-1909: Add idleBeforeDataMultiplier

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1929
Need to rebuild the record list after interception (when `interceptBeforeTx` is false).
Otherwise changes made to the records in the `ConsumerRecords` is lost.
Always intercept early when transactions are not used; rebuild list if transactions in
use, `interceptBeforeTx` is false, and a batch interceptor is present.
> GH-1929: Fix BatchInterceptor

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualImmediateNackBatchTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackBatchTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1915
- perform acks within the scope of the ack call so users can catch exceptions with sync commits
- when using MANUAL_IMMEDIATE, commit offsets for the batch instead of one-at-a-time
> GH-1915: Batch Manual AckMode Improvements

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaHeaders.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/ConversionException.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTypeSerializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/BatchAdapterConversionErrorsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java
- src/checkstyle/checkstyle-suppressions.xml
Resolves https://github.com/spring-projects/spring-kafka/issues/1936
Make it easier to detect and recover from conversion exceptions in batch
listeners.
Also add `DelegatingByTypeSerializer`.
> GH-1936: Batch Listener Handle ConversionException

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AbstractFilteringMessageListener.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/FilteringBatchMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RecordFilterStrategy.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1938
Previously, when adding a filter strategy to a batch listener, the batch
members were filtered one-at-a-time. When database lookups are involved
it is more efficient to act on the entire batch.
Add another method to the filter strategy to allow filtering the entire
batch in one call.
> GH-1938: Support Whole Batch Filtering

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1952
Since maps are built on the fly, maps need to support concurrency.
**cherry-pick back to 2.5.x**
> GH-1952: Fix Possible NPE

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/HeaderMethodArgumentResolverTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1951
Converts `byte[]` (particularly headers) to `long`, `int`, `short` or `byte` (or wrappers).
> GH-1951: Add BytesToNumberConverter

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1948
> GH-1948: KafkaTemplate Receive Multiple Records

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolver.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolverTests.java
Resolves: https://github.com/spring-projects/spring-kafka/issues/1961
> GH-1961: DefaultDestinationTopicResolver: Inconsistencies In Spring Cloud Environment

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolver.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolverTests.java
- rename field to something more meaningful
- just compare the contexts in the event listener
> GH-1961: Polishing

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
The Topic created in `kReplies()` is `"kReplies"`, so this should be reflected in the `repliesContainer`.
> doc: fix topic name in RequestReply-Example

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler1Tests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1970
SCSt health check uses `isRunning()` to measure health. However a container
that was `autoStartup=false` (or has been stopped) is healthy, it is just
not running.
- add `isInexpectedState()`
- add `stopAbnormally()`
- call `stopAbnormally` (from `emergencyStop`) when a listener throws an `Error`
- call `stopAbnormally` from the container stopping error handler
> GH-1970: Add container.isInExpectedState()

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler2Tests.java
Add an option to stop the container normally.
There might be a case where the container is stopped due to an error, but
the user wants the container to remain 'healthy', e.g. to avoid Kubernetes
restarting the instance.
> GH-1970: Container Stopping EH Improvement

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1974
A new `SimpleAsyncTaskExecutor` was created for each child container when
the container was stopped/started.
Reuse the same container for each child; handle an increase to `concurrency` between
stop and start
> GH-1974: Fix Default Task Executor

- spring-kafka-docs/src/main/asciidoc/testing.adoc
Change the JUnit4 rule to `EmbeddedKafkaBroker`.
> Fix EmbeddedKafkaHolder Example Class Names

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicBootstrapper.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicInternalBeanNames.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicBootstrapperTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicInternalBeanNamesTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1994
Add an option to strip previous exception headers when republishing a
dead letter record.
**This is for 2.7.x - back ported due to extra header (CAUSE_FQCN) on main, to resolve conflicts.**
> GH-1994: Option to Strip Exception Headers

- build.gradle
Resolves https://github.com/spring-projects/spring-kafka/issues/1991
We had to add ZK to the spring-kafka-test classpath because Kafka no longer
puts it on the compile classpath since 3.0.0.
This inadvertently pulled in undesired logging dependencies.
> GH-1991: Exclude slf4j impl and log4j via Zookeeper

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/1902
Rename property and use for both exception types.
> GH-1902: AuthenticationException Fatal By Default

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactoryUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2001
Previously, synchronized transaction commits (for producer initiated
transactions) were not propagated to the caller.
> GH-2001: Propagate Exception from TX Sync Commit

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTypeSerializer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2000
Backport `DelegatingByTypeSerializer`.
This is for 2.7.x; cherry pick forward to main.
> GH-2000: Doc RetryTopic Publish with Deser. Errors

- spring-kafka-docs/src/main/asciidoc/appendix.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/2018
> GH-2018: Docs - Downgrading to Apache Kafka 2.8.1

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2036
Improve documentation about how to handle `DeserializationException`s
with batch listeners.
> GH-2036: Deserialization Errors and Batches

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ErrorHandlingDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/2050
The application can have several consumer factories when one fully relies
on the configuration properties for its deserializers and other
configures them programmatically.
The consumer factory now calls `configure()` on the `Deserializer`
independently of its origins.
See https://github.com/spring-projects/spring-kafka/issues/1879
In this case the `ErrorHandlingDeserializer` consults
`spring.deserializer.key.delegate.class` or `spring.deserializer.value.delegate.class`
for its delegate overriding provided explicitly programmatically
* Fix `ErrorHandlingDeserializer` to check it `delegate` and `failedDeserializationFunction`
for null before taking their values from the respective configuration properties
* Add …
> GH-2050: Configure ErrHandlDeser if no delegate

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2055
If context initialization fails, `Lifecycle.stop()` is not called.
Containers must be stopped from `DisposableBean` in this case.
**cherry-pick to 2.7.x, 2.6.x, 2.5.x**
> GH-2055: Containers Must Implement DisposableBean

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerde.java
Narrow return types of `serializer()`, `deserializer()` to avoid casting
if the user wants to programmatically customize the objects.
> JsonSerde Improvement

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
https://github.com/spring-projects/spring-kafka/issues/2076
Do not attempt to retry asynchronous commits.
- a later commit for the same topic/partition may have already succeeded
- many consecutive retryable exceptions can cause a stack overflow
> GH-2076: Fix Async Commit Retries

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
The topic "Conversion Errors with Batch Error Handlers" was at the same section level "Handling Exceptions" but should be a subsection of it. Other subsections of  "Handling Exceptions" were erroneously subsections of "Handling Exceptions".
I fixed section level of "Conversion Errors with Batch Error Handlers" to align with other subsections of "Handling Exceptions".
> Docs: fixed "Handling Exceptions" section levels

- spring-kafka-test/src/test/java/org/springframework/kafka/test/hamcrest/KafkaMatchersTests.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SubBatchPerPartitionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
In preparation for https://github.com/spring-projects/spring-kafka/issues/2089
Missed deprecations.
> GH-2089: Add Deprecations for 3.0 Removal

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2109
Increase default session timeout to 18 seconds to align with Kafka itself.
Also make connection timeout the same, similar to Kafka's default behavior.
> GH-2109: Increase EKB Zookeeper Timeouts

- build.gradle
The `/libs-*` repos require an authentication to download artifacts
**Cherry-pick to `2.8.x` & `2.7.x`**
> Change Spring repositories to official

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicLegacyFactoryConfigurerIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicSameContainerFactoryIntegrationTests.java
Resolves #2069 
This solution uses a decorator to only interfere with container properties when we're in retryable topic logic.
As a result we only change two existing classes, instead of almost 10 from the other PR. I think this should be easier to review and has less chance of interfering with existing logic, while also keeping all retryable topic's factory configuration logic in one class.
I also deprecated two methods in the `ListenerContainerFactoryConfigurer` class, added the possibility of reverting back the behavior, and described this in the documentation. Since we're going to 3.0.0 and I see deprecations are being removed, I can remove these after and if we merge this code to 2.8.x.
Of course, we can still reopen the other PR if you prefer the other solution, no worries. And …
> GH-2069: Same factory for retryable and normal endpoints

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolver.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolverTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DestinationTopicTests.java
Resolves GH-2113
Adds exception classification to DefaultDestinationTopicResolver so that fatal exceptions makes records go straight to the DLT.
Also stop DLT processing if such an exception is found (see GH-2118).
Add documentation on this feature.
> GH-2113: Add ex classification to DDTopicResolver

- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
Fixes GH-2118
The logic introduced to stop endless loops in DLPR processing for fatal exceptions interferes with RT's single-topic strategy.
Make it optional and set the default to false in DLPRF for RT.
The loop is now addressed in DefaultDestinationTopicResolver as in GH-2113.
> GH-2118: Make DLPR skip same topic fatal ex optional

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
Resolves GH-2117
In order to make keeping this class' APIs compatibility easier in the future, I reviewed the methods signatures to future proof them. I've been dealing a lot with that lately.
Basically what I did was pass the Configuration object around so all methods have access to it when we add new features, without having to deprecate or overload them. I actually have one feature in mind that would require this soon.
The public method I renamed is from my previous PR and hasn't been released yet, so I hope that's ok.
I acknowledge that this may be too much for a quick review - I'm ok with only opening up the ctor and leaving the visibility opening / refactor for the next version and can provide a PR with that if that's the case.
Of course, if you think it's better to just open up the …
> GH-2117: Make ListenerContainerFactoryConfigurer ctor public

- spring-kafka/src/main/java/org/springframework/kafka/listener/ExceptionClassifier.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ExceptionClassifierTests.java
Option to not retry by default and retry specific exception(s).
Preparation for https://github.com/spring-projects/spring-kafka/pull/2124
> ExceptionClassifier Reverse Option

- spring-kafka-docs/src/main/asciidoc/index.adoc
- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/support/CompositeProducerInterceptor.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
Allow producer interceptors to be managed by Spring so that
they can be used in KafkaTemplate instead of providing the classname
of the interceptor to Kafka configuraiton.
Adding tests and docs.
Resolves https://github.com/spring-projects/spring-kafka/issues/2049
> GH-2049: Spring Managed Producer Interceptors

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ExceptionClassifier.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java
- spring-kafka/src/test/resources/log4j2-test.xml
Before we hardcoded a no-ops back off in the DefaultErrorHandler used in the Retryable Topics feature.
Adds a setter to let the user provide their own back off policy and configure blocking retries in conjunction with RT.
I also thought of making this configuration possible on a per-topic basis by adding it to the builder and annotation, but I think this is enough for this release since we won't have much time to review. We can open an issue for that if that's the case
and I can provide a PR soon.
> GH-2116: Add blocking retries to RT

- spring-kafka-docs/src/main/asciidoc/index.adoc
- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
Closes GH-2137
The wording in `@BackOff`'s maxDelay property's javadoc is a bit ambiguous. Clarify its default behavior in the Retryable Topic's documentation. Also a few smalls adjustments around that.
LMK if there's anything to change.
Thanks.
> Clarify ExponentialBackOffPolicy maxDelay default

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTypeSerializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/2140
Improve some internal code around generics in the `DelegatingByTypeSerializer`.
This allows us to use a dedicated external `Map` variable for the delegates
> GH-2140: Improve generics for DelegatingByTypeSer

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
StreamsBuilderFactoryBean needs a getter for StreamsUncaughtExceptionHandler.
> Add getter for StreamsUncaughtExceptionHandler

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
> GH-615: Docs - Migrating Legacy Error Handlers

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListener.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/AbstractKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaHeaders.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SimpleKafkaHeaderMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/SimpleKafkaHeaderMapperTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2134
Also clean up parsing of `errorHandler` and `contentTypeConverter`.
Add `info` property to `@KafkaListener`.
> GH-2134: Add filter to @KafkaListener

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
Partial solution for  https://github.com/spring-projects/spring-kafka/issues/2132
Allow the user to provide a function for formatting producer records.
Also move consumer record formatting to `KafkaUtils` will deprecate
`ListenerUtils` versions later.
There will be more polising in this area for 3.0 only (separate PR).
> GH-2132: Producer Record Log Formatting

- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/MicrometerHolder.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/MicrometerHolderTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2148
- use Boot's `AutoConfiguredCompositeMeterRegistry`, if only one
(tested with a Boot application)
- use `@Primary` registry bean
> GH-2148: Fix MeterRegistry Detection

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplateTransactionIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerRecordTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/pull/2133
Apply to 2.8.x, and 2.7.x.
In 3.0 they will be removed and `KafkaUtils` called directly instead.
> GH-2132: Deprecate ListenerUtils.recordToString

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2155
- Add a `BitSet` property to suppress individual standard headers
- Support multiple `headersFunction`
- Allow complete customization of exception headers
- Add `setHeadersFunction` to the DLPR factory for retryable topics
> GH-2155: DeadLetterPublishingRecoverer Improvement

- spring-kafka-docs/src/main/asciidoc/changes-since-1.0.adoc
- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2164#
> GH-2164: Remove EOSMode.V1

- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2179
**cherry-pick to 2.8.x; will back port to 2.7.x**
> GH-2179: Exit RetryingBatchErrorHandler on Stop

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2178
The wrong collection was used as the source for the `assignments` map,
`SeekPosition.BEGINNING` and `.END` entries are removed; use the
`definedPartitions` field instead.
> GH-2178: Fix CSA.onPartitionsAssigned (Manual)

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
The title for the Blocking / Non-blocking features combination was not properly capitalized in the docs.
> GH-2182 - Capitalize title in docs

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
Fixes #2184
I also looked into leveraging `KafkaException`'s self logging features here, but in order for it to work we'd need to make a few adjustments to `KafkaMessageListenerContainer#decorateException`, and that looks like too much change for a bugfix to me.
I still think we could have some configurable feature where a `KafkaException` could look into its causes, and use the deepest KE log level to self log. This way we could for example throw the original `KafkaBackOffException` as `DEBUG` (or what the user configures), and leave all other exceptions as `ERROR` (or what the user configures), and no matter how many wrappings it goes through it'd still be logged as `DEBUG`.
Not sure if that's something that would be useful for scenarios other than KBE though.
Please let me know if …
> GH-2184 KafkaBackOffException logged as ERROR

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2197
When a container is stopped due to any fatal error, `isInExpectedState()`
should return false.
> GH-2197: Fix Container State After Fatal Stop

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecordInterceptor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackRecordTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2208
`equals()` test on `ConsumerRecord` fails (not implemented).
Compare topic, partition and offset instead.
**cherry-pick to 2.9.x, 2.8.x, 2.7.x**
> GH-2208: Fix Manual Nack with Mutating Interceptor

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java
- Fixes [GH-2218](https://github.com/spring-projects/spring-kafka/issues/2218)
-  Useful when you want to pass an AdminClient that has already
been initialised with specific properties to connect to the cluster
e.g. SSL properties.
> GH-2218 add ability to pass AdminClient

- spring-kafka/src/main/java/org/springframework/kafka/listener/TimestampedException.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/KafkaBackoffAwareMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolverTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2212
As in normal `Retry Topic` flow recovery is always successful, the exception thrown by the listener is never logged.
Now such exception is logged at `DEBUG` level for intermediate retries and `ERROR` level when retries are exhausted.
Produces messages such as:
For intermediate retries:
```log
2022-04-05 20:37:36,713 DEBUG [org.springframework.kafka.KafkaListenerEndpointContainer#1-retry-500-0-C-1] [org.springframework.kafka.retrytopic.DeadLetterPublishingRecovererFactory] - Error processing record: topic = myRetryTopic2-retry-500, partition = 0, offset = 0, main topic = myRetryTopic2 at topic myRetryTopic2-retry-500. Sending to retry topic myRetryTopic2-retry-1000.
```
For messages heading to a DLT:
```log
2022-04-05 …
```
> GH-2212: Log listener exception in retry topic flow

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2222
Re-pause any paused partitions that are re-assigned after a rebalance,
Remove any partitions that are revoked and not re-assigned from the
paused partitions collections (pause requests and actually paused).
> GH-2222: Re-Pause Paused Partitions After Rebal.

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonMixedErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonMixedErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksBatchAckTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksBatchListenerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksRecordAckTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerRecordTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2195
Add an option to avoid seeks after handling exceptions.
Instead, pause the consumer for one `poll()` and use the remaining records as the
result of that poll.
New methods on `CommonErrorHandler` - `handleOne` for record listeners, returning
a boolean to indicate whether the record was recovered and should not be redelivered.
`handlaBatchAndReturnRemaining` for batch listeners, returning either the complete
set or a subset, e.g. when the `DEH` receives a `BatchListenerExecutionFailedException`
and commits a partial batch.
Also includes the classifier refactoring discussed here
https://github.com/spring-projects/spring-kafka/pull/2185#issuecomment-1078259823
The new logic is disabled by default, we can consider enabling it …
> GH-2195: DefaultErrorHandler Improvements

- publish-maven.gradle
Turns out Gradle 7 can run independent tasks in parallel.
* Make an `artifactoryPublish` dependent on `build` task
to ensure that tests are performed before artifacts are published
to the repository
**Cherry-pick to `2.9.x` & `2.8.x`**
> Make `artifactoryPublish dependsOn build`

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolver.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DefaultDestinationTopicResolverTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2172
* Add methods to `DestinationTopicContainer` interface
* Reduce memory footprint of `DefaultDestinationTopicResolver`
* Add documentation
This has been ready for quite a while and I was only waiting for us to solve the dependency injection issue to push it. Pretty much only exposed logic that was already there and renamed a few methods accordingly.
Also, there was a `Map` in `DefaultDestinationTopicResolver` that wasn't necessary, so I removed it.
Please let me know if there's anything to be changed.
Thanks.
> GH-2172: Expose Retry Topic Chain at Runtime

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/Acknowledgment.java
See https://github.com/spring-projects/spring-kafka/issues/2128
> GH-2128: Document Nack Sleep Time Limitations

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultListenerMetadata.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/OffsetAndMetadataProvider.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ListenerUtilsTests.java
Remarks:
- Every OffsetAndMetadata are now created using the provider if available. 
- Listener info has been added to the MessageListener container interface.
- Code related to the provider has been refactored and simplified.
- Javadoc has been reviewed.
- Updated the CommitProperties documentation
Closes #2252
> GH-2252: Keep offset metadata in case of batch reprocessing

- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2269
- add getters for fields used in protected methods
- change more methods to protected
**Cherry-pick to 2.9.x, 2.8.x, 2.7.x**
If it doesn't cherry-pick cleanly, I will back-port.
> GH-2269: Improve DLPR Extensibility

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/Acknowledgment.java
Prior to, it was required to dig a few levels into to realize they are in millis.
I'm not satisfied with the new names of the field, but I wanted to express that `nackSleep` is a duration and `nackWake` is a point of time (the same as `currentTimeMillis()`). Nevertheless, as they are used internally, it might be sufficient to just change `sleep` to `sleepMillis` in the method argument (+ change the javadoc).
`java.time.Duriation` in the `Acknowledgment` class would be probably better, however, it is a non-backward compatible change.
> Precise unit for sleep duration and wake time

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2295
A subclass of `InvocableHandlerMethod` was used to signal that a method
needs a `ConsumerRecordMetadata` to be constructed.
However, the constructor that takes an existing IHM, does not fully clone
the argument passed into it.
Then, the payload resolver was not invoked to resolve that parameter.
Use a map of booleans instead, to signal the creation of the metadata.
**cherry-pick to 2.9.x, 2.8.x, 2.7.x**
> GH-2295: No Resolvers with ConsumerRecordMetadata

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/Acknowledgment.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackBatchTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackBatchTxTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackPauseResumeTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackRecordTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackRecordZeroSleepTests.java
To prevent confusion what unit should be used for "long sleep" arguments.
As the old and new methods in the Acknowledgment interface have default
implementations, the change itself is backward compatible.
The old methods are marked as deprecated and intended to be removed in the future.
I wonder, if we should also test old, deprecated methods. On one hand, they should be to "ensure" they still work fine. On the other hand the logic there is rather obvious and covering them would probably duplicate 2 tests. WDYT?
An extension to #2278.
> Add Acknowledgment.nack() variants accepting Duration

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2297
Add an option to apply `autoStartup` semantics to late registrations.
> GH-2297: Add KLERegistry.alwaysStartAfterRefresh

- spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2304
`@SendTo` was only detected on the concrete listener method.
Use `AnnotatedElementUtils.findMergedAnnotation()` instead.
> GH-2304: Fix SendTo on Interface Etc.

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/SerializationUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2306
Include the original exception message in the `DeserializationException.cause`
when the original exception could not be serialized.
> GH-2306: Improve DeserEx Message For Improper Ex.

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerSeekAfterCommitException.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerSeekAfterCommitExceptionBatchAck.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerSeekAfterCommitExceptionBatchAckTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerSeekAfterCommitExceptionBatchListenerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerSeekAfterCommitExceptionTests.java
- Revert to seeking when `CommitFailedException` - due to a rebalance
- For batch listeners, move committing to the try block
- For record listeners, `AckMode.RECORD` already commits in the try block
- With `AckMode.BATCH`, detect a no-seek retry and call the error handler `handleRemaining`
> GH-2195: Fix No Seek Retry Mode

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicNamesProviderFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/SuffixingRetryTopicNamesProviderFactory.java
> Use KafkaListenerEndpoint instead of MethodKafkaListenerEndpoint in the RetryTopicNamesProvider

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2318
Add an option to wait for assignment to the `ReplyingKafkaTemplate`; useful
when using `auto.offset.reset=latest` to avoid sending a request with the reply
sent before the container is initialized.
> GH-2318: ReplyingKT - Wait for Assignment

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerRetryAuthSuccessfulEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
* Added Events for auth failed
and successful retry of auth
* publish of these events
* unit testing
Closes #2284
> GH-2284: Publish Auth Error Events

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksRecordAckNoResumeTests.java
Related to https://github.com/spring-projects/spring-kafka/issues/2195
Do not process the remaining records if the first record is from a
paused partition.
> GH-2195: Fix No Seek Retries with Non-Blocking

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Related to https://github.com/spring-projects/spring-kafka/issues/2195
- check `isPartitionPauseRequested()` instead of `isPartitionPaused()`
- add diagnostic debug logging
- prevent re-pausing the entire consumer each time a poll exits but the first
partition is still paused.
> GH-2195: Polishing

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2329
The flag should apply, regardless of PTM type.
**cherry-pick to 2.9.x,**
> GH-2329: Fix interceptBeforeTx for Non-Kafka TM

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksRecordAckNoResumeContainerPausedTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksRecordAckNoResumePartitionTests.java
Related to https://github.com/spring-projects/spring-kafka/issues/2195
Similar to the recent fix when the first partition is paused, we should
not continue to process the remaining records if the container itself
was paused during the poll after an error occurred with `seekAfterError=false`.
> GH-2195: Fix Fix No Seek Retries with Pause

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/PauseContainerManualAssignmentTests.java
- spring-kafka/src/test/resources/log4j2-test.xml
Resolves https://github.com/spring-projects/spring-kafka/issues/2332
Use manual assignments, if present for pause.
Also, in the rebalance listener, use `isPaused()` rather than `consumerPaused`
to determine whether the partitions should be paused.
Add logs and events for pauses in the rebal listener.
> GH-2332: Fix Container.pause() with Manual Assign.

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FallbackBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2340
The `RetryingBatchErrorHandler` - now called the `FallbackBatchErrorHandler`
pauses and resumes the consumer during retries, to allow it to poll the
consumer to avoid a forced rebalance.
However, if a normal rebalance occurs, for example if a new member joins,
the error handler does not re-pause the consumer and silently consumes
new records.
Add a mechanism to always re-pause the consume when in this retry mode.
As well as the unit test, tested proper functionality by running two copies of a Boot app.
> GH-2340: Fix Retrying Batch Error Handling

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractKafkaBackOffManagerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerPartitionPausingBackOffManagerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicBeanNames.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicComponentFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupport.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupportTests.java
See https://github.com/spring-projects/spring-kafka/issues/2239
The previous commit removed the implicit bootstrap in favor of enforcing the
user to use the `@EnableKafkaRretryTopic` or explicitly extend
`RetryTopicConfigurationSupport`.
Unfortunately, this breaks Spring Boot because it can auto configure a
`RetryTopicConfiguration` bean, which means the infrastructure beans are required.
Fallback to late binding of the infrastructure beans if a `RetryTopicConfiguration`
bean is found in the application context.
Tested with a Boot app.
**cherry-pick to main**
> GH-2239: Fix Boot AutoConfiguration

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2345
I haven't been able to reproduce it since, but I saw one occasion where
the existing config property returned null.
Protect against an NPE in that case and add the property to the change
candidates.
Also move the map entry out of the for loop.
> GH-2345: Fix Possible NPE in KafkaAdmin

- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2344
The `ReplyingKafkaTemplate` supports the use of a custom header name
for correlation, but the subclass `AggregatingReplyingKafkaTemplate`
was hard coded to use the default header.
Support the use of a custom header name in the subclass.
> GH-2344: AggReplyingKT Support Custom Correlation

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2350
Do not maintain the `pausePartitionsRequested` field in the concurrent MLC,
it is not used and can cause confusion.
Also fixes some synchronization around `CMLC.containers`.
Also resolves https://github.com/spring-projects/spring-kafka/issues/2222
The previous fix removed revoked partitions from `pausePartitionsRequested`;
this was incorrect - consider a rebalance where we lose `topic-0` and another
rebalance where we are re-assigned `topic-0`. According to the contract, this
partition should remain paused.
> GH-2350: Fix Paused Partitions After Rebalance

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaListenerErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ManualAckListenerErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RecordMessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ListenerErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2355
> GH-2355: Add ManualAckListenerErrorHandler

- spring-kafka-docs/src/main/asciidoc/changes-since-1.0.adoc
- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations2.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/RequestReplyFuture.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/RequestReplyMessageFuture.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/RequestReplyTypedMessageFuture.java
- spring-kafka/src/main/java/org/springframework/kafka/support/SendResult.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerBatchIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2357
Spring Framework is planning to deprecate `ListenableFuture` in 6.0.
Add methods to the `KafkaOperations` (`KafkaTemplate`) that return
`CompletableFuture` instead; the `ListenableFuture` methods have now
been removed in 3.0.
> GH-2357: Switch to CompletableFuture

- spring-kafka-test/src/main/java/org/springframework/kafka/test/junit/GlobalEmbeddedKafkaTestExecutionListener.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/junit/GlobalEmbeddedKafkaTestExecutionListenerTests.java
The `EmbeddedKafkaBroker.brokerProperties(brokerProperties)` does not accept a `null`.
* Fix `brokerProperties` map extraction for a `.orElse(Map.of())` instead of `null`
* Modify `GlobalEmbeddedKafkaTestExecutionListenerTests` to ensure that `brokerProperties`
are covered both ways - present and missed
> Fix NPE in Global Embedded Kafka

- build.gradle
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/RoutingKafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2357
**main only; will issue separate PR to deprecate setters in 2.9**
> GH-2357: Remove Remaining Uses of ListenableFuture

- build.gradle
- spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaAvroBeanRegistrationAotProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHintsRegistrar.java
- spring-kafka/src/main/java/org/springframework/kafka/aot/package-info.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/resources/META-INF/spring/aot.factories
Resolves https://github.com/spring-projects/spring-kafka/issues/2359
This is sufficient for the basic Kafka smoke test.
I will issue another PR if changes are needed for the Streams and Avro versions.
I have a `KafkaAvroBeanRegistrationAotProcessor` but I have omitted it from
this commit because it hasn't been tested.
> GH-2359: Initial AOT Support for Native

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/dynamic/Application.java
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/dynamic/MyListener.java
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/dynamic/MyPojo.java
- spring-kafka-docs/src/main/kotlin/org/springframework/kafka/kdocs/dynamic/Application.kt
- spring-kafka-docs/src/main/resources/logback.xml
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaListenerEndpointRegistryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2375
Also add docs for creating dynamic listener containers.
> GH-2375: Add KLER.unregisterListenerContainer

- spring-kafka-docs/src/main/asciidoc/changes-since-1.0.adoc
same as #2384
(https://docs.spring.io/spring-kafka/docs/3.0.0-SNAPSHOT/reference/html/#x29-lc-changes)
> Fix typo in changes-since-1.0.adoc

- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
Can't move to table row "interceptBeforeTX" because there  is a wrong letter case.
I changed the capital letter "X" to lowercase in `whats-new.adoc`.
(https://docs.spring.io/spring-kafka/reference/html/#x29-lc-changes)
> Fix typo in whats-new.adoc

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPausedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FallbackBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualNackPauseResumeTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2387
- `FallbackBatchErrorHandler`
- `Acknowledgment.nack()`
**2.9.x only - I will back port/forward port**
> Add Missing Pause/Resume Events

- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2184
`KafkaBackOffException`s are incorrectly logged at ERROR level during
retries when using the no-seek error handling mode.
They are not logged in the seek mode; see
https://github.com/spring-projects/spring-kafka/commit/448871ac6529a45f4d54f837d370696c76705191
> GH-2184: Don't Log KafkaBackoffException

- build.gradle
- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/DefaultKafkaListenerObservationConvention.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/DefaultKafkaTemplateObservationConvention.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaListenerObservation.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaListenerObservationConvention.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaRecordReceiverContext.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaRecordSenderContext.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaTemplateObservation.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaTemplateObservationConvention.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2198
> GH-2198: Spring Observability Initial Commit

- spring-kafka/src/main/java/org/springframework/kafka/requestreply/CorrelationKey.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/CorrelationKeyTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2400
Use a hex string instead of a `BigInteger` in `toString`. Also, if the bytes are the length of a UUID, use the standard representation thereof.
> GH-2400: ReplyingKT Improve CorrelationId Logging

- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2399
By default, the correlationId header contains a binary representation of a UUID; add an option to use a String representation instead.
> GH-2399: ReplyingKT Human Readable Correlation

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RetryListener.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerBatchTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2395
Previously, `RetryListener` only supported record listeners; add methods for retrying batches.
> GH-2395: RetryListener - Add Batch Methods

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2348
The replying template supports a custom header for correlation for cases when the consumer side is not a Spring app and uses a different header.
Support a custom header name on the consumer side, for cases where the client side is not Spring and uses a different header.
> GH-2348: Custom Correlation Consumer Side

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/2415
> GH-2415: Doc for DeserializationEx... with DLPR

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerPauseResumeEventPublisher.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2387
Events were not published for `ConcurrentMessageListenerContainer`s.
Also resolves a class tangle in https://github.com/spring-projects/spring-kafka/issues/2417 between `ErrorHandlingUtils` and KMLC.
> GH-2387: Fix FallbackBatchErrorHandler Events

- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2419
We try to obtain the configured request timeout using the producer factory's configuration properties. Some wrappers (e.g. open tracing) do not implement this method, so fallback to the default instead of throwing an USOE.
> GH-2419: DLPR: Protect Against Non-Compliant PF

- build.gradle
- spring-kafka-docs/src/main/asciidoc/appendix.adoc
- spring-kafka-docs/src/main/asciidoc/quick-tour.adoc
- spring-kafka-docs/src/main/asciidoc/streams.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
- spring-kafka/src/main/java/org/springframework/kafka/streams/HeaderEnricherProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/streams/messaging/MessagingProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/HeaderEnricherProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/messaging/MessagingProcessorTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2423
Upgrade Apache Kafka version to 3.3.1.
Migrate transformers to the new processor API.
> GH-2423: Upgrade to Kafka 3.3.1, Streams Proc. API

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2430
Do not obtain the clusterId unless explicitly needed for observation.
> GH-2430: Fix Unnecessary describeCluster()

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/TopicForRetryable.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2432
Don't provision an individual retry topic bean, if there is already a `NewTopic` bean with the same topic name.
> GH-2432: Fix Retryable Topic Provisioning

- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
This PR resolves #2435 
With this change we will be able to create new annotations, meta-annotated with `RetryableTopic`. This makes it possible to share the same configurations from a `RetryableTopic` annotation across multiple `KafkaListener` annotated methods, making configuration details transparent, reducing boilerplate.
> Add meta-annotation support to RetryableTopic

- build.gradle
Replace the usage of deprecated `micrometer-docs-generator-[metrics|spans]` to the new `micrometer-docs-generator`.
Migration doc: https://github.com/micrometer-metrics/micrometer-docs-generator/wiki/1.0.0-Migration-Guide
> Update the usage of micrometer-docs-generator

- .github/workflows/central-sync-close.yml
- .github/workflows/central-sync-create.yml
- .github/workflows/central-sync-release.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2451
Classes with class level `@KafkaListener` were incorrectly added to the `nonAnnotatedClasses` set, preventing multiple instances of the same class to be registered as listeners.
> GH-2451: Fix Class Level Listener Multi Instances

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2443
Optionally configure a different concurrency for retry containers.
> GH-2443: Distinct Concurrency for Retry Containers

- spring-kafka/src/main/java/org/springframework/kafka/listener/ExceptionClassifier.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupport.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupportTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2457
Previously, classifying `RuntimeException` either for no retries or for blocking retries would cause undesirable effects - its classification would be found first because the classifier first traverses up the class hierarchy to find a match before traversing down the cause links.
When classifying exception for retry, unwrap the 'LEFE' cause from a `TimestampedException` and/or `ListenerExecutionFailedException` so that the classification is made on that cause.
By default, the retry classifier has no classified exceptions when used in "classify for retry" mode (instead of the default "classify for no retry" mode). This means that, if `retryOn(RuntimeException.class)` is used, then all `RuntimeException`s will be retried …
> GH-2427: Allow RuntimeException to be Classified

- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ExceptionClassifier.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FallbackBatchErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerBatchTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2459
The `FallbackBatchErrorHandler` was not an `ExceptionClassifier`. The default error handler should propagate exception classifications.
**3.0.x - I will back port**
> GH-2459: FallbackBatchErrorHandler Retryable Ex

- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Additional Support of SpEL for listenerContainerFactory and kafkaTemplate properties.
The main work has been done here - https://github.com/spring-projects/spring-kafka/pull/1722, and that's great, but listenerContainerFactory and kafkaTemplate still can not be used from properties or SpEL, when JavaDoc says "All String properties can be resolved from property placeholders".
> @RetryableTopic Additional Support of SpEL

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeliveryHeaderTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2464
`KafkaBackoffException` should never be classified as retryable; the design is such that those exceptions go straight to the recoverer, which will re-throw.
If, however, a user configures a super class as retryable (e.g. `RuntimeException`) then its classification wins.
This causes a new retry state (`FailedRecord`) to be started, causing an incorrect value of 2 instead of 1 on the first delivery from a retry topic.
**I will backport - conflicts expected**
> GH-2464: Fix Delivery Attempt Header (Rare)

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingCoverageTests.java
To adjust codebase to modern JVM (and Kafka API itself - e.g. poll(Duration)). I've just bumped into that writing some tests recently. Old methods with "long timeout" are marked as deprecated and removed in separate commit.
A variant for 2.9. Methods are removed in PR for 3.x - https://github.com/spring-projects/spring-kafka/pull/2467.
> Add KafkaTestUtils methods using Duration for timeout (2.9)

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/utils/KafkaTestUtilsTests.java
To adjust codebase to modern JVM (and Kafka API itself - e.g. `poll(Duration)`). I've just bumped into that writing some tests recently. Old methods with "long timeout" are marked as deprecated and removed in separate commit.
It seems to be still a good moment before 3.0-final.
Btw, a PR for 2.9.x will be created with just method deprecation without the method removal.
> Add KafkaTestUtils methods using Duration for timeout

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
`ObservationRegistry` cannot be null; current code uses `ObjectProvider.getIfUnique()`, which can return null.
In those cases, use the default NOOP registry.
> Fix Get ObservationRegistry

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilderTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2471
Set the default to -1 (use broker default).
> GH-2471: RetryableTopic Default Replication Factor

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Sonar:
Collection.isEmpty() should be used to test for emptiness (java:S1155)
CODE_SMELL_MINOR
Using Collection.size() to test for emptiness works, but using Collection.isEmpty() makes the code more readable and can be more performant. The time complexity of any isEmpty() method implementation should be O(1) whereas some implementations of size() can be O(n).
Also
"Stream.toList()" method should be used instead of "collectors" when unmodifiable list needed (java:S6204)
CODE_SMELL_MAJOR
In Java 8 Streams were introduced to support chaining of operations over collections in a functional style. The most common way to save a result of such chains is to save
them to some collection (usually List). To do so there is a terminal method collect
that can be used with a library of Collectors. The …
> Use isEmpty() Instead of size(); toList()

- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupport.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupportTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicSameContainerFactoryIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2478
Allow users to define a `RetryTopicComponentFactory` bean for use in infrastructure bean definitions.
Previously, although `createComponentFactory()` can be overridden, it is called early in the class lifecycle and can't have any dependencies on Spring beans.
Now, if the application context contains a unique bean of this type, it is used instead.
**Cannot back port due to breaking API changes; work around for 2.9.x is to override one or more of `destinationTopicResolver`, `kafkaConsumerBackoffManager` and/or `retryTopicConfigurer` bean definition methods.**
> GH-2478: Improve `RetryTopicComponentFactory` Conf

- spring-kafka-docs/src/main/asciidoc/testing.adoc
- spring-kafka-test/src/main/java/org/springframework/kafka/test/junit/GlobalEmbeddedKafkaTestExecutionListener.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2481
The Maven Surefire plugin uses an older version of JUnit platform which is incompatible with the Global embedded broker.
Check that the platform version is compatible before attempting to determine if a global embedded broker should be created.
Tested with a Spring Boot application.
> GH-2481: Global Embedded Broker and JUnit Platform

- build.gradle
- spring-kafka-docs/src/main/asciidoc/testing.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/2490
The new global embedded kafka broker depends on the JUnit platform launcher. With gradle, the launcher must be on the test runtime class path. Add the launcher as a transitive dependency.
Tested with gradle and maven Boot apps.
> GH-2490: Add JUnit Platform Test Dependency

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2501
> GH-2501: Add Option to Set Consumer Thread Name

- samples/sample-01/pom.xml
- samples/sample-01/src/main/java/com/example/Application.java
- samples/sample-02/pom.xml
- samples/sample-02/src/main/java/com/example/Application.java
- samples/sample-03/pom.xml
- samples/sample-03/src/main/java/com/example/Application.java
- samples/sample-04/pom.xml
- samples/sample-05/pom.xml
Resolves https://github.com/spring-projects/spring-kafka/issues/2508
> GH-2508: Upgrade Samples to 3.0.x

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2505
When observation is enabled, we use the context's `KafkaAdmin`, if present, to determine the cluster id.
The context's admin may be configured with different bootstrap servers than the producer/consumer (e.g. in Spring Cloud Stream).
When looking up the cluster id for observation, use the appropriate bootstrap servers for the component.
> GH-2505: Use Correct Brokers for Cluster Id

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2521
The `__listener` pseudo bean name is not available for bean resolution in the `@KafkaListener.id` attribute.
> GH-2521: Fix `__listener` in `id` Regression

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2528
When adding headers in a DLPR headers function, header values accumulate because Kafka headers support multiple values.
Provide a mechanism to allow adding a header to replace any existing header with that name.
> GH-2528: DLPR - Support Header Replacement

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2525
If a paused partition is revoked and re-assigned during a retry topic pause delay, the partition is not resumed because it no longer exists in the `pausedPartitions` field.
When re-pausing a paused partition, it must be re-added to the paused partitions so that it will not be filtered out of the resume logic.
> GH-2525: Fix Paused Partition Resume (Rebalance)

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
Compare https://github.com/spring-projects/spring-kafka/issues/2515
With only EOSMode v2 supported, the alternative way of `transactional.id` creation is not used anymore and not needed anymore. This PR removes the outdated (and confusing) extra documentation in the overview section for transactions.
> Remove outdated information for transactional.id

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2538
The `KafkaTemplate` already has code to lazily fetch the cluster id when first needed. Remove the eager fetch in `afterSingletonsInstantiated`.
Also, when creating a new `KafkaAdmin` propagate the `operationTimeout` from the source admin (in both the template and listener container).
> GH-2538: KafkaTemplate - Fix Eager Init Cluster Id

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedBatchProcessorTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2558
If a user throws a `BatchListenerExcecutionFailedException` with an invalid `index`, an NPE is logged instead of the true error.
> GH-2558: Fix Possible NPE in FailedBatchProcessor

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2565
Previously, when a partition was resumed while not currently assigned, it would be paused indefinitely when reassigned.
This was caused by the `ConcurrentMessageListenerContainer` only resuming partitions in child containers if that partition is currently assigned to the container, leaving the pause request in place.
Use the `isPartitionPauseRequested()` method on the child container instead when deciding whether to resume the partition.
> GH-2565 Fix Resume Partition When Unassigned

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/BatchAdapterConversionErrorsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2566
Now that both batch and record listners can be created by a single factory, it should be possible to configure both a `RecordMessageConverter` and `BatchMessageConverter`.
Previously, only a single `MessageConverter` could be configured.
> GH-2566: Both Converters in Container Factory

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2576
When the error handler `seeksAfterError` is false, we keep the unprocessed records in memory (`retainedRecords`), pause the consumer, and attempt redelivery.
If a rebalance occurs during this state, the behavior depends on whether a legacy or cooperative partition assignor is used.
With a legacy assignor, all partitions are unassigned and usually a subset is reassigned. This causes their positions to be reset to the last committed offset. In this case, all retained records must be cleared, otherwise an emergency stop occurs because records are polled when we don't expect them.
With a cooperative assignor, only a subset of the partitions are revoked. Records for these partitions must be pruned from the `retainedRecords` …
> GH-2576: Fix No Seeks After Error Handling

- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/kotlin/org/springframework/kafka/core/KotlinProducerFactoryTests.kt
Resolves: #2583
ProducerFactory.createProducer argument txIdPrefix is non-nullable which causes kotlin compiler to emit warning if implementations declare txIdPrefix as nullable txIdPrefix: String?
This PR changes signature of ProducerFactory.createProducer so that `txIdPrefix` is `@Nullable` and also adds unit test to verify compilation, and to verify that future versions of Kotlin won't cause compile errors.
Current users of kotlin who implemented ProducerFactory.createProducer(txIdPrefix) with `txIdPrefix: String` (non-nullable) will start seeing kotlin compiler warning that their signature is not matching base signature.
> GH-2583 ProducerFactory.createProducer argument @Nullable

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2581
If a rebalance occurred while pending out of order commits were present, the pending commits were correctly purged, however, the `consumerPaused` boolean remained true.
This prevented the consumer from being paused again while the next batch of records is being processed and subsequent polls returned more records.
Reset the `consumerPaused` boolean when all pending commits are purged.
Also, with a cooperative assignor, ensure that any newly assigned partitions are paused if pending commits are present.
Add tests to verify the correct behavior with a legacy and cooperative assignor.
Also tested with the reporter's reproducer.
> GH-2581: Fix OOO Commits with Rebalance

- spring-kafka-test/src/main/java/org/springframework/kafka/test/junit/GlobalEmbeddedKafkaTestExecutionListener.java
Fixes https://github.com/spring-projects/spring-kafka/issues/2582
Even if we don't use Embedded Kafka in native image or even if Apache Kafka broker (or Zookeeper) is not compatible, the `GlobalEmbeddedKafkaTestExecutionListener` is still service-loaded by JUnit platform and according to build time some classes (`Logger`) are initialized too early
* Refactor `GlobalEmbeddedKafkaTestExecutionListener` to initialize `Log` property and check for `TestPlan.getConfigurationParameters()` method lazily already in the `testPlanExecutionStarted()`
> GH-2582: GlobalEmbedKafka compatible with native

- README.md
Added getting support in README.md
> Added getting support in README.md

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonLoggingErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerPauseImmediateTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksBatchAckTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksRecordAckNoResumeContainerPausedTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksRecordAckNoResumePartitionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksRecordAckTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/LoggingErrorHandlerNoPauseAfterHandle.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/LoggingErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/PauseContainerManualAssignmentTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2596
- Do not pause and poll when an error handler "handles" an error
- this was a bug in that the remaining records were incorrectly built after the error handler indicated that it had handled the error
- Reduce the poll timeout while the consumer is paused because we won't receive any records anyway
> GH-2596: Fix No Seek Error Handling

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopic.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactoryTests.java
Resolve https://github.com/spring-projects/spring-kafka/issues/2377
`DestinationTopic.Properties` has `isDltTopic()` and `isMainEndpoint()` but not for retry topic. It adds `isRetryTopic()` method and adds tests to verify the correct behavior.
* Add `isRetryTopic()` instance method to `DestinationTopic.Properties`
> GH-2377: Add DestinationTopic.Properties#isRetryTopic()

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2600
Also reproduced in Java with
@KafkaListener(id = "kgh2600", topics = "kgh2600", batch = "true")
void listen(List<? extends Message<?>> in) {
System.out.println(in);
}
MMLA did not handle a `WildcardType` as the list element type.
Also tested with reporter's Kotlin reproducer.
**cherry-pick to 2.9.x** (pattern matching instanceof will need to be changed)
> GH-2600: Fix Kotlin Listener List<Message<*>>

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonContainerStoppingErrorHandler2Tests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2612
Add a container property to enable restarting the container after an emergency stop due to authentication/authorization exceptions, perhaps due to credentials expiring.
> GH-2612: Add Option To Restart Container After Auth

- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FallbackBatchErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2620
Previously, if a not-retryable exception is thrown during batch retry, after a retryable exception, it was not reclassified and retries continued.
Also use the last thrown exception to the recoverer.
**cherry-pick to 2.9.x - will need work on instanceof pattern matching**
> GH-2620: FallbackBatchErrorHandler Reclassify Ex

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2627
Introduced by https://github.com/spring-projects/spring-kafka/commit/73bee667dbaabca11ceee22a8d70b09934932d5f
Remove the synchronization; it was added because an earlier implementation referenced `containers` which can only be used under the lock. When the implementation changed, I failed to remove the unnecessary sync.
> GH-2627: Deadlock on lifecycleMonitor Regression

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2641
Need to traverse the cause tree to find the actual user exception.
Also tested with reporter's reproducer.
> GH-2641: Fix Exception Change with RetryableTopic

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/MicrometerHolder.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2638
TODO: Support for Observations when `observationEnabled` (3.0.x only).
> GH-2638: Add Dynamic Micrometer Tags

- spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
Description:
While registering native hints for Spring Kafka project `KafkaOperations.class` and `ImplicitLinkedHashCollection.Element.class` is specified twice.
> Remove duplicate native hint registration.

- spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
Hey, sorry for one small PR again. I noticed one more duplicate.
`KafkaListenerEndpointRegistry.class` is specified above with categories that include more than one from where I removed it.
```
builder -> builder.withMembers(MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
MemberCategory.INVOKE_DECLARED_METHODS,
MemberCategory.INTROSPECT_PUBLIC_METHODS))
```
> Remove duplicate from KafkaRuntimeHints

- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
When timers have dynamic tags, creation of the timers is deferred until the first completion of a timer with a set of tag values.
Use awaitility to wait for the timer to be created before checking the count.
> Fix Race in Micrometer Test

- spring-kafka-docs/src/main/asciidoc/tips.adoc
> Howewever -> However

- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2671
With Spring Framework 6, `NestedRuntimeException.getMessage()` no longer includes the messages for nested exceptions via the cause chain.
See https://github.com/spring-projects/spring-framework/issues/25162
This means that the DLQ exception message header always contains the same `Failed listener` message.
Find the root cause exception and include its message in the header. Ignore any nested `TimestampedException` and `LEFE` between the top `LEFE` and the root cause; these will still appear in the stack trace.
> GH-2671: Improve DLQ Exception Message Header

- spring-kafka-docs/src/main/asciidoc/testing.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/mock/MockConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/mock/MockProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/mock/package-info.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/MockConsumerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2673
Also remove an unnecessary call to `offsetsForTimes` which is not supported by `MockConsumer`.
> GH-2673: Add Mock Consumer and Producer Factories

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerAwareRebalanceListener.java
As a user, I do not want my exception be effectively ignored by framework by logging them on debug level
> Expose user exception thrown during rebalance

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/AsyncAckAfterHandleTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2677
When an error handler handles an error (and `ackAfterHandle` is true), the ack bypassed the out of order commit logic, causing the consumer to be paused indefinitely, due to the missing ack.
> GH-2677: Fix EH AckAfterHandle With Async Acks

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
There are two forms of method representation in the documentation.
- `methodName()`
- `.methodName()`
I think that `methodName()` is the commonly used form in this documentation.
How about replacing `.methodName()` to `methodName()` in this documentation.
> replace `.methodName()` with `methodName()` in documentation

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
Fixes a method name in retry-topics docs.
The method to override for managing fatal exceptions is called  `manageNonBlockingFatalExceptions` and not `manageNonBlockingRetriesFatalExceptions`.
> docs: fix name of overriden method

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
The doc suggests that the default value of this method is false, even though it's actually true.  Update the doc to match the code.
> docs: fix Javadoc of CommonErrorHandler::remainingRecords

- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
The default behavior was to throw an `UnsupportedOperationException` which effectively makes the `MockProducerFactory` unusable without subclassing, e.g. in `spring-integration-kafka`, which calls that method to examine some properties.
Change the default behavior to return an empty map.
> Default Empty Map for PF configurationProperties

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
Resolves https://github.com/spring-projects/spring-kafka/issues/2699
`@RetryableTopic` is not supported with batch listeners.
> GH-2699: Document Retry Limitation

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/KafkaBackoffAwareMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/KafkaBackoffAwareMessageListenerAdapterTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2702
When using `asyncAcks` with manual ack modes, the `DefaultErrorHandler` must have `seekAfterError` set to `false`; this required user configuration.
The framework now unconditionally sets the property when it configures a container using a manual ack mode.
In addition, the default DLT handler was not compatible with any manual ack mode, regardless of the `asyncAcks` setting.
Add `Acknowledgment` to the `LoggingDltListenerHandlerMethod`.
Also tested with reporter's reproducer.
**cherry-pick to 2.9.x (will require instanceof polishing for Java 8)**
> GH-2702: RetryableTopic with asyncAcks

- spring-kafka-docs/src/main/asciidoc/retrytopic.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2711
Previously, it was not easy to provide custom DLPRs, for example to override `createProducerRecord`.
> GH-2711: Non-Blocking Retries and Custom Publisher

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
This PR fixes a minor typo in the docs: https://docs.spring.io/spring-kafka/docs/3.0.8/reference/html/#eh-summary.
Fixes #2716
> GH-2716: Fix minor typo in Handling Exceptions docs section

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2720
**cherry-pick to 2.9.x** (minor conflict on imports).
> GH-2720: Add Predicate to KafkaAdmin

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2723
Previously, it was possible for `handlerReturnsMessage` to return `null` when a `cachedHandlers` was present, causing an NPE when unboxing the `Boolean` value.
Ensure that the `handlerReturnsMessage` map is populated before adding the handler to `cachedHandlers`.
> GH-2723: Fix NPE in DelegatingInvocableHandler

- spring-kafka/src/main/java/org/springframework/kafka/listener/BatchInterceptor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecordInterceptor.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2722
Prior to 2.8.x, `interceptBeforeTx` was default `false`; it is now `true`. However, it should only be considered if there is a `TransactionManager` present.
This allows an interceptor (when no transactions) to throw an exception, causing error handling to be invoked.
Also tested with user's reproducer.
> GH-2722: Only Consider interceptBeforeTx with TX

- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingUtilsTest.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ListenerUtilsTests.java
Closes #2742 
Implementation is aligned with idea exit retrying as soon as possible if any of is true:
- container is not running anymore
- container is requested to pause
- retrying batch which has record from partition that container is requested to pause
Why I extracted ?
```java
static Runnable NO_OP = () -> {};
```
- To be able to verify arguments
- Named field stating intention
Why did I introduced new method?
```java
public static void stoppableSleep(Supplier<Boolean> shouldSleepCondition, long interval) throws InterruptedException
```
- At first it was tempting just to add `!container.isRunning() || container.isPauseRequested()` but not having access to retrying `ConsumerRecords` to check paused partitions
- Changing behaviour of public api seems like bad idea, and I believe …
> GH-2742: Exit batch retries when container is paused

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2744
Possible deadlock if `removeProducer` is called on the producer network thread.
Move resetting the global shared producer to the creation logic.
Also ensure the delegate of any thread-bound producers are closed.
Add try/catch around the delegate close.
> GH-2744: Fix Possible Deadlock in DKPF

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- move to `ErrorHandlingUtils` for reuse.
> Refactor DeserializationException Detection Code

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2760
> GH-2760: Add SmartLifecycle to Producer Factory

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka-docs/src/main/asciidoc/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/Acknowledgment.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ManualAckPartialBatchTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2066
Allow apps to commit partial batches.
> GH-2066: Partial Batch Acknowledgments

- spring-kafka-docs/src/main/asciidoc/kafka.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DeserializationExceptionHeader.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/SerializationUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/adapter/BatchAdapterConversionErrorsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/SerializationTestUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/SerializationUtilsTests.java
Use a package-private header for deserialization exceptions.
> Private Header Type for DeserializationExceptions

- build.gradle
- gradle.properties
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ListenerErrorHandlerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupportTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Also some test changes due to Spring, Kafka, Mockito changes.
> Move main to 3.1; Upgrade Depenency Versions

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FallbackBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConsumerSeekAwareTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedRecordTrackerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FallbackBatchErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2729
I considered making this optional but these are low contention uses and, for the most part, are not on the happy path.
> GH-2729: Avoid ThreadLocal

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2730
Use `ReentrantLock`s when I/O is possible to avoid unnecessary virtual thread pinning. Synchronized blocks to protect update to shared fields are ok.
> GH-2730: Avoid I/O in synchronized Blocks

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactory.java
So they can be removed in 3.1, along with `FixedDelayStrategy`.
> Deprecate DestinationTopicPropertiesFactory CTORs

- build.gradle
This sets the path sensitivity to relative for the `sourceDir` property of the `asciidoctorPdf` task. Previously, the full absolute path to the source directory would be considered as an input to the task. This would cause a local build cache miss when executing the task from two different directories or a remote build cache hit given that the paths to the sources directory on CI and for local developers will undoubtedly be different.
You can recreate this with the [Gradle Enterprise Build Validation Scripts](https://github.com/gradle/gradle-enterprise-build-validation-scripts) using the following command:
```shell
./03-validate-local-build-caching-different-locations.sh \
-r https://github.com/spring-projects/spring-kafka \
-t asciidoctorPdf \
-c d171f04ec88874db9d3385fc454a09a5a97dbacb …
```
> Output of `asciidoctorPdf` can be pulled from cache when run on machines with different checkout directories

- samples/sample-01/README.adoc
- samples/sample-03/README.adoc
- samples/sample-04/README.adoc
**Update Spring Kafak Sample 1, 3, 4, 5 .adoc**
Hello, I was looking at the Spring Kafka sample, and I was a little uncomfortable to see the sample outputting the application console of adoc. I modified it to look like a console screen.
Modified samples 1, 3, 4 and 5. If you think this is a good method, please consider it and make an approach
Thank you :)
> Update kafka sample adoc

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-config.adoc
Fixing a typo I saw while reading through docs
> Typo fix in retry-config.adoc

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/2817
An observation in `KafkaTemplate` can be marked with error from a `Callback`. Then `Future` is evaluated and its exception is thrown back to the `observeSend()`. Here this exception is caught and reported to the observation again. This creates a second timer in the Micrometer, but with different error tag
* Check for error presence in the `observeSend()` `catch` block and skip second report
**Cherry-pick to `3.0.x`**
> GH-2817: KafkaTemplate: No double error timers

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/junit/GlobalEmbeddedKafkaTestExecutionListener.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/rule/EmbeddedKafkaRule.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/EmbeddedKafkaKraftBrokerTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/EmbeddedKafkaZKBrokerTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/EmbeddedKafkaConditionTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/rule/AddressableEmbeddedBrokerTests.java
- spring-kafka-test/src/test/resources/junit-platform.properties
- spring-kafka/src/test/java/org/springframework/kafka/annotation/AliasPropertiesTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/BatchListenerConversionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminBadContextTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ErrorHandlingDeserializerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ExistingRetryTopicIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationManualAssignmentIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationIntegrationTests.java
- spring-kafka/src/test/resources/broker.properties
Resolves https://github.com/spring-projects/spring-kafka/issues/2391
> GH-2391: Add Kraft Version of EmbeddedKafkaBroker

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
The proxy in the `DefaultKafkaConsumerFactory` for `KafkaConsumer` is created only to intercept `close()` call to remove an instance from the `listeners`.
There is no need in such a proxy since simple `KafkaConsumer` class extension can handle that scenario.
The reason behind this change is to avoid a `Serializable` (`java.lang.reflect.Proxy`) header in the produced message for the `KafkaConsumer` where we still fail to serialize it because other properties of the proxy are not `Serializable`
* Introduce `DefaultKafkaConsumerFactory.ExtendedKafkaConsumer` to handle `listeners` interaction
* The `createRawConsumer()` might be considered as breaking change since now end-user must extend this `ExtendedKafkaConsumer` to be able to handle `listeners` same way as before
* Adjust …
> Get rid of proxy in DefaultKafkaConsumerFactory

- build.gradle
- exclude transitive `commons-logging` dependency from `spring-kafka-test`.
> Upgrade to Apache Kafka 3.6.0

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonDelegatingErrorHandlerTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2826
The `addDelegate` method did not update the classifier, so it failed to work when cause chain traversal is enabled.
**cherry-pick to 3.0.x, 2.9.x**
> GH-2826: Fix CommonDelegatingErrorHandler

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2832
**cherry-pick to 3.0.x, 2.9.x**
> GH-2826: Fix KafkaAdmin NPE With Bad Config Name

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonDeserializer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2838
Previously, the exception message contained the entire JSON content.
**cherry pick to 3.0.x (#2839) and 2.9. (#2840)**
I will add What's New? content to each branch after the merge.
> GH-2838: JSON Deser. Remove Verbose Exc. Message

- build.gradle
`MockTime` moved there in 3.6.
> Add kafka-server-common Transitive Test Dependency

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2853
Apparently, some third party Kafka replacements can return a `null` `clusterId`.
This causes an attempt to retrieve it on every operation.
**cherry-pick to 3.0.x**
> GH-2853: Handle null Cluster ID

- README.md
The Java version in README.md is still JAVA SE 7 or later, as specified in 2016. Seems we'd better bump it as per the version specified in build.gradle (Java 17).
Also perm size is deleted in Java 17, so the previous GRADLE_OPTS example doesn't apply. I changed the verbiage to point to the gradle.properties file.
> bump recommended java version to 17 in README.md

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
> GH-2731: fix count and time ack mode

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/configuring-topics.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/connecting.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/quick-tour.adoc
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/started/noboot/Sender.java
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/topics/Config.java
some minor improvements to reference. See self-comments for the rationale behind the changes. Potentially more similar PRs will come in later
> some cosmetic improvements of the reference

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/SerializationUtils.java
> GH-2862: Add Option to Log Recovery to DLPR

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-factory.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/exactly-once.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/headers.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/interceptors.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/pause-resume-partitions.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/producer-interceptor-managed-in-spring.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/tombstones.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/transactions.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/how-the-pattern-works.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/programmatic-construction.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-config.adoc
- spring-kafka-docs/src/main/java/org/springframework/kafka/jdocs/started/noboot/Config.java
all the way to 4.2.5 Features
feel free to make changes without requiing
> cosmetic doc improvements part 3

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
```
if (this.brokerListProperty != null) {
System.setProperty(this.brokerListProperty, getBrokersAsString());
}
System.setProperty(SPRING_EMBEDDED_KAFKA_BROKERS, getBrokersAsString());
System.setProperty(this.brokerListProperty, getBrokersAsString());
```
The last statement seems unnecessary and could lead to exception thrown if `this.brokerListProperty` is null
> remove unnecessary property setting statement in EmbeddedKafkaKraftBroker

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryTopicConfigurationProvider.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2654
* fix incorrect retry topic suffix when attempts is 2
* optimization method `isDelayWithReusedTopic`
* add retry topic integration tests when reuse retry topic
fix java doc in RetryTopic
* fix javadoc in `@RetryTopic`
* fix javadoc in `RetryTopicConfigurationProvider`
> GH-2654: Incorrect retry topic suffix

- build.gradle
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafka.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
Fixes https://github.com/spring-projects/spring-kafka/issues/2870
The `EmbeddedKafkaContextCustomizer` uses `beanFactory.initializeBean()` which is too early according to the `ApplicationContext` lifecycle since it is not refreshed yet for `ContextCustomizer`
* Rework the logic in the `EmbeddedKafkaContextCustomizer` to register a `BeanDefinition` for an `EmbeddedKafkaBroker` to include it into standard `ApplicationContext` lifecycle
* Also mark `@EmbeddedKafka` with a `@DisabledInAotMode` to disallow this kind of tests in native images
> GH-2870: EmbeddedKafka: register BeanDefinition

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2891
When using manual partition assignment and `AckMode.MANUAL`, it is possible to have a `null` `group.id`, whereby Kafka does not maintain any committed offsets.
In this case, we should not attempt to commit the offset after recovery, even if the error handler `ackAfterHandle` property is true.
**cherry-pick to 3.0.x, 2.9.x**
> GH-2891: Fix isAckAfterHandle with No group.id

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/tips.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Resolves https://github.com/spring-projects/spring-kafka/issues/2891
When using manual partition assignment with `null` `group.id` always coerce `AckMode` to `MANUAL`.
> GH-2891: Always MANUAL with null group.id

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Improved `Spring for Apache Kafka` > `Testing Applications` > `@EmbeddedKafka Annotation with JUnit5` documentation.
> Update testing.adoc > "@EmbeddedKafka Annotation with JUnit5" section

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/ooo-commits.adoc
This PR adds a note to the [documentation page](https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/ooo-commits.adoc) about `asyncAck` stating that it cannot be combined with `Acknowledgment.nack()`.
It was discussed in issue #2410, that `Acknowledgment.nack()` cannot be used when `asyncAck` set to `true`.
This was ensured with [: Disallow nack() with Out of Order Commits](https://github.com/garyrussell/spring-kafka/commit/18398517ee4bdcd05822319dabfad94b629bf9e8).
It was also documented at several places, e.g., with this commit: [: Disallow nack() with Out of Order Commits](https://github.com/spring-projects/spring-kafka/commit/950a2ea75cc4da9524ab275abe43d2a860380482).
However, it is not mentioned on the …
> Improve Documentation: State on OOO-Commits page that AsyncAcks cannot be combined with nack()

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/Acknowledgment.java
From the current documentation, it was not clear to me what is the effect of calling `Acknowledgment.nack()` when a listener is assigned to multiple topics and/or partitions.
Looking at the implementation, I believe that calling `nack(Duration sleep)` will pause the entire listener for the specified sleep duration. Another option would have been that is only pauses reading from one partition or one topic, which other topics or partitions are still processed.
With this PR, I attempt to make this more clear on the documentation page and in the JavaDoc of `Acknowledgment.nack()`. 
Please feel free to discuss, improve and correct me in case I'm wrong. Thank you!
> Improve Documentation about Acknowledgment.nack()

- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
It seems there is some logic cleaning up room in AggregatingReplyingKafkaTemplate to reuse existing RecordHeader without duplicating it.
Not very sure about the validity of my PR. Feel free to close it if invalid.
> reuse RecordHeader in AggregatingReplyingKafkaTemplate

- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/EmbeddedKafkaConditionTests.java
> GH-2927 Resolve subclasses of EmbeddedKafkaBroker in tests

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
see self-comments for the rationale behind the changes. Feel free to modify and revert back inappropriate change.
> minor improvement to DefaultKafkaHeaderMapper

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
Fixes: #2943
The `if (this.kafkaAdmin != null && this.clusterId == null) {` condition might be always true for concurrent threads (especially virtual). Therefore, all of those threads are calling `this.kafkaAdmin.clusterId()` making unnecessary network chats to Kafka broker
* Surround `this.kafkaAdmin.clusterId()` call with `Lock`
**Cherry-pick to `3.0.x`**
> GH-2943: Fix `KT.clusterId()` for concurrency

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Improvements in `MessagingMessageListenerAdapter` and `KafkaUtils`
* improvements and clenaup in `MessagingMessageListenerAdapter` and `KafkaUtils`
* clenaup in `EnableKafkaIntegrationTests`
----
Submit the improvements work separately, because of issue #1189 is complicated:
* `@KafkaListener` `@KafkaHandler` support Async return
* support `Mono` and `CompletableFuture` copy/paste from [AMQP-832](https://github.com/spring-projects/spring-amqp/issues/2374), 
* support `Kotlin Continuation`, copy/paste from [GH-1210: Add Kotlin suspend functions support](https://github.com/spring-projects/spring-amqp/issues/1210)
* Invoke KafkaListenerErrorHandler, copy/paste from [GH-2461: RabbitListenerErrorHandler with Async](https://github.com/spring-projects/spring-amqp/issues/2461)
* add warn log if …
> improvements in `MessagingMessageListenerAdapter` and `KafkaUtils`

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Fixes: #2965
Clarify how to override MockProducer and provide it via MockProducerFactory.
**Cherry-pick to `3.0.x`**
> GH-2965: Docs improvements in testing ref docs

- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ErrorHandlingUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ExceptionClassifier.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedRecordTracker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/FallbackBatchErrorHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerRecordTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
* remove `FailedRecordProcessor.retryListeners`, reuse FailureTracker's retryListeners
* cleanup related to error handlers
> minor improvement error handler related

- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
some minor and easily verified code quality improvements.
after the changes, the warnings in IDEA decreased from 16 to 5.
> GH-2967: Some minor improvements in RetryableTopicAnnotationProcessor

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
Fixes: #2981
When `producer.abortTransaction()` fails, the original exception is lost
* Catch an exception on `producer.abortTransaction()` and `ex.addSuppressed(abortException)`
**Cherry-pick to `3.0.x`**
> GH-2981: Suppress abortTransaction in KafkaTemplate

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/MultiMethodKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AdapterUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
> minor improvement `DelegatingInvocableHandler` and AKLE relate

- spring-kafka/src/main/java/org/springframework/kafka/annotation/DltHandler.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafkaRetryTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaNullAwarePayloadArgumentResolver.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryTopicConfigurationProvider.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/package-info.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicComponentFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupport.java
almost all of the nullness vulnerability has been fixed except that gigantic `org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor` class, which is left for future PR(s).
> GH-2974 Add NonNullApi and NonNullFields to package-info.java in 'annotation' package

- spring-kafka/src/main/java/org/springframework/kafka/listener/FailedBatchProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerNoSeeksBatchListenerTests.java
Resolves #2968 
`DefaultErrorHandler#handleBatchAndReturnRemaining` recovered invalid and infinite loop when kafka listener threw BatchListenerFailedException and error record is first one in remaining list..
> GH-2968 `DefaultErrorHandler#handleBatchAndReturnRemaining` recovered invalid

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Fixes: #2991
There is a warning log from `KafkaMessageListenerContainter#checkRebalanceCommits` that unconditionally prints that offsets could not be committed. Because of this unconditional check, the messages are very likely to be false positives. Fixing this by adding a check to see if there are indeed uncommitted records.
> GH-2991: Fix unwanted warning logs in KMLC

- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Cleanup redundant suppress warnings, other Java 17 improvements etc. in KafkaMessageListenerContainerTests
> Minor cleanup in KMLCT

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/transactions.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultTransactionIdSuffixStrategy.java
- spring-kafka/src/main/java/org/springframework/kafka/core/NoProducerAvailableException.java
- spring-kafka/src/main/java/org/springframework/kafka/core/TransactionIdSuffixStrategy.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultTransactionIdSuffixStrategyTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTransactionTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Introduce a new `TransactionSuffixManager` interface with `DefaultTransactionSuffixManager` implementation to restrict `transaction.id` in range for existing [PR](https://github.com/spring-projects/spring-kafka/pull/2913)
Resolves https://github.com/spring-projects/spring-kafka/issues/2852
> GH-2852: Provide a way to customize a transactionIdSuffix

- README.md
Resolves https://github.com/spring-projects/spring-kafka/issues/3005
Invalid reference manual link in README
* before: [https://docs.spring.io/spring-kafka/docs/current/reference/html/](https://docs.spring.io/spring-kafka/docs/current/reference/html/)
* after: [https://docs.spring.io/spring-kafka/reference/index.html](https://docs.spring.io/spring-kafka/reference/index.html)
> fix invalid reference link in README.md

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DestinationTopicPropertiesFactoryTests.java
polish `DestinationTopicPropertiesFactory` and `DestinationTopicPropertiesFactoryTests`
> Polish DestinationTopicPropertiesFactory

- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerialization.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/ParseStringDeserializer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/RetryingDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerializationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/DelegatingSerializationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/RetryingDeserializerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/ToStringSerializationTests.java
adapt apache kafka feature, reduce `CompletedFetch#parseRecord()` memory copy, details see https://issues.apache.org/jira/browse/KAFKA-14944
> Implementation Deserializer.deserialize(String, Headers, ByteBuffer)

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfiguration.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ListenerContainerFactoryConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
Deprecated `Configuration` and related public method in `ListenerContainerFactoryConfigurer`, remove args `Configuration` that method not public.
> Deprecated ListenerContainerFactoryConfigurer.Configuration

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/AfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/BatchListenerFailedException.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Resolves #2588
This is a draft of support DLT batch recover for `DefaultAfterRollbackProcessor`. so we can evaluate if it's going in the right direction before doing a final review, adding docs, etc.
Function
* add opt-in property `batchRecoverAfterRollback` at `ContainerProperties`
* add method processBatch at `AfterRollbackProcessor`
Batch recoverable
* batchRecoverAfterRollback is true
* set transcation DLT to enable isCommitRecovered
* enable kafka transcation
exception handler logic
* in retry, seek to begin
* out of retry exception recover entire recods
* recover fail, seek to begin
> GH-2588: ARBP support batch recoverable

- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
* remove Test `testConsumeAndProduceTransactionKTM_BETA` because it same as testConsumeAndProduceTransactionKTM.
* remove logger
> Polish TransactionalContainerTests

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Use AbstractMessageListenerContainer method `isPauseRequested` uniformly instead of `isPaused()`.
> Remove AbstractMessageListenerContainer.isPaused

- spring-kafka-docs/src/main/antora/modules/ROOT/nav.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/enforced-rebalance.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/MessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerEnforceRebalanceTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Fixes: #3011
Kafka consumer API supports an enforced rebalance. Provide an option via the message listener container to trigger this operation.
> GH-3011: Support enforced consumer rebalance

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/streams/KafkaStreamsInteractiveQueryService.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsInteractiveQueryServiceTests.java
Fixes: #2942
This is an initial iteration for providing a basic API around interactive query service in Kafka Streams. In this iteration, we introduce a single API for retrieving the queryable state store from the Kafka Streams topology, namely, retrieveQueryableStore.
> GH-2942: Kafka Streams queryable stores

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
* Clarify how KafkaStreamsInteractiveQueryService retries work in the docs
> Clarify retries in KSIQS docs

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/RetryingDeserializer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/RetryingDeserializerTests.java
> GH-3032: RecoveryCallback on RetryingDeserializer

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
```
public interface ConsumerSeekAware {
void seekRelative(String topic, int partition, long offset, boolean toCurrent);
}
```
when offset positive and toCurrent false.
actual behavior is seek absolute offset to the beginning of the partition, fix to expected behavior that seek relative to the beginning of the partition, see [Seeking to a Specific Offset](https://docs.spring.io/spring-kafka/reference/kafka/seek.html).
> fix bug about method ConsumerSeekAware.seekRelative

- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
* change `Arrays.asList` to `List.of`
* cleanup ConcurrentMessageListenerContainerMockTests
> Cleanup ConcurrentMessageListenerContainerMockTests

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/pause-resume.adoc
* `pause-resume.adoc`, Fix xref pauseImmediate.
* `micrometer.adoc`, change Micrometer Tracing link https://micrometer.io/docs/tracing to https://docs.micrometer.io/tracing/reference/index.html
* `container-props.adoc`, fix ContainerProperties properties
* cleanup `annotation-error-handling.adoc`
> polish adoc for kafka chapter

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Resolves #2287 
* Align lifecycle for earlyRecordInterceptor(intercept + failure/success + afterRecord) and earlyBatchInterceptor(intercept + failure/success).
* Fix unit test KafkaMessageListenerContainerTests, see https://github.com/spring-projects/spring-kafka/issues/2722 and https://github.com/spring-projects/spring-kafka/issues/2287.
> GH-2287: Align RecordInterceptor and BatchInterceptor lifecycle.

- spring-kafka/src/test/java/org/springframework/kafka/listener/TestOOMError.java
TestOOMError#testOOMCMLC throw `ConcurrentModificationException` needs simultaneous invoke `KafkaMessageListenerContainer#setStoppedNormally`, `ConcurrentMessageListenerContainer#isInExpectedState`, _modify property when stream.map().allMatch cause list size change_.
Then assertThat container.isInExpectedState(), because of container maybe is not in expected state. concurrent container publishes one time, child container publishes concurrency time, CountDownLatch needs to modify to 2.
* Fix `TestOOMError#testOOMCMLC` throw `ConcurrentModificationException`
---
```
TestOOMError > testOOMCMLC() FAILED
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel …
```
> Fix TestOOMError#testOOMCMLC throw ConcurrentModificationException

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonDelegatingErrorHandlerTests.java
Fixes: #3050
Correct CommonDelegatingErrorHandler validation for delegates compatibility.
Add documentation stating that delegates must be compatible with default error handler.
> GH-3050: Delegating EH delegates compatibility

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
Class.this use to inner Class display specifies outer Class.
* replace `KafkaTemplate.this` to `this` in `buildCallback`.
> Polish KafkaTemplate

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
* Add method `consumerWakeIfNecessary()` to reuse `consumer.wakeIfNecessary()`.
* Add method `getTxProducer()`.
* Optimize `determineListenerType()`.
* Change `OffsetMetadata` type to record.
> Polish KafkaMessageListenerContainer

- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedBatchProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
* Because `transactionManager` property is deprecated in `ContainerProperties` via a previous commit, there are some test variants that we may not need any longer. Cleaning them up and updating the tests where we were still using the deprecated transaction manager.
> Deprecation Code Cleanup

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/transactions.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic.adoc
Retry topic will break container txns atomicity
1. container txns commit success.
2. Message send to retryable topic retry again.
* Add adoc to notice.
See #2934
> Non-Blocking Retries cannot combine with container transactions.

- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
Fix race condition at TransactionalContainerTests.testBatchListenerRecoverAfterRollbackProcessorCrash
---
Exception see:
```
TransactionalContainerTests > testBatchListenerRecoverAfterRollbackProcessorCrash() FAILED
org.opentest4j.AssertionFailedError: 
expected: "qux"
but was: "baz"
at java.base@17.0.10/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base@17.0.10/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base@17.0.10/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base@17.0.10/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at app//org.springframework.kafka.listener.TransactionalContainerT …
```
> Fix race condition at TransactionalContainerTests.testBatchListenerRecoverAfterRollbackProcessorCrash

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
* Embedded the (original) exception into the observation, allowing downstream tracing code to handle it.
* Add unit test for observation Error and RuntimeException.
Resolves #3049
> GH-3049: Listener exceptions are not saved to the observation.

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/how-the-pattern-works.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/topic-naming.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicSameContainerFactoryIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicAnnotationProcessorTests.java
Resolves https://github.com/spring-projects/spring-kafka/issues/3052
* Change @RetryableTopic properties SameIntervalTopicReuseStrategy behavior to SINGLE_TOPIC
* Change unit test SameIntervalTopicReuseStrategy
* Add doc
> Change @RetryableTopic properties SameIntervalTopicReuseStrategy behavior to SINGLE_TOPIC

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
- spring-kafka/src/main/java/org/springframework/kafka/streams/KafkaStreamsInteractiveQueryService.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsInteractiveQueryServiceTests.java
Fixes: #3034
https://github.com/spring-projects/spring-kafka/issues/3034
* Kafka Streams interactive query API's for accessing remote state stores.
> GH-3034: IQ API's for remote state stores

- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
* When `AckMode.RECORD` and early is `false`, the last execute method is `RecordInterceptor.afterRecord`, miss out `CountDownLatch` waiting `RecordInterceptor.afterRecord` execute complete.
> fix bug at KafkaMessageListenerContainerTests.testInvokeRecordInterceptorAllSkipped()

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
> GH-2611: Remove MimeTypeJsonDeserializer

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java
This PR is naïve approach to solve #3076 (i am not sure about possible side effects/consequences of this change)
> GH-3076: Set `batchFailed` state in `ListenerConsumer` even if no `commonErrorHandler` is configured

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/seek.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerMockTests.java
Fixes: #3078
* Provide a new API method in `ConsumerSeekCallback` to seek to an offset based on the current offset. This is accomplished by a user-defined function where the user can make decision on the offset to seek to based on the current offset which is available via the function's input.
* Adding tests, docs.
> GH-3078: Compute Seek Position from Current Offset

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
This PR proposes a documentation update for the Spring Kafka project to correct the class naming convention for the 'hat' class in serializer and deserializer configurations. 
The current documentation uses `com.myhat.hat`, which doesn't adhere to Java naming conventions. This PR rectifies this inconsistency by updating the class name to `com.myhat.Hat`.
> Correct class naming convention for 'hat' in serializer/deserializer Doc

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/support/EndpointHandlerMethod.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupportTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java
* add @Nullable at `AbstractKafkaListenerEndpoint.setGroupId`
* add @Nullable at `AbstractKafkaListenerEndpoint.setGroupId`
* change `KafkaListenerEndpointDescriptor` type to `record` at `KafkaListenerEndpointRegistrar`
* cleanup `KafkaListenerEndpointRegistry`
* change `collect(Collectors.toList())` to `toList()` at `EndpointCustomizerFactory`.
* cleanup `EndpointHandlerMethod`.
* cleanup tests.
> polish retryable topic.

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/TopicPartitionOffset.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes: #3108
* When the seek API that uses the user-provided function to compute the offset to seek, there is a concurrency issue in which the Kafka consumer is used unsafely.
See this for details: https://github.com/spring-projects/spring-kafka/issues/3078#issuecomment-1983759811
> GH-3108: Unsafe access to consumer in seek API

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-config.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryTopicConfigurationProvider.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryableTopicAnnotationProcessorTests.java
* `@RetryableTopic` support annotated on Class.
* Support process `@RetryableTopic` from Class in `RetryTopicConfigurationProvider`.
* Support process `@DltHandler` when `@RetryableTopic` annotated on the Class in `RetryableTopicAnnotationProcessor`.
part of #3105
> @RetryableTopic support @KafkaListener annotated on class part 1

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/connecting.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaProducerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/KafkaAdminTests.java
Fixes: #GH-3001
Use Spring Boot's `spring.application.name` property as part of the default clientIds for Consumers, Producers and AdminClients. Helps with identifying problematic clients at server side.
* Only use as a fallback if clientId wasn't specified explicitly
* Do not use for Consumers with a specified groupId because KafkaConsumer will use the groupId as clientId which already is an identifiable default
> GH-3001: default clientIds with application name

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/config/MultiMethodKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizer.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/EndpointHandlerMethod.java
- spring-kafka/src/main/java/org/springframework/kafka/support/EndpointHandlerMultiMethod.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/EndpointCustomizerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurerTests.java
* `EndpointCustomizerFactory` adaptor `MultiMethodKafkaListenerEndpoint`.
* `RetryTopicConfigurer.processAndRegisterEndpoint` support `@KafkaListener` on a class.
* Add new class `EndpointHandlerMultiMethod` to handler multi method for retrying endpoints.
part2 of #3105 and this contributes to fixing https://github.com/spring-projects/spring-kafka/pull/3105 eventually.
> @RetryableTopic support KL annotated on class part 2

- build.gradle
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaProducerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/SerializationIntegrationTests.java
Fixes: #3116
* Upgrade kafka-client to 3.7.0
* Necessary test changes due to `KafkaConsumer` now uses a delegate based model for consumers to create legacy vs consumer-group based consumers. See the following link for more details. https://cwiki.apache.org/confluence/display/KAFKA/The+Next+Generation+of+the+Consumer+Rebalance+Protocol+%28KIP-848%29+-+Early+Access+Release+Notes
* Implement Kafka producer `clientInstanceId()` method in `CloseSafeProducer`
* whats-new changes
> GH-3116: Upgrade kafka-client to 3.7.0

- spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/SerializationUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DeadLetterPublishingRecovererTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/SerializationTestUtils.java
Fixes: #3114
* Since DeserializationExceptionHeader is currently porpagated as a `byte[]`, it encounters some issues when processing the header especially in batch listeners. Fixing this by providing the deserialization header without `byte[]` conversion
* Adding test to verify
* Refactoring in SerializationTestUtils
> GH-3114: DeserializationException propagation

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-config.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DeliveryHeaderTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/DltStartupTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ExistingRetryTopicClassLevelIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelExceptionRoutingIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicSameContainerFactoryIntegrationTests.java
Fixes: #3012
* Non-blocking retries support `@KafkaListener` on class level, include `@RetryableTopic`, `@DltHandler`, `RetryTopicConfiguration`, `RetryTopicConfigurationSupport`.
* Doc and test Non-blocking retries support `@KafkaListener` on class level.
---
Part 1:  Support process annotation `@RetryableTopic` and `@DltHandler` when `@RetryableTopic` annotated on class, see #3107.
Part 2:  `RetryTopicConfigurer#processAndRegisterEndpoint` support `MultiMethodKafkaListenerEndpoint`, see #3112.
Part 3:  `@EnableKafka` integration feature that non-blocking retries support `@KafkaListener` on class level,  see #3105.
> GH-3012: Non-blocking retries support @KafkaListener on class level

- spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaConsumerTemplate.java
* Adding wrapper method `receiveBatch` in ReactiveKafkaConsumerTemplate.
Closes #3057
> GH-3057: ReactiveKafkaConsumerTemplate missing receiveBatch method

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/kafkalistener-lifecycle.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerContainerRegistry.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaListenerEndpointRegistryTests.java
> GH-3135 : Adding new `ListenerContainerRegistry.getListenerContainersMatchingId(Predicate)` for easier usage. 

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Fixes: #3146
There is a requirement to see logs correlated even in the `CompletableFuture` result after `KafkaTemplate.send()` operation
* Add `observation.openScope()` into the `buildCallback()` logic
**Auto-cherry-pick to `3.1.x` & `3.0.x`**
> GH-3146: Propagate KafkaTemplate observation to Callback

- spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaRuntimeHints.java
* Since several of the native runtime hints that Spring for Apache Kafka provides for org.apahce.kafka classes are available via the graalvm-reachability-metadata repository (https://github.com/oracle/graalvm-reachability-metadata), we are no longer keeping these runtime hints in Spring for Apache Kafka since version 3.2.0. This applies to both kafka-client classes and Kafka Streams classes.
> Remove org.apache.kafka native runtime hints

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
👋 Hi Spring-Kafka Team !
When developping with Kafka Streams, I figured that when shutting down an app, the consumer didn't seem to proactively leave the Kafka consumer group.
This seems to be related to a `leaveGroup` parameter that wasn't used in the `org.apache.kafka.streams.KafkaStreams#close()` method.
So this PR adds support for this parameter, and documentation of the parameters in the *Apache Kafka Streams Support* section.
> Add an option to leave consumer group when closing Streams

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanTests.java
- spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryLateConfigTests.java
Hi, Spring kafka Team.
This is chickenchickenlove, huge fan of you guys.
I saw this issue (https://github.com/spring-projects/spring-kafka/issues/3020). i want to resolve this problem by myself!
- https://github.com/spring-projects/spring-kafka/issues/3020
- If `Topology` of `kafka streams` are initialized before `StreamsBuilderFactoryBean#start()`, it will be very helpful to Test code for `spring kafka-streams`. `TopologyTestDriver` is very efficient to test comparing to `TestContainers`. 
- I have tiny PR to solve Issue(https://github.com/spring-projects/spring-kafka/issues/3020).
- It might be a fairly simple fix, but it could look bad. IMHO, it's a better idea to register `StreamsBuilder` as a `Bean` in a different scope, however, it will introduce many changes to …
> Create topology before kafka streams start.

- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/StreamsBuilderFactoryBeanInMemoryStateStoreTests.java
GH-3176: Setting the Kafka Streams property default.dsl.store has no effect
This is a proposal to fix GH-3176 (https://github.com/spring-projects/spring-kafka/issues/3176)
> GH-3176: Take property default.dsl.store into account

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-annotation.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/PartitionOffset.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
Fixes #3178
* align `@PartitionOffset` to `TopicPartitionOffset`.
* add unit test for `@PartitionOffset.SeekPosition`.
* add unit for SpEL partitions to Integer[] and Integer.
* add adoc `whats-new.adoc` or `listener-annotation.adoc`.
> GH-3178: Align @PartitionOffset to TopicPartitionOffset

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
Closes #3186
* Don't retry failed commits due to rebalance if they are subsequently superseded by successful commits
* Modify rebalance test cases to capture the scenario that triggers the bug
> GH-3186: Filter out successful commits from retry

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- I found that the `descriptions` and `methods` related to `ackDiscarded` behave differently during investigating [issue](https://github.com/spring-projects/spring-kafka/issues/2806). 
https://github.com/spring-projects/spring-kafka/blob/1d0a7d305aec6e0976027267e80c3effd80e870c/spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java#L335-L341
- From java docs, when `setRecordFilterStrategy()` in use, `ackDiscarded` should be `true`. however, `ackDiscarded` is always `false` even if some `BeanPostProcessor` call `setRecordFilterStrategy()` to use `RecordFilter`. 
- create new method `useRecordFilterStrategy()` to bind `setRecordFilterStrategy()` and `setAckDiscarded()` to follow java docs.
> Fix ackDiscarded.

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Fixes: #3210
* When adding a tag to the current span during the sending of a kafka message using KafkaTemplate, the tag gets added to another span because KafkaTemplate doesn't open the scope for the started observation. Fixing this issue by wrapping the doSend method call in a proper observation scope.
**Auto-cherry-pick to `3.1.x` & `3.0.x`**
> GH-3210: KafkaTemplate currentSpan tagging issue

- spring-kafka/src/main/java/org/springframework/kafka/security/jaas/KafkaJaasLoginModuleInitializer.java
Fixes: #3217
* Cleaning up a temp file creation that was added as part of Kafka 0.9 Java client. This seems to be a no-op in the latest versions of the Kafka Java client.
> GH-3217: kafkaJaasInitializer clean up

- spring-kafka/src/main/java/org/springframework/kafka/listener/CommonDelegatingErrorHandler.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/CommonDelegatingErrorHandlerTests.java
Implement CommonErrorHandler.handleOne() in CommonDelegatingErrorHandler #3227
https://github.com/spring-projects/spring-kafka/issues/3227
Adds an implementation of `CommonErrorHandler.handleOne()` in `CommonDelegatingErrorHandler`.
Implementation functions the same as the other `handle` methods - Finds a delegate to call `handleOne()` on, or uses the `defaultErrorHandler`
> GH-3227: Implement handleOne() in CommonDelegatingErrorHandler

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
Fixes: #3242
**Auto-cherry-pick to `3.1.x` & `3.0.x`**
> GH-3242: Clarify docs on custom Consumer/Producer factories

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
* Clarify the usage of the new consumer-group protocol in the 3.7.0 version of the client
* Add a note on the usage of `EmbeddedKafka` in `kraft` mode
> Adding more whats-new for kakfa-client 3.7.0

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
Hi Team,
This PR the use of deprecated Kafka Streams API methods in the example code provided in the documentation.
+ Replace deprecated `TimeWindows.of` method with `TimeWindows.ofSizeWithNoGrace`.
> Fix deprecated Kafka Streams API in example code

- spring-kafka/src/main/java/org/springframework/kafka/support/AbstractKafkaHeaderMapper.java
**Auto-cherry-pick to `3.2.x` & `3.1.x`**
> Add tracing headers to be mapped to string

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/AdapterUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/ContinuationHandlerMethodArgumentResolver.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/kotlin/org/springframework/kafka/listener/EnableKafkaKotlinTests.kt
* https://github.com/spring-projects/spring-kafka/issues/3277
* `isCoroutines` is a method unit, but on the determineInferredType method it determine by each parameter type. So I think that determine by parameter type is more nice way to improve it
* Change variable naming `isCoroutines` to `isKotlinContinuation` variable 
* Change the coroutine detection logic 
* Feel free to discuss about the test code improvement way
> GH-3277 : Fix coroutine detection login on MessagingMessageListenerAdapter

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/features.adoc
- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPartitionPausedEvent.java
- **ConsumerPartitionPausedEvent**
- Correct misleading method name and content.
- `ConsumerPausedEvent` -> `ConsumerPartitionPausedEvent` (This prevents confusion with the existing event `ConsumerPausedEvent`).
- `getPartitions()` -> `getPartition()` (Since the event is specific to a single partition, use the singular form)
- **features.adoc**
- `DeadLetterPublishingRecovererer` -> `DeadLetterPublishingRecoverer` 
- This reverts the incorrect change made in [PR #3226](https://github.com/spring-projects/spring-kafka/pull/3226).
> Update misleading contents in ConsumerPartitionPausedEvent and features.adoc

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaListenerEndpointRegistryTests.java
The `KafkaListenerEndpointRegistry.getUnregisteredListenerContainer()` returns `null` when container is already present in the internal `unregisteredContainers` cache
* Fix `KafkaListenerEndpointRegistry.getUnregisteredListenerContainer()` to return a container instance from the `unregisteredContainers` cache
**Auto-cherry-pick to `3.2.x` & `3.1.x`**
> GH-3319: Fix NPE in the `KafkaListenerEndpointRegistry`

- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistry.java
Fixes: #3349
* The KafkaListenerEndpointRegistry refactoring for List.isEmpty() instead of List.size() > 0
> GH-3349: Polish

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultKafkaConsumerFactoryTests.java
Fixes  #3375: ExtendedKafkaConsumer now overrides close() in order to make sure listener.consumerRemoved() is called when the consumer is closed
> GH-3375: ExtendedKafkaConsumer now overrides close()

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/how-the-pattern-works.adoc
Fixes: https://github.com/spring-projects/spring-kafka/issues/3396
This pull request updates the documentation to reflect the support for class-level @KafkaListener annotations in the retry topic configuration, available since version 3.2. It corrects the outdated statement and adds a relevant code example.
> GH-3396 : Fix retry topic documentation for class-level configuration

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
Fixes: #3395
When using `ReplyingKafkaTemplate,` include the original key from the request record if such a key exists.
> GH-3395: Use Original Key in Reply Record

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/tips.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafka.java
Fix typos in the documents below.
- `EnableKafka`
- `tips.adoc`
> Fix typos in the `EnableKafka` and `tips.adoc`

- build.gradle
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
- spring-kafka/src/test/java/org/springframework/kafka/support/serializer/StringOrBytesSerializerTests.java
> GH-3416: Upgrading to kafka-client 3.8.0

- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaMessageHeaderAccessor.java
#3408 
Updated JavaDoc to show the return of the method is the the decoded header if header is present. Throws IllegalStateException if otherwise
> DOC: JavaDoc for KafkaMessageHeaderAccessor.getBlockingRetryDeliveryAttempt()

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
In `processTimestampSeeks()`, we use `seekIterator` to pre-remove unassigned partitions, thus eliminating duplicate code running in the following loop.
> Clean up `processSeeks()` duplicate code

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/RecordInRetryException.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/SeekUtils.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/DefaultErrorHandlerRecordTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/FailedBatchProcessorTests.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/SeekToCurrentRecovererTests.java
Fixes: #3409
- During error handling, records in retry are throwing `KafkaException` after seeking that causes the exception to get logged which maybe misleading. It seems to indicate that the error handling process itself thew the exception, while the exception was thrown in order to prevent accidental committing of a not-yet recovered record. Change this exception during seeks in retry while handling error from `KafkaException` to a new framework-only used exception - `RecordInRetryException` that simply logs the message at INFO level.
> GH-3409: Improve exceptions during retry

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/aot/KafkaAvroBeanRegistrationAotProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/config/TopicBuilder.java
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerGroupSequencer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/AggregatingReplyingKafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/support/AbstractKafkaHeaderMapper.java
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerialization.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/KafkaMessageListenerContainerTests.java
- There are some codes using `*.size() > 0` or `*.size() == 0` in `spring-kafka`.
- There is code where the constructor could be reused, but it was not. 
- There is code where a `null` value can occur, but it does not indicate that `null` is possible.
- Replace `a.size() > 0` with `!a.isEmpty()`.
- Replace `a.size() == 0` with `a.isEmpty()`.
- Reuse constructor already existed to remove duplicate constructor logic. 
- Add @Nullable annotations to field, and method. Also, add warning log. 
- There is only one side effect which developer can observe.
-  when `BatchMessagingMessageListenerAdapter#setBatchMessageConverter()` is executed, new warning log can be occur.
> No Issue : Internal Refactoring to improve code readability.

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerGroupSequencer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainerTests.java
This commit would fix the [issue](https://github.com/spring-projects/spring-kafka/issues/3338).
1) 'isChildRunning' API would return true only after all the containers are actually stopped. 
2) Add 'stopAbnormally' in a Lock.
3) Call `childStarted` in ConcurrentContainer from KafkaMessageListenerContainer right before publishing ConsumerStartedEvent.
> Fix ConcurrentContainer lifecycle issues

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DeadLetterPublishingRecovererFactory.java
Fixes: #3424
Provide the ability to customize logging in `DeadLetterPublishingRecovererFactory`.
> GH-3424: Customizing DeadLetterPublishingRecovererFactory logging

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
Fixes: #3467
The `KafkaListenerAnnotationBeanPostProcessor.afterPropertiesSet()` get access to `BeanFactory` for other beans which causes a warning into logs like:
```
is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor
```
The rule of thumb is to not have any bean factory access from `BeanPostProcessor` initialization phase
* Fix `KafkaListenerAnnotationBeanPostProcessor` to `buildEnhancer()` i lazy manner. Therefore remove an `afterPropertiesSet()` altogether
**Auto-cherry-pick to `3.2.x` & `3.1.x`**
> GH-3467: Fix KafkaListenerAnnotationBeanPostProcessor for early BF access

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Fixes: #3466
https://github.com/spring-projects/spring-kafka/issues/3466
Improve bootstrap-server config comparison to avoid unnecessary KafkaAdmin recreation. This addresses inconsistencies between List<String> and String configurations for bootstrap servers.
The change ensures that List versions of bootstrap-server configs are converted to regular Strings by removing brackets. This allows for consistent comparison between producer and admin configurations.
This optimization is particularly relevant for Spring Boot scenarios where configs may be provided in different formats but represent the same underlying values.
> GH-3466: Optimize KafkaAdmin creation in KafkaTemplate

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
In streams.adoc, RetryTemplate is incorrectly written "RetryTemmplate"
> Fix - "RetryTemplate" misspelling in streams.adoc

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsCustomizer.java
- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
Fixes #3515. This PR introduces the ability to customize the instantiation of `KafkaStreams` using the `KafkaStreamsCustomizer` interface.
> Support custom KafkaStreams implementations

- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationProviderTests.java
I have updated the documentation in `@RetryableTopic` to change the previously referenced `retryTopicDefaultKafkaTemplate` to `defaultRetryTopicKafkaTemplate`.
Additionally, I modified the test code to replace instances of `retryTopicDefaultKafkaTemplate` with `RetryTopicBeanNames.DEFAULT_KAFKA_TEMPLATE_BEAN_NAME` to ensure it uses the correct default bean name.
Thank you for considering my PR, and I would be grateful for the opportunity to become a contributor.
>>> Fixes: https://github.com/spring-projects/spring-kafka/issues/3514
> GH-3514: Change default template bean name from retryTopicDefaultKafkaTemplate to defaultRetryTopicKafkaTemplate.

- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
In these test codes, `@Component` annotation is dead code. 
Because these bean have been registered by `@Bean` annotation with `RetryTopicConfigurations` inner class.
> Remove dead code from test codes.

- spring-kafka/src/main/java/org/springframework/kafka/annotation/KafkaListenerAnnotationBeanPostProcessor.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ContainerCustomizationTests.java
Fixes: #3544
https://github.com/spring-projects/spring-kafka/issues/3544
- Enhance resolveContainerPostProcessor method in KafkaListenerAnnotationBeanPostProcessor to evaluate SpEL expressions
- Verify containerPostProcessor property in KafkaListener annotation can be specified as a SpEL expression
> GH-3544: Support SpEL in @KafkaListener containerPostProcessor

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ExistingRetryTopicClassLevelIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/ExistingRetryTopicIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelExceptionRoutingIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicClassLevelIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicExceptionRoutingIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/RetryTopicSameContainerFactoryIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/Configurer1Tests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/Configurer2Tests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsBranchTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsInteractiveQueryServiceTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsJsonSerializationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/KafkaStreamsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/streams/RecoveringDeserializationExceptionHandlerTests.java
In the `MessagingMessageListenerAdapter` class, `org.springframework.messaging.converter.MessageConversionException` is already imported. however, the `MessageConversionException` was declared with full package names.
Many test classes don't use `KafkaTestUtils.consumerProps()` and `KafkaTestUtils.producerProps()` even if they can. 
Also, test code for `KafkaStreams` can be integrated using `KafkaTestUtils.streamsProps()`.
> No Issue : Refactor test codes and Remove useless full package name.

- spring-kafka/src/main/java/org/springframework/kafka/core/ProducerFactory.java
The error message "This factory does not support this method" was hardcoded twice in the production code of the ProducerFactory interface. By introducing the constant FACTORY_DOES_NOT_SUPPORT_METHOD, we eliminate this duplication, improve code maintainability, and ensure consistency. This change is particularly significant as it affects actual production code, not test code. Moreover, while currently used twice, this constant could potentially be reused in other parts of the codebase in the future, further justifying its creation and enhancing the overall code quality and future maintainability of the ProducerFactory and related classes.
> Refactor ProducerFactory to use constant for repeated exception message

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
I noticed that the warning message when using `ConsumerRecords` is somewhat unclear. In particular, the distinction between 'List' and 'id' could be more explicit. To enhance clarity, I made some adjustments to that part.
> Improve warning message for ConsumerRecords filter strategy

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/HandlerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
…bleFuture, Mono)
Fixes: #3528
https://github.com/spring-projects/spring-kafka/issues/3528
- Improve spring-kafka observability for failures in async consumer tasks when listener methods return CompletableFuture<?> or Mono<?> and throw errors during async execution
- Refactoring code in KafkaMessageListenerContainer and MessagingMessageListenerAdapter around observability
- Adding tests to verify
- Add @Nullable annotations to relevant methods for better null safety
> GH-3528: Improving Observability in Asynchronous Processing 

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaMetricsSupport.java
- spring-kafka/src/main/java/org/springframework/kafka/core/MicrometerConsumerListener.java
- spring-kafka/src/main/java/org/springframework/kafka/core/MicrometerProducerListener.java
- spring-kafka/src/main/java/org/springframework/kafka/streams/KafkaStreamsMicrometerListener.java
- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
- spring-kafka/src/test/java/org/springframework/kafka/config/KafkaStreamsCustomizerTests.java
Related to: https://github.com/micrometer-metrics/micrometer/issues/4976
* Introduce a `KafkaMetricsSupport` to have a common API for the `MeterBinder` registration
* Rework `MicrometerConsumerListener`, `MicrometerProducerListener` and `KafkaStreamsMicrometerListener` to extend the `KafkaMetricsSupport` which allows to minimize code duplication
* Expose ctors on those listeners based on the `TaskScheduler`
* Implement a simple `ScheduledExecutorServiceAdapter` to adapt a `TaskScheduler` to the expected by the `KafkaMetrics` `ScheduledExecutorService`
> Add `TaskScheduler` option for Kafka metrics components

- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/AsyncCompletableFutureRetryTopicScenarioTests.java
- spring-kafka/src/test/java/org/springframework/kafka/retrytopic/AsyncMonoRetryTopicScenarioTests.java
In the previous version, all test cases depended on sleep.
However, it made all test cases flaky. 
(Please refer to this comment https://github.com/spring-projects/spring-kafka/pull/3523#issuecomment-2419692216)
- Removed sleep.
- Used latch instead.
- Fixes flaky test cases in `AsyncCompletableFutureRetryTopicScenarioTests`, `AsyncMonoRetryTopicScenarioTests`.
I removed a test case. that involved a random situation. 
However, it is very hard to handle a random situation with a latch. 
Therefore, I decided to remove it and create a new test with a more complex scenario.
> Fix flaky tests in async retry by using a latch instead of sleep.

- spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
**While analyzing the toMessage() function of BatchMessagingMessageConverter, improvements were made. We have worked on improving it accordingly.**
1. Replace traditional loops with **Java Stream API** for processing collections. This enhances code conciseness and readability, allowing for functional-style operations on data.
```java
private void processRecord(ConsumerRecord<?, ?> record, List<Object> payloads, List<Object> keys,
List<String> topics, List<Integer> partitions, List<Long> offsets,
List<String> timestampTypes, List<Long> timestamps, List<Map<String, Object>> convertedHeaders,
List<Headers> natives, List<ConsumerRecord<?, ?>> raws, List<ConversionException> conversionFailures,
Map<String, Object> rawHeaders, Type type) {
// proceedRecord..
}
```
2. Utilize Optional to handle …
> Improve the implementation of the toMessage() function in the BatchMessagingMessageConverter:

- spring-kafka/src/main/java/org/springframework/kafka/support/AbstractKafkaHeaderMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
Fixes: #3581
https://github.com/spring-projects/spring-kafka/issues/3581
- Optimize `headerValueToAddIn` method by adding better null checks
- Add unit test to verify
> GH-3581: Address NPE in `AbstractKafkaHeaderMapper`

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultKafkaConsumerFactory.java
- Corrected "producer configuration" to "consumer configuration" in `DefaultKafkaConsumerFactory` comments
- Added `default` keyword to methods in `ProducerListener` interface in `sending-messages.adoc`
- Updated casing from `ConsumerConfigs` to `consumerConfigs` for consistency in `serdes.adoc`
- Added other minor refinements.
> Refine docs for consistency and correctness

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/events.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/annotation-send-to.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
- Corrected `AbstractListenerContainer` to `AbstractMessageListenerContainer` in `change-history.adoc` and `container-props.adoc`.
- Removed `assignedPartitionsByClientId` properties in `container-props.adoc` as they no longer exist in the code.
- Added a doc reference to improve consistency for container thread naming in `container-props.adoc`
- Made additional minor improvements to enhance overall documentation clarity.
> Refine docs for improved accuracy

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ContainerPartitionPausingBackOffManager.java
- spring-kafka/src/main/java/org/springframework/kafka/support/serializer/DelegatingByTopicSerialization.java
Modified the `LogAccessor` codes for log traceability and consistency across the project.
> Update LogAccessor instantiations with current class names

- CONTRIBUTING.adoc
Modifications:
- Updated the broken Git documentation link from `https://git-scm.com/book/en/Distributed-Git-Contributing-to-a-Project` to the correct link `https://git-scm.com/book/ms/v2/Distributed-Git-Contributing-to-a-Project`.
> Update broken Git documentation link to correct URL

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/interceptors.adoc
- #3587
Modifications:
- Removed the duplicate producerProperties declaration from kafkaProducerFactory.
- Updated the code structure in kafkaProducerFactory to be consistent with the consumerFactory sample
> Remove duplicate producerProperties declaration in kafkaProducerFactory

- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
Fixes: #3557 
Expected Behavior
It would be nice if the embedded broker started by @EmbeddedKafka (or the similar JUnit Rule) defaulted the replication factor for the transaction state topic to the number of brokers, or a min(<number-of-brokers>, 3).
Current Behavior
The embedded broker starts with the default configuration of transaction.state.log.replication.factor = 3 which doesn't make sense for a single-broker cluster, which is quite common in tests:
```
org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
```
Fix
* When writing test code using EmbeddedKafka, adjust the number of brokers for the transaction topic to the minimum.
* The topic has been made constant
> Lower the replication factor for transactions topic on @EmbeddedKafka Test

- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
* Fix warning in the `EmbeddedKafkaContextCustomizerTests.testTransactionReplicationFactor()`
> Some generics optimization in the `MessagingMessageListenerAdapter`

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
- spring-kafka/src/main/java/org/springframework/kafka/support/converter/BatchMessagingMessageConverter.java
Fixes: #3555
Issue link: https://github.com/spring-projects/spring-kafka/issues/3555
The batch might be processed in the `@KafkaListener` silently without looking into conversion failures header. So, that might cause in impression that nothing is wrong with the batch.
* Mention `KafkaHeaders.CONVERSION_FAILURES` in the docs
* Add `warn` for the failed conversion in the `BatchMessagingMessageConverter`
* Some other code optimization clean up in the `BatchMessagingMessageConverter`
> GH-3555: Improve docs for `KafkaHeaders.CONVERSION_FAILURES`

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- In the [previous PR](https://github.com/spring-projects/spring-kafka/pull/3523), `spring-kafka` has a potential bug during async retry because of race condition between thread for KafkaMessageListenerContainer and threads for `Mono` or `CompletableFuture`.
- After capturing the size to remove from `failedRecords`, it is repeatedly removed.
- Fixes https://github.com/spring-projects/spring-kafka/issues/3638
> GH-3638: Fixes bug caused by race condition during handleAsyncFailure().

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/filtering.adoc
Hello
I'd like to fix dead link I've found today.
> Fix dead page url in filtering.adoc

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/dlt-strategies.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/features.adoc
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- **DeadLetterPublishingRecoverer.java**
- The field `failIfNoDestinationReturned` is non-existent. Moreover, in the context of DLT strategy here, `fail` means ending without performing any retry or throwing an error. However, `failIfNoDestinationReturned: true` actually throws an error, which is inconsistent with this meaning. Therefore, I changed it to `throwIfNoDestinationReturned` for clarity and consistency.
- **dlt-strategies.adoc**
- Modified the method signature for the `@DltHandler` annotation because it cannot be identical to the method signature for the `@RetryableTopic` annotation.
- **features.adoc**
- Removed the reference to `kafkaOperations` as it is a non-existent variable.
> Update DLT log message and docs

- spring-kafka/src/main/java/org/springframework/kafka/core/reactive/ReactiveKafkaProducerTemplate.java
* Fixes : #3617 
* add @Nullable to parameter of send method
* Fix to allow tombstone records to be transferred.
> GH-3617 : Value parameters in ReactiveKafkaProducerTemplate should be nullable

- build.gradle
- Adds direct dependency on kafka-server module to support integration testing components that require broker functionality.
> spring-kafka-test: add kafka-server dependency

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/EmbeddedKafkaKraftBrokerTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/EmbeddedKafkaZKBrokerTests.java
Fixes #GH-3660
> Problem:
> consumeFromEmbeddedTopics calls Consumer.seekToEnd, which "evaluates lazily, seeking to the final offset in all partitions only when poll(Duration) or position(TopicPartition) are called". This means that the consumer may or may not see future messages, depending on timing.
> 
> This fix calls `position` so that the seek happens before consumeFromEmbeddedTopics returns. That was it is ensured that any message sent to the topic after the call to consumeFromEmbeddedTopics are seen by the consumer.
I did not see tests yet for the consume methods in EmbeddedKafkaBroker, so I'm not entirely sure if this is the approach you would want for the tests. The tests are inspired by tests in KafkaTestUtilsTests.
> GH-3660: Fix EmbeddedKafkaBroker seekToEnd

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBrokerFactory.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaZKBroker.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/condition/EmbeddedKafkaCondition.java
- spring-kafka-test/src/main/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizer.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/EmbeddedKafkaConditionTests.java
- spring-kafka-test/src/test/java/org/springframework/kafka/test/context/EmbeddedKafkaContextCustomizerTests.java
Fixes: #3658
Issue link: https://github.com/spring-projects/spring-kafka/issues/3658
When `@EmbeddedKafka` is used with Spring context, the `adminTimeout` is not resolved. Apparently when `adminTimeout` was introduced, it was covered only by the `EmbeddedKafkaCondition`.
* Extract `EmbeddedKafkaBrokerFactory` to encapsulate an `EmbeddedKafkaBroker` creation logic (including the mentioned `adminTimeout`)
* Replace the logic in the `EmbeddedKafkaCondition` and `EmbeddedKafkaContextCustomizer` with that new `EmbeddedKafkaBrokerFactory`, essentially, introducing a single place of truth.
* Pull `adminTimeout(int)` property to the `EmbeddedKafkaBroker` interface, making the logic in the `EmbeddedKafkaBrokerFactory` simpler
* Add `adminTimeout` attribute verification into tests for condition, as …
> GH-3658: Fix `@EmbeddedKafka` for `adminTimeout` resolution

- spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaKraftBroker.java
Fixes: #3662
Issue: https://github.com/spring-projects/spring-kafka/issues/3662
Add compatibility for both Kafka 3.8.0 and 3.9.0+ by handling different method signatures for setConfigProp:
- 3.9.0+: setConfigProp(String, Object)
- 3.8.0: setConfigProp(String, String)
The change uses reflection to detect Kafka version and call appropriate method.
> GH-3662: Support Kafka 3.9.0+ in EmbeddedKafkaKraftBroker

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
Fixes: https://github.com/spring-projects/spring-kafka/issues/3690
When `this.listener` is an instance of `RecordMessagingMessageListenerAdapter`, we rely on its logic to call `invoke()` from super class to handle observation lifecycle this or other way.
However, Spring Integration's `KafkaMessageDrivenChannelAdapter` use its own `IntegrationRecordMessageListener` extension of the `RecordMessagingMessageListenerAdapter` without calling super `invoke()`.
The problem apparent from Spring Cloud Stream Kafka Binder, where an observation is enabled.
* Fix `KafkaMessageListenerContainer` to check for exact type of `this.listener` before making decision to close an observation here, or propagate it down to the `RecordMessagingMessageListenerAdapter`
> GH-3690: Fix observation leak in the `KafkaMessageListenerContainer`

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
Fixes: https://github.com/spring-projects/spring-kafka/issues/3695
Even if th `@KafkaHandler` method is `void` the `DelegatingInvocableHandler` returns an empty `InvocationResult`. That triggers a `MessagingMessageListenerAdapter.handleResult()` logic. On the `completableFutureResult.whenComplete()` we call `acknowledge()` which is not expected for `void` POJO methods.
* Fix `MessagingMessageListenerAdapter` to check for `isAsyncReplies()` before calling `acknowledge()`
This is a regression after https://github.com/spring-projects/spring-kafka/issues/3528
> GH-3695: Fix `MessagingMessageListenerAdapter` to not ack when sync

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Fixing a typo in the documentation - see #3701.
> Fixing the class names in one of the documentation provided snippets.

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/features.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/how-the-pattern-works.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/retry-config.adoc
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurer.java
- Corrected `RetryConfigurationSupport` to `RetryTopicConfigurationSupport` in `features.adoc`, `how-the-pattern-works.adoc` `retry-config.adoc`.
- Added quotes(`""`) for string-type attributes in `@RetryableTopic` (e.g., traversingCauses, numPartitions, autoCreateTopics).
- Updated `RetryTopicConfigurationBuilder` methods to use `List` for arguments (e.g., includeTopics(), excludeTopics()).
> Correct non-blocking retries docs

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/DelegatingInvocableHandler.java
Fixes: #3697 
Change the logic in the  DelegatingInvocableHandler.invoke()
> GH-3697: DelegatingInvocableHandler.invoke() returning null

- CONTRIBUTING.adoc
- README.md
> Fix typo in `CONTRIBUTING` and `README`

- settings.gradle
Fixes: https://github.com/spring-projects/spring-kafka/issues/3734
This commit configures the Foojay resolver plugin in the Gradle build to auto-provision a required JDK distribution if it's not present already on the host.
> GH-3734: Configure Gradle toolchain auto-provisioning

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/HandlerAdapter.java
- spring-kafka/src/test/kotlin/org/springframework/kafka/listener/EnableKafkaKotlinCoroutinesTests.kt
Fixes: #3740
Issue link: https://github.com/spring-projects/spring-kafka/issues/3740
Even if Kotlin `suspend` functions are called properly, the acknowledgement is not called because this kind of method is not treated as an `asyncReplies` mode
* Fix `HandlerAdapter` to check for `KotlinDetector.isSuspendingFunction()` in addition to `CompletableFuture` & `Mono`
* Adjust `EnableKafkaKotlinCoroutinesTests.kt` to verify that `acknowledgement` has been called by the Framework
**Auto-cherry-pick to `3.3.x` & `3.2.x`**
> GH-3740: Fix `HandlerAdapter` to detect Kotlin suspend functions

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/MicrometerMetricsTests.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Fixes: #3741
Issue: https://github.com/spring-projects/spring-kafka/issues/3741
When exceptions occur in Kafka listeners, the metrics currently show `ListenerExecutionFailedException` in both the `error` tag (when using observation) and `exception` tag (when using micrometer without observation), rather than the actual underlying exception.
* Modify ListenerContainer to pass actual exception to failure metrics
* Update MessagingMessageListenerAdapter to report cause to observation
* Add MicrometerMetricsTests to verify both observation and non-observation metrics
* Fix ObservationTests to verify correct error reporting in metrics
This ensures metrics show the actual underlying exception while maintaining existing span behavior.
Signed-off-by: Soby Chacko <soby.chacko@broadcom.com> …
> GH-3741: Fix metric tag to show underlying exception type

- spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RecordFilterStrategy.java
Initialise the "batch of records" list container as an ArrayList rather than LinkedList. 
Using a LinkedList has an impact on performance as outlined here https://github.com/spring-projects/spring-kafka/issues/3764
(fixes #3764)
> feat: Replace LinkedList with ArrayList

- gradle/docs.gradle
- spring-kafka-docs/src/main/antora/antora-playbook.yml
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/native-images.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/filtering.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/listener-annotation.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/serdes.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/tombstones.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/other-resources.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/quick-tour.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/streams.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
The main points:
- The new Spring Kafka version document will be compatitable with Spring Framework version or Micrometer version document
- Reference javadoc will be easier, use `javadoc:org.springframework.amqp...`
> Improve `build.gradle` for building antora

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
This fixes that exceptions thrown from observation.start() are hidden by KafkaTemplate throwing a new exception due to registering observation error without successfully starting the observation.
Signed-off-by: Christian Fredriksson <christian.fredriksson.2@volvocars.com>
> Fix KafkaTemplate hiding exceptions when starting observation

- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaListenerObservation.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/KafkaListenerObservationTests.java
This change fixes an NPE when group id is null and observation is enabled.
> Handle null group id in listener observation

- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaRecordSenderContext.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
Fixes: #3786
Issue link: https://github.com/spring-projects/spring-kafka/issues/3786
When tracing is enabled, the KafkaRecordSenderContext was adding a new traceparent header without removing existing ones, resulting in multiple traceparent headers in the same record. This commit fixes the issue by Updating KafkaRecordSenderContext to remove existing traceparent headers before adding new ones.
**Auto-cherry-pick to `3.3.x` & `3.2.x`**
> GH-3786: Remove ProducerRecord duplicated traceparent header

- spring-kafka-test/src/main/java/org/springframework/kafka/test/utils/KafkaTestUtils.java
Fixes: #3810
Move the logging statement after the conditional statement.
> GH-3810 Move the logging statement after the conditional statement.

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
> Adding whats-new section for 4.0.0

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/quick-tour.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
> Update testing docs for 4.0.0 with the updates in EmbeddedKafka

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaTemplate.java
- spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
> GH-3808: ReplyingKafkaTemplate observation on reply

- spring-kafka/src/main/java/org/springframework/kafka/event/ConsumerPartitionPausedEvent.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractConsumerSeekAware.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/DeadLetterPublishingRecoverer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ListenerUtils.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/DestinationTopicContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/support/KafkaUtils.java
Fixes: #3829
Issue: https://github.com/spring-projects/spring-kafka/issues/3829
Since 4.0.0 is a new major version, we can remove all the previously deprecated components.
> GH-3829: Remove items marked as deprecated in previous generations

- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/AbstractKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/ConcurrentKafkaListenerContainerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaListenerEndpointRegistrar.java
- spring-kafka/src/main/java/org/springframework/kafka/config/KafkaStreamsCustomizer.java
- spring-kafka/src/main/java/org/springframework/kafka/config/MethodKafkaListenerEndpoint.java
- spring-kafka/src/main/java/org/springframework/kafka/config/StreamsBuilderFactoryBean.java
- spring-kafka/src/main/java/org/springframework/kafka/support/JavaUtils.java
> Further changes for nullability in the config package

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaOperations.java
> GH-3813: add missing nullability annotations to KafkaOperations

- spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java
This PR validates the `@ Headers` annotation 
https://docs.spring.io/spring-kafka/reference/kafka/headers.html
> Add integration test for @Headers annotation

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/container-props.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/micrometer.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/message-listener-container.adoc
- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/sending-messages.adoc
The document contains words written in plural form, so I think we can avoid the plural form by using double backticks instead of spaces.
> Fix plural words

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/receiving-messages/class-level-kafkalistener.adoc
- Fixes #3880 
```java
// HandlerAdapter.java
Object[] args = new Object[providedArgs.length + 1];
args[0] = message.getPayload();
System.arraycopy(providedArgs, 0, args, 1, providedArgs.length);
return this.delegatingHandler.invoke(message, args);
```
If `defaultHandler` is set, the above code is executed.
During this call stack, the `args` array contains a payload of `KafkaMessage`, which is then passed to the invoked method.
[InvocableHandlerMethod.java (L212-L224)](https://github.com/spring-projects/spring-framework/blob/ecdb63371e99b4a285903106dcc06e90b355db53/spring-web/src/main/java/org/springframework/web/method/support/InvocableHandlerMethod.java#L212-L224)
```java
protected @Nullable Object[] getMethodArgumentValues(Message<?> message, @Nullable Object... providedArgs) throws …
```
> GH-3880: The DefaultHandler resolves an incorrect value for the parameter annotated with @Header.

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/retrytopic/topic-naming.adoc
- spring-kafka/src/main/java/org/springframework/kafka/annotation/EnableKafkaRetryTopic.java
- `FixedDelay(Topic)Strategy` -> `SameIntervalTopicReuseStrategy`
- (on RetryTopicConfigurationBuilder) `useSingleTopicForFixedDelays` -> `useSingleTopicForSameIntervals`
> Replace deprecated `FixedDelay` in docs

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/kafka/annotation-error-handling.adoc
`DeadLetterPublishingRecoverer` ctor cannot take `Map<Class<?>, KafkaTemplate<?, ?>` as parameter, because constructor is `Map<Class<?>, KafkaOperations<? extends Object, ? extends Object>>`.
```
$ ./gradlew build
...
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler output below.
/.../config/KafkaConfig.java:161: error: no suitable constructor found for DeadLetterPublishingRecoverer(Map<Class<?>,KafkaTemplate<?,?>>)
return new DeadLetterPublishingRecoverer(templates);
^
constructor DeadLetterPublishingRecoverer.DeadLetterPublishingRecoverer(KafkaOperations<? extends Object,? extends Object>) is not applicable
(argument mismatch; Map<Class<?>,KafkaTemplate<?,?>> cannot be converted to …
```
> Correct `DeadLetterPublishingRecoverer` example to use `KafkaOperations`

- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationSupport.java
Fix annotation name in the docs. (`@EnableRetryTopic` -> `@EnableKafkaRetryTopic`)
> Fix docs `@EnableRetryTopic` to `@EnableKafkaRetryTopic`

- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopic.java
- spring-kafka/src/main/java/org/springframework/kafka/retrytopic/RetryTopicConfigurationBuilder.java
- (1) Fix docs in `RetryableTopic` - The sentence was not properly separated. I think it was confusing.
- (2) Repharased docs in `RetryTopicConfigurationBuilder` to match the wording used in other sections, e.g. change history
https://github.com/spring-projects/spring-kafka/blob/b68db559c4367918c76ed81cef1302ae4892e28a/spring-kafka-docs/src/main/antora/modules/ROOT/pages/appendix/change-history.adoc?plain=1#L298-L299
> Rephrase replication factor documentation

- spring-kafka-docs/src/main/antora/modules/ROOT/pages/testing.adoc
Integration tests with an EmbeddedKafka instance are sometimes run in parallel in Junit. The current example is not thread safe, so I think the official documentation should account for that.
> Altered the example in EmbeddedKafkaHolder usage

- spring-kafka/src/main/java/org/springframework/kafka/core/DefaultShareConsumerFactory.java
- spring-kafka/src/main/java/org/springframework/kafka/core/ShareConsumerFactory.java
- spring-kafka/src/test/java/org/springframework/kafka/core/DefaultShareConsumerFactoryTests.java
- Preliminary set of changes to support Kafka queueus introduced via KIP-932 (Kafka Queue) for early access in Apache Kafka 4.0.0. See: https://cwiki.apache.org/confluence/display/KAFKA/KIP-932%3A+Queues+for+Kafka
- Add ShareConsumerFactory interface and DefaultShareConsumerFactory implementation as the initial building blocks for supporting Kafka Queues (KIP-932) in Spring for Apache Kafka 4.0.x. This factory and the implementation provide a flexible API for creating share consumers, and are designed as the foundation for further queue integration.
- Tests to verify the share consumer behavior
Related to #3875
https://github.com/spring-projects/spring-kafka/issues/3875
> Introduce share consumer factories for Kafka Queues (Early Access)

- spring-kafka/src/main/java/org/springframework/kafka/listener/AbstractShareKafkaMessageListenerContainer.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/ShareKafkaMessageListenerContainer.java
- spring-kafka/src/test/java/org/springframework/kafka/listener/ShareKafkaMessageListenerContainerIntegrationTests.java
- New AbstractShareKafkaMessageListenerContainer base class with lifecycle management
- ShareKafkaMessageListenerContainer implementation for share consumer protocol
- Integration tests for end-to-end message delivery validation
> Add Kafka shared consumer container support

- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/BatchMessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/MessagingMessageListenerAdapter.java
- spring-kafka/src/main/java/org/springframework/kafka/listener/adapter/RecordMessagingMessageListenerAdapter.java
> GH-3979: Revise `MessagingMessageListenerAdapter` ctor  Nullability 

- spring-kafka/src/main/java/org/springframework/kafka/listener/ConcurrentMessageListenerContainer.java
Refactored the partitionSubset method to reduce nesting and improve readability while preserving original behavior.
> refactor: simplify partitionSubset logic in ConcurrentMessageListenerContainer

- spring-kafka/src/main/java/org/springframework/kafka/support/AbstractKafkaHeaderMapper.java
- spring-kafka/src/test/java/org/springframework/kafka/support/DefaultKafkaHeaderMapperTests.java
Fixes: #3879
Issue link: #3879
In previous discussion, we decided to use `LinkedHashMap` for `LruCache` Implementation. 
However, I think that we missed concurrency of KafkaListenerContainer. 
We can set concurrency when we create KafkaListener like `@KafkaListener(concurrency = 10, ....)`. 
But, `LinkedHashMap` is not thread-safe. 
So, I use `ConcurrentLruCache` provided by `spring-framework` to ensure thread-safe.
> GH-3879: Add cache to optimize header match performance.

- spring-kafka/src/main/java/org/springframework/kafka/annotation/RetryableTopicAnnotationProcessor.java
Previously, the `@RetryableTopic.includeNames` and `@RetryableTopic.excludeNames` attributes were not resolved from property placeholders `(${...})` or SpEL expressions `(#{...})`, despite the documentation stating that all String properties support such resolution.
This commit ensures proper resolution via `BeanExpressionResolver` and `BeanFactory`, consistent with the behavior of other annotations like `@KafkaListener`.
> Fix SpEL/placeholder resolution in `@RetryableTopic.includeNames` and `@RetryableTopic.excludeNames`

- spring-kafka/src/main/java/org/springframework/kafka/core/KafkaAdmin.java
Replace O(n²) nested iteration with O(n) map-based lookups for filtering topics Use topicNameToMapKey to efficiently resolve duplicate topic names This improves application startup time and scalability when managing a large number of topics, while preserving the original filtering logic
Resolves: #4025
> Refactor newTopics to remove nested loops

- spring-kafka/src/test/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplateTests.java
This PR addresses issue #4008 by refactoring `ReplyingKafkaTemplateTests`
to improve test maintainability and readability through better
separation of concerns.
- Refactored listener methods to return `Message<?>` objects instead of
handling validation internally
- Extracted header validation logic into separate utility methods
(`validateHeaders`, `validateSuccessfulResponse`)
- Simplified test methods by moving validation concerns outside of
listener logic
- **Listener Methods**: Simplified
`handleCustomReplyHeaderNoReplyPartition` and
`handleCustomReplyHeaderDefaultPartitionHeader` to focus only on business
logic
- **Validation Utilities**: Added `validateHeaders()` and
`validateSuccessfulResponse()` methods for external header verification
- **Test Methods**: Updated …
> GH-4008: Improve ReplyingKafkaTemplateTests with modular validation

- spring-kafka/src/main/java/org/springframework/kafka/support/micrometer/KafkaListenerObservation.java
- spring-kafka/src/test/java/org/springframework/kafka/support/micrometer/ObservationTests.java
This updates the listener observation operation tag according to latest standard.
E.g. [Open Telemetry states](https://github.com/open-telemetry/semantic-conventions/blob/v1.24.0/docs/messaging/messaging-spans.md#consumer):
> The consumer receives, processes, and settles a message. "Receiving" is the process of obtaining a message from the intermediary, **"processing" is the process of acting on the information a message contains**, "settling" is the process of notifying an intermediary that a message was processed successfully.
E.g. [Micrometer JMS follows this](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-jakarta9/src/main/java/io/micrometer/jakarta9/instrument/jms/DefaultJmsProcessObservationConvention.java#L34).
> `private static final KeyValue …
> Update listener observation operation tag
